import type { DictationSentence, FocusInfo, MinimalPair } from './types'

// Sentences come from docs/research/english-errors.md §7 (verified to pass every rule) and
// docs/research/exercises-and-content.md §11.2. Spelling is variety-neutral (no colour/color).

export const FOCUS_EN: Record<string, FocusInfo> = {
  'then-than': { label: 'then/than', title: 'taller than, and then' },
  its: { label: "its/it's", title: "it's raining, its tail" },
  homophone: { label: 'sound-alikes', title: "their/there/they're, your/you're, whose/who's, to/too/two" },
  confusable: { label: 'mix-ups', title: 'lose/loose, affect/effect, advice/advise, life/live' },
  'a-an': { label: 'a/an', title: 'an hour, a university' },
  apostrophe: { label: 'apostrophes', title: "photos, children's, grandparents'" },
  capital: { label: 'capitals', title: 'I, Monday, January, Dutch' },
  spelling: { label: 'tricky words', title: 'necessary, accommodate, definitely' },
  dunglish: { label: 'dunglish', title: 'since/for, lend/borrow, make/do' },
  grammar: { label: 'grammar', title: 'do-questions, should have, fewer/less' },
}

export const DICTATION_EN: DictationSentence[] = [
  /* ---------------- english-errors.md §7 ---------------- */
  {
    id: 'en-d01',
    text: "It's raining, so the dog is hiding in its little house.",
    level: 2,
    focus: ['its'],
    note: { en: "It's = it is. its = belonging to it, with no apostrophe, like his." },
  },
  {
    id: 'en-d02',
    text: "You're going to love your new bike.",
    level: 1,
    focus: ['homophone'],
    note: { en: "You're = you are. your = belonging to you." },
  },
  {
    id: 'en-d03',
    text: "They're sure their bags are over there by the door.",
    level: 2,
    focus: ['homophone'],
    note: { en: "They're = they are. their = belonging to them. there = that place." },
  },
  {
    id: 'en-d04',
    text: 'My sister is taller than me, but then again, she is older.',
    level: 2,
    focus: ['then-than'],
    note: { en: 'than compares (taller than). then is about time or order (then again).' },
  },
  {
    id: 'en-d05',
    text: 'I should have called you before I left.',
    level: 1,
    focus: ['grammar'],
    note: { en: 'should have, never should of. It only sounds like of.' },
  },
  {
    id: 'en-d06',
    text: 'My jeans are loose now, so I hope I do not lose them on the bus.',
    level: 2,
    focus: ['confusable'],
    note: { en: 'loose = not tight (rhymes with goose). lose = misplace (rhymes with shoes).' },
  },
  {
    id: 'en-d07',
    text: 'The cold weather did not affect the result, but the new rule had a big effect.',
    level: 3,
    focus: ['confusable'],
    note: { en: 'affect is the verb, effect is the noun (a big effect).' },
  },
  {
    id: 'en-d08',
    text: 'It took an hour to walk to a university near an old castle.',
    level: 2,
    focus: ['a-an'],
    note: { en: 'a or an goes by sound: an hour (silent h), a university (starts with a y sound).' },
  },
  {
    id: 'en-d09',
    text: "Whose phone is ringing, and who's going to answer it?",
    level: 2,
    focus: ['homophone'],
    note: { en: "Whose = belonging to whom. who's = who is." },
  },
  {
    id: 'en-d10',
    text: 'It is too late to buy two tickets for the concert.',
    level: 1,
    focus: ['homophone'],
    note: { en: 'too = very or also, to = towards, two = 2.' },
  },
  {
    id: 'en-d11',
    text: 'Everyone accepted the invitation except Tom.',
    level: 1,
    focus: ['confusable'],
    note: { en: 'accept = say yes to. except = apart from.' },
  },
  {
    id: 'en-d12',
    text: 'My teacher gave me good advice, and I advise you to listen to her too.',
    level: 2,
    focus: ['confusable'],
    note: { en: 'advice is the noun (s sound), advise is the verb (z sound).' },
  },
  {
    id: 'en-d13',
    text: "I think I left my glasses at home, but I'm not sure.",
    level: 1,
    focus: ['capital'],
    note: { en: "I is always a capital, also in I'm." },
  },
  {
    id: 'en-d14',
    text: 'I definitely need a lot of time to separate the old receipts.',
    level: 2,
    focus: ['spelling'],
    note: { en: 'definitely (finite inside), separate (a rat in the middle), receipt (silent p). a lot is two words.' },
  },
  {
    id: 'en-d15',
    text: 'The hotel can accommodate twelve guests, so a separate room is not necessary.',
    level: 3,
    focus: ['spelling'],
    note: { en: 'accommodate: double c and double m. necessary: one c, double s.' },
  },
  {
    id: 'en-d16',
    text: 'I have lived in Utrecht since 2015.',
    level: 1,
    focus: ['dunglish'],
    note: { en: 'since + a starting point, with have lived. Not I live here since.' },
  },
  {
    id: 'en-d17',
    text: 'We have known each other for ten years.',
    level: 1,
    focus: ['dunglish'],
    note: { en: 'for + a period of time, with the present perfect (have known).' },
  },
  {
    id: 'en-d18',
    text: 'Can you lend me your pen? I will give it back after class.',
    level: 2,
    focus: ['dunglish'],
    note: { en: 'lend = give for a while, borrow = take for a while. Never borrow me.' },
  },
  {
    id: 'en-d19',
    text: 'May I borrow your charger for a moment?',
    level: 1,
    focus: ['dunglish'],
    note: { en: 'borrow = take for a while, from someone.' },
  },
  {
    id: 'en-d20',
    text: 'My grandmother taught me how to bake bread.',
    level: 1,
    focus: ['dunglish'],
    note: { en: 'Someone teaches you (taught me). You learn something yourself.' },
  },
  {
    id: 'en-d21',
    text: 'We took a lot of photos on the beach last weekend.',
    level: 1,
    focus: ['dunglish', 'apostrophe'],
    note: { en: 'take a photo, not make. photos: a plural, so no apostrophe.' },
  },
  {
    id: 'en-d22',
    text: 'Have you done your homework, or are you still making mistakes?',
    level: 2,
    focus: ['dunglish'],
    note: { en: 'do homework, make mistakes.' },
  },
  {
    id: 'en-d24',
    text: 'Could you give me some information about the trains to Amsterdam?',
    level: 2,
    focus: ['grammar', 'capital'],
    note: { en: 'information has no plural: some information.' },
  },
  {
    id: 'en-d25',
    text: "I agree with you, but my brother doesn't agree with either of us.",
    level: 2,
    focus: ['grammar'],
    note: { en: "I agree, not I am agree. doesn't = does not." },
  },
  {
    id: 'en-d26',
    text: 'He goes to the gym every Monday and Thursday in January.',
    level: 1,
    focus: ['capital'],
    note: { en: 'Days and months take a capital in English (not in Dutch).' },
  },
  {
    id: 'en-d27',
    text: 'My parents speak Dutch and Arabic, and I am learning English.',
    level: 2,
    focus: ['capital'],
    note: { en: 'Languages take a capital: Dutch, Arabic, English.' },
  },
  {
    id: 'en-d28',
    text: 'This book is much better than the film.',
    level: 1,
    focus: ['then-than'],
    note: { en: 'better than: than after a comparison.' },
  },
  {
    id: 'en-d29',
    text: 'Most people in my class live near the station.',
    level: 1,
    focus: ['grammar'],
    note: { en: 'Most people, not the most people.' },
  },
  {
    id: 'en-d30',
    text: 'I want to enjoy my whole life and live by the sea.',
    level: 1,
    focus: ['confusable'],
    note: { en: 'life is the noun (my life), live is the verb (to live).' },
  },
  {
    id: 'en-d31',
    text: 'We might possibly move next year, and eventually we want to buy a house.',
    level: 2,
    focus: ['dunglish'],
    note: { en: 'eventually = in the end. The Dutch eventueel is possibly.' },
  },
  {
    id: 'en-d32',
    text: 'The current situation is difficult, but the actual problem is money.',
    level: 2,
    focus: ['dunglish'],
    note: { en: 'current = happening now (actueel). actual = real (eigenlijk).' },
  },
  {
    id: 'en-d33',
    text: 'When do you usually go home after work?',
    level: 1,
    focus: ['grammar'],
    note: { en: 'Questions need do: when do you go, not when go you.' },
  },
  {
    id: 'en-d34',
    text: "I don't like cold coffee, and he doesn't either.",
    level: 1,
    focus: ['grammar'],
    note: { en: "Negatives need do: don't, doesn't." },
  },
  {
    id: 'en-d35',
    text: 'Please park the car near the big blue building.',
    level: 1,
    focus: ['spelling'],
    note: { en: 'p and b: park, big, blue, building.' },
  },
  {
    id: 'en-d36',
    text: 'Peter put the paper bag on the back seat of the bus.',
    level: 1,
    focus: ['spelling', 'capital'],
    note: { en: 'p and b: Peter, put, paper, bag, back, bus.' },
  },
  {
    id: 'en-d37',
    text: 'My brother is a teacher, and my sister is an engineer.',
    level: 1,
    focus: ['a-an'],
    note: { en: 'a teacher, an engineer: an before a vowel sound.' },
  },
  {
    id: 'en-d38',
    text: 'Life is short, so money is not the most important thing.',
    level: 1,
    focus: ['grammar'],
    note: { en: 'No the for general ideas: life, money.' },
  },
  {
    id: 'en-d39',
    text: 'She is very tired because she is very busy.',
    level: 1,
    focus: ['grammar'],
    note: { en: 'English needs the verb: she is tired.' },
  },
  {
    id: 'en-d40',
    text: 'Please fill the bin with paper and feel free to sit on the seat.',
    level: 2,
    focus: ['spelling'],
    note: { en: 'fill and feel, sit and seat: short i against long ee.' },
  },
  {
    id: 'en-d41',
    text: 'When can I call you, and why are you late?',
    level: 1,
    focus: ['grammar'],
    note: { en: 'Question order: can I, are you.' },
  },
  {
    id: 'en-d42',
    text: 'I went to the market. I bought some fruit, and then I walked home.',
    level: 2,
    focus: ['then-than'],
    note: { en: 'and then: then is about time.' },
  },
  {
    id: 'en-d43',
    text: 'Wait, what is that? Hello, my name is Sara.',
    level: 1,
    focus: ['capital'],
    note: { en: 'Names and sentence starts take a capital. No space before a question mark.' },
  },
  {
    id: 'en-d44',
    text: 'We discussed the plan and explained it to our manager.',
    level: 1,
    focus: ['dunglish'],
    note: { en: 'discuss something, without about. explain it to someone.' },
  },
  {
    id: 'en-d45',
    text: 'She has been married to Omar for five years.',
    level: 1,
    focus: ['dunglish'],
    note: { en: 'married to, not with. for five years.' },
  },
  {
    id: 'en-d46',
    text: 'Their colleagues were surprised by the beautiful weather on Wednesday.',
    level: 2,
    focus: ['spelling', 'homophone', 'capital'],
    note: { en: 'colleague, surprised, beautiful, weather, Wednesday: none is spelled the way it sounds.' },
  },
  {
    id: 'en-d47',
    text: 'There are five of us, so we need a bigger table.',
    level: 1,
    focus: ['dunglish'],
    note: { en: 'There are five of us, not we are with five.' },
  },
  {
    id: 'en-d48',
    text: 'In my opinion, the second option is better than the first.',
    level: 1,
    focus: ['then-than'],
    note: { en: 'better than. In my opinion, not according to me.' },
  },
  {
    id: 'en-d49',
    text: 'Whether we go or not depends on the weather.',
    level: 1,
    focus: ['homophone'],
    note: { en: 'whether = if, weather = rain or sun. depend on.' },
  },
  {
    id: 'en-d50',
    text: 'Which restaurant would you recommend for a business dinner?',
    level: 2,
    focus: ['spelling'],
    note: { en: 'recommend: one c, double m. restaurant and business have silent letters.' },
  },
  {
    id: 'en-d51',
    text: 'The babies were asleep, so we turned off the radios and put away the photos.',
    level: 2,
    focus: ['apostrophe'],
    note: { en: 'Plurals take no apostrophe: babies, radios, photos.' },
  },
  {
    id: 'en-d52',
    text: 'The woman who lives next door is a nurse.',
    level: 1,
    focus: ['grammar'],
    note: { en: 'who for people, which for things.' },
  },
  {
    id: 'en-d53',
    text: 'I will definitely wait until tomorrow before I decide.',
    level: 1,
    focus: ['spelling'],
    note: { en: 'until has one l. tomorrow has one m and double r.' },
  },
  {
    id: 'en-d54',
    text: 'She is interested in business, and her first shop was a big success.',
    level: 2,
    focus: ['spelling'],
    note: { en: 'success: double c, double s. business: the i is silent.' },
  },
  {
    id: 'en-d55',
    text: 'It was embarrassing because the mistake occurred twice.',
    level: 2,
    focus: ['spelling'],
    note: { en: 'embarrassing: double r, double s. occurred: double c, double r.' },
  },

  /* ---------------- exercises-and-content.md §11.2 ---------------- */
  {
    id: 'en-c01',
    text: "It's raining, so the cat stays inside.",
    level: 1,
    focus: ['its'],
    note: { en: "It's = it is." },
  },
  {
    id: 'en-c02',
    text: 'The dog is chasing its own tail.',
    level: 1,
    focus: ['its'],
    note: { en: 'its = belonging to it. No apostrophe.' },
  },
  {
    id: 'en-c03',
    text: "They're waiting for their friends over there.",
    level: 1,
    focus: ['homophone'],
    note: { en: "They're = they are. their = belonging to them. there = that place." },
  },
  {
    id: 'en-c04',
    text: "You're right: your keys were in the kitchen.",
    level: 1,
    focus: ['homophone'],
    note: { en: "You're = you are. your = belonging to you." },
  },
  {
    id: 'en-c05',
    text: 'My brother is taller than I am.',
    level: 1,
    focus: ['then-than'],
    note: { en: 'than compares: taller than.' },
  },
  {
    id: 'en-c06',
    text: 'We ate dinner, and then we went for a walk.',
    level: 1,
    focus: ['then-than'],
    note: { en: 'then is about time: first dinner, then a walk.' },
  },
  {
    id: 'en-c07',
    text: 'I want to buy two tickets, and my friend wants one too.',
    level: 1,
    focus: ['homophone'],
    note: { en: 'to buy, two tickets, one too (also).' },
  },
  {
    id: 'en-c08',
    text: 'I would like a piece of cake, please.',
    level: 1,
    focus: ['homophone'],
    note: { en: 'piece = a part. peace = no war.' },
  },
  {
    id: 'en-c09',
    text: 'On Monday we have a meeting in English.',
    level: 1,
    focus: ['capital'],
    note: { en: 'Days and languages take a capital in English.' },
  },
  {
    id: 'en-c10',
    text: "Whose bag is this, and who's going to carry it?",
    level: 1,
    focus: ['homophone'],
    note: { en: "Whose = belonging to whom. who's = who is." },
  },
  {
    id: 'en-c11',
    text: 'If the screw is loose, you might lose the wheel.',
    level: 2,
    focus: ['confusable'],
    note: { en: 'loose = not tight. lose = misplace.' },
  },
  {
    id: 'en-c12',
    text: "The weather was so bad that we didn't know whether to go out.",
    level: 2,
    focus: ['homophone'],
    note: { en: 'weather = rain or sun. whether = if.' },
  },
  {
    id: 'en-c13',
    text: 'I believe she received the letter last Wednesday.',
    level: 2,
    focus: ['spelling', 'capital'],
    note: { en: 'i before e (believe), except after c (received). Wednesday hides a d.' },
  },
  {
    id: 'en-c14',
    text: "The noise didn't affect me, but it had a strange effect on the dog.",
    level: 2,
    focus: ['confusable'],
    note: { en: 'affect is the verb, effect is the noun.' },
  },
  {
    id: 'en-c16',
    text: 'It was quite late, and the street was quiet.',
    level: 2,
    focus: ['confusable'],
    note: { en: 'quite = fairly (rhymes with white). quiet = not loud (two syllables).' },
  },
  {
    id: 'en-c17',
    text: 'Take a deep breath, and try to breathe slowly.',
    level: 2,
    focus: ['confusable'],
    note: { en: 'breath is the noun. breathe, with an e, is the verb.' },
  },
  {
    id: 'en-c18',
    text: 'There were fewer people than last year, but there was less noise.',
    level: 2,
    focus: ['grammar', 'then-than'],
    note: { en: 'fewer for things you can count, less for amounts. fewer than.' },
  },
  {
    id: 'en-c19',
    text: 'Time passed quickly, and soon the past felt very far away.',
    level: 2,
    focus: ['homophone'],
    note: { en: 'passed is the verb. past is the noun or adjective.' },
  },
  {
    id: 'en-c20',
    text: "The children's toys were all over the living room floor.",
    level: 2,
    focus: ['apostrophe'],
    note: { en: "children is already plural, so children's." },
  },
  {
    id: 'en-c21',
    text: 'The committee will definitely need a separate room for the meeting.',
    level: 3,
    focus: ['spelling'],
    note: { en: 'committee: double m, double t, double e.' },
  },
  {
    id: 'en-c22',
    text: 'It is not necessary to accommodate every request, and nobody should feel embarrassed about that.',
    level: 3,
    focus: ['spelling'],
    note: { en: 'necessary, accommodate, embarrassed: count the double letters.' },
  },
  {
    id: 'en-c23',
    text: 'The principal explained the principle behind the new rule.',
    level: 3,
    focus: ['homophone'],
    note: { en: 'principal = head of a school. principle = a rule or idea.' },
  },
  {
    id: 'en-c24',
    text: 'I bought some stationery, but the bus remained stationary for an hour.',
    level: 3,
    focus: ['homophone', 'a-an'],
    note: { en: 'stationery has e for envelopes. stationary has a for standing still. an hour.' },
  },
  {
    id: 'en-c25',
    text: 'She complimented him on his tie, which complemented his jacket perfectly.',
    level: 3,
    focus: ['homophone'],
    note: { en: 'compliment = say something nice. complement = complete or match.' },
  },
  {
    id: 'en-c26',
    text: 'The desert was so hot that our dessert melted in seconds.',
    level: 3,
    focus: ['confusable'],
    note: { en: "dessert has two s's, like the second helping you want." },
  },
  {
    id: 'en-c27',
    text: 'We could have arrived earlier if we had checked the timetable.',
    level: 3,
    focus: ['grammar'],
    note: { en: 'could have, never could of.' },
  },
  {
    id: 'en-c28',
    text: "The parrot's owners hadn't noticed that its cage was open.",
    level: 3,
    focus: ['its', 'apostrophe'],
    note: { en: "parrot's: belonging to the parrot. its cage: no apostrophe." },
  },
  {
    id: 'en-c29',
    text: "Neither of the twins knows where their grandparents' house is.",
    level: 3,
    focus: ['grammar', 'apostrophe'],
    note: { en: "Neither takes a singular verb (knows). grandparents': plural, so the apostrophe goes after the s." },
  },
  {
    id: 'en-c30',
    text: 'Please lay the book on the table, and then lie down for a while.',
    level: 3,
    focus: ['confusable', 'then-than'],
    note: { en: 'You lay something down. You lie down yourself.' },
  },
]

export const PAIRS_EN: MinimalPair[] = [
  {
    id: 'then-than',
    lang: 'en',
    words: ['then', 'than'],
    note: { en: 'than compares (older than, rather than). then is about time or order (and then).' },
    sentences: [
      { text: 'She is older than her brother.', word: 'than' },
      { text: 'We had lunch, and then we went home.', word: 'then' },
      { text: 'I would rather walk than take the bus.', word: 'than' },
      { text: 'Finish your homework first, then you can play.', word: 'then' },
      { text: 'It is colder today than yesterday.', word: 'than' },
      { text: 'Back then, nobody had a phone.', word: 'then' },
    ],
  },
  {
    id: 'lose-loose',
    lang: 'en',
    words: ['lose', 'loose'],
    note: { en: "lose (one o, z sound) = misplace or not win. loose (two o's, s sound) = not tight." },
    sentences: [
      { text: "Don't lose your ticket.", word: 'lose' },
      { text: 'This shirt is too loose.', word: 'loose' },
      { text: 'We always lose when it rains.', word: 'lose' },
      { text: 'One of the screws is loose.', word: 'loose' },
    ],
  },
  {
    id: 'life-live',
    lang: 'en',
    words: ['life', 'live'],
    note: { en: 'life is the noun (my life). live is the verb (I live).' },
    sentences: [
      { text: 'I love my life in Utrecht.', word: 'life' },
      { text: 'I live in Utrecht.', word: 'live' },
      { text: 'Where do you live now?', word: 'live' },
      { text: 'Life is too short for bad coffee.', word: 'Life' },
      { text: 'They live next to a big park.', word: 'live' },
    ],
  },
  {
    id: 'price-prize',
    lang: 'en',
    words: ['price', 'prize'],
    note: { en: 'price = what it costs (s sound). prize = what you win (z sound).' },
    sentences: [
      { text: 'The price of bread went up again.', word: 'price' },
      { text: 'She won first prize in the contest.', word: 'prize' },
      { text: 'What is the price of this jacket?', word: 'price' },
      { text: 'The prize is a trip to Paris.', word: 'prize' },
    ],
  },
  {
    id: 'advice-advise',
    lang: 'en',
    words: ['advice', 'advise'],
    note: { en: 'advice is the noun (s sound). advise is the verb (z sound).' },
    sentences: [
      { text: 'Can you give me some advice?', word: 'advice' },
      { text: 'I advise you to leave early.', word: 'advise' },
      { text: 'Thanks for the advice.', word: 'advice' },
      { text: 'Doctors advise people to sleep more.', word: 'advise' },
    ],
  },
  {
    id: 'its-its',
    lang: 'en',
    words: ['its', "it's"],
    note: { en: "it's = it is or it has. its = belonging to it, like his, with no apostrophe." },
    sentences: [
      { text: "It's cold outside.", word: "It's" },
      { text: 'The company changed its name.', word: 'its' },
      { text: "I think it's time to go.", word: "it's" },
      { text: 'The bird hurt its wing.', word: 'its' },
    ],
  },
  {
    id: 'your-youre',
    lang: 'en',
    words: ['your', "you're"],
    note: { en: "you're = you are. your = belonging to you." },
    sentences: [
      { text: 'Your coffee is getting cold.', word: 'Your' },
      { text: "You're late again.", word: "You're" },
      { text: 'Is this your umbrella?', word: 'your' },
      { text: "I think you're right.", word: "you're" },
    ],
  },
  {
    id: 'their-there',
    lang: 'en',
    words: ['their', 'there', "they're"],
    note: { en: "their = belonging to them. there = that place, or there is. they're = they are." },
    sentences: [
      { text: 'Their house has a red door.', word: 'Their' },
      { text: 'Put the box over there.', word: 'there' },
      { text: "They're coming at eight.", word: "They're" },
      { text: 'There is no milk left.', word: 'There' },
      { text: 'The kids lost their shoes.', word: 'their' },
      { text: "I hope they're not lost.", word: "they're" },
    ],
  },
  {
    id: 'weather-whether',
    lang: 'en',
    words: ['weather', 'whether'],
    note: { en: 'weather = rain or sun. whether = if.' },
    sentences: [
      { text: 'The weather is lovely today.', word: 'weather' },
      { text: "I don't know whether he is coming.", word: 'whether' },
      { text: 'We will go whether it rains or not.', word: 'whether' },
      { text: 'Bad weather closed the airport.', word: 'weather' },
    ],
  },
]
