import type { DictationSentence, FocusInfo, MinimalPair } from './types'

// Sentences come from docs/research/dutch-errors.md §9 (46 + 8, checked against the OpenTaal
// list and by hand) and docs/research/exercises-and-content.md §11.1 (40). Notes are short:
// the trap, the rule, nothing more.

export const FOCUS_NL: Record<string, FocusInfo> = {
  dt: { label: 'd/t', title: 'ik word, hij wordt, word jij' },
  participle: { label: 'gebeurd/gebeurt', title: 'Participle or present tense' },
  past: { label: 'past tense', title: "'t kofschip and strong verbs: werkte, woonde, vond" },
  'ei-ij': { label: 'ei/ij, au/ou', title: 'leiden/lijden, eik, koud' },
  'de-het': { label: 'de/het', title: 'die/dat, het grote huis' },
  'als-dan': { label: 'als/dan', title: 'groter dan, zo groot als' },
  pronoun: { label: 'hun/me/jouw', title: 'hun/hen, me/mijn, jou/jouw' },
  compound: { label: 'compounds', title: 'One word or two, tussen-n, hyphens' },
  trema: { label: 'trema', title: 'ideeën, België, geüpdatet' },
  apostrophe: { label: 'apostrophes', title: "auto's, foto's, cafés" },
  capital: { label: 'capitals', title: 'maandag, januari, Nederlands' },
  spelling: { label: 'tricky words', title: 'per se, sowieso, te allen tijde' },
}

export const DICTATION_NL: DictationSentence[] = [
  /* ---------------- dutch-errors.md §9 ---------------- */
  {
    id: 'nl-r01',
    text: 'Word je morgen ook om zeven uur opgehaald, of wordt je zus eerst gebracht?',
    level: 3,
    focus: ['dt', 'pronoun'],
    note: {
      en: 'Word je: je comes after the verb, so no t. Wordt je zus: here je means jouw, the subject is je zus, so the verb gets a t.',
      local: 'Word je: je staat achter het werkwoord, dus geen t. Wordt je zus: je betekent hier jouw, het onderwerp is je zus, dus wel een t.',
    },
  },
  {
    id: 'nl-r02',
    text: 'Hij wordt elke dag om zes uur wakker, maar ik word pas om acht uur wakker.',
    level: 2,
    focus: ['dt'],
    note: { en: 'hij + stem + t: hij wordt. ik + stem: ik word.', local: 'hij + stam + t: hij wordt. ik + stam: ik word.' },
  },
  {
    id: 'nl-r03',
    text: 'Vind jij het ook raar dat hij nooit antwoordt als je hem iets vraagt?',
    level: 2,
    focus: ['dt'],
    note: {
      en: 'Vind jij: jij after the verb, so no t. Hij antwoordt: stem antwoord + t.',
      local: 'Vind jij: jij achter het werkwoord, dus geen t. Hij antwoordt: stam antwoord + t.',
    },
  },
  {
    id: 'nl-r04',
    text: 'Wat er gisteren is gebeurd, gebeurt hopelijk nooit meer.',
    level: 2,
    focus: ['participle'],
    note: {
      en: 'is gebeurd: a participle after an auxiliary ends in d. gebeurt: present tense, stem + t.',
      local: 'is gebeurd: voltooid deelwoord na een hulpwerkwoord, met d. gebeurt: tegenwoordige tijd, stam + t.',
    },
  },
  {
    id: 'nl-r05',
    text: 'Ze heeft haar tekst drie keer verbeterd en nu verbetert ze die van haar broer.',
    level: 3,
    focus: ['participle', 'dt'],
    note: {
      en: 'heeft verbeterd: participle with d. verbetert ze: only jij/je drops the t after the verb, ze keeps it.',
      local: 'heeft verbeterd: voltooid deelwoord met d. verbetert ze: alleen bij jij/je valt de t weg, bij ze niet.',
    },
  },
  {
    id: 'nl-r06',
    text: 'De docent beantwoordt nu de vragen die hij vorige week niet heeft beantwoord.',
    level: 3,
    focus: ['participle', 'dt'],
    note: {
      en: 'beantwoordt: present, stem beantwoord + t. heeft beantwoord: participle without ge- and without an extra d.',
      local: 'beantwoordt: tegenwoordige tijd, stam beantwoord + t. heeft beantwoord: voltooid deelwoord, zonder ge- en zonder extra d.',
    },
  },
  {
    id: 'nl-r07',
    text: 'Wordt u al geholpen, of mag ik u even iets vragen?',
    level: 2,
    focus: ['dt'],
    note: { en: 'u always takes stem + t, also after the verb: wordt u.', local: 'Bij u komt er altijd stam + t, ook achter het werkwoord: wordt u.' },
  },
  {
    id: 'nl-r08',
    text: 'Hij vond zijn sleutels pas terug nadat hij het hele huis had doorzocht.',
    level: 2,
    focus: ['past'],
    note: { en: 'vond is a strong past tense. The past tense never ends in dt.', local: 'vond is een sterke verleden tijd. In de verleden tijd schrijf je nooit dt.' },
  },
  {
    id: 'nl-r09',
    text: 'Ik houd van pannenkoeken met stroop, maar mijn vriendin houdt meer van poffertjes.',
    level: 2,
    focus: ['dt', 'compound'],
    note: {
      en: 'ik houd (or ik hou), mijn vriendin houdt: stem + t. pannenkoeken has a linking -en-.',
      local: 'ik houd (of ik hou), mijn vriendin houdt: stam + t. In pannenkoeken zit een tussen-n.',
    },
  },
  {
    id: 'nl-r10',
    text: 'Het meisje dat naast mij woont, heeft een hond die heel hard blaft.',
    level: 2,
    focus: ['de-het'],
    note: { en: 'het meisje, so dat. de hond, so die.', local: 'het meisje, dus dat. de hond, dus die.' },
  },
  {
    id: 'nl-r11',
    text: 'Het boek dat ik gisteren heb gekocht, ligt nu op de tafel in de woonkamer.',
    level: 2,
    focus: ['de-het'],
    note: { en: 'het boek, so dat. ligt is spelled with g (liggen).', local: 'het boek, dus dat. ligt schrijf je met g (liggen).' },
  },
  {
    id: 'nl-r12',
    text: 'Zij zijn groter dan wij, maar niet zo groot als onze buren.',
    level: 2,
    focus: ['als-dan'],
    note: {
      en: 'A comparative takes dan (groter dan). Equal takes als (zo groot als).',
      local: 'Na een vergrotende trap komt dan (groter dan). Bij gelijkheid komt als (zo groot als).',
    },
  },
  {
    id: 'nl-r13',
    text: 'Zij hebben hun huiswerk vergeten, dus de leraar heeft hun een extra opdracht gegeven.',
    level: 3,
    focus: ['pronoun'],
    note: {
      en: 'hun huiswerk: possessive. heeft hun gegeven: hun as the indirect object (to them).',
      local: 'hun huiswerk: bezittelijk. heeft hun gegeven: hun als meewerkend voorwerp (aan hen).',
    },
  },
  {
    id: 'nl-r14',
    text: 'Hoe laat begint de film die jij zo graag wilt zien?',
    level: 2,
    focus: ['de-het', 'dt'],
    note: { en: 'de film, so die. jij wilt and jij wil are both correct.', local: 'de film, dus die. jij wilt en jij wil zijn allebei goed.' },
  },
  {
    id: 'nl-r15',
    text: "Ik heb mijn telefoon geüpdatet en daarna alle foto's gedownload.",
    level: 2,
    focus: ['past', 'trema', 'apostrophe'],
    note: {
      en: "updaten: the stem ends in a t sound, so geüpdatet, with a trema. downloaden: gedownload. foto's: apostrophe after a long vowel.",
      local: "updaten: de stam eindigt op een t-klank, dus geüpdatet, met trema. downloaden: gedownload. foto's: apostrof na een lange klinker.",
    },
  },
  {
    id: 'nl-r16',
    text: "De auto's van mijn ooms staan al dagen voor het ziekenhuis geparkeerd.",
    level: 2,
    focus: ['apostrophe', 'compound'],
    note: {
      en: "auto's: a final long vowel gets 's. ooms needs no apostrophe. ziekenhuis is one word.",
      local: "auto's: na een lange klinker aan het eind komt 's. ooms heeft geen apostrof nodig. ziekenhuis is één woord.",
    },
  },
  {
    id: 'nl-r17',
    text: 'Bij de snackbar bestel ik altijd een kaassoufflé en een portie patat.',
    level: 2,
    focus: ['compound', 'trema'],
    note: { en: 'kaassoufflé is one word, with é at the end.', local: 'kaassoufflé is één woord, met é aan het eind.' },
  },
  {
    id: 'nl-r18',
    text: "Mijn ideeën over de coördinatie van het project zijn heel anders dan die van mijn collega's.",
    level: 3,
    focus: ['trema', 'als-dan', 'apostrophe'],
    note: {
      en: 'ideeën and coördinatie get a trema so you read the vowels apart. anders dan, not anders als.',
      local: 'ideeën en coördinatie krijgen een trema, zodat je de klinkers los leest. anders dan, niet anders als.',
    },
  },
  {
    id: 'nl-r19',
    text: 'We zijn in België geweest en hebben daar veel cafés en musea bezocht.',
    level: 2,
    focus: ['trema', 'apostrophe', 'capital'],
    note: {
      en: 'België has a trema. cafés: plural with s and no apostrophe, because the é is stressed.',
      local: 'België heeft een trema. cafés: meervoud met s zonder apostrof, want de é heeft klemtoon.',
    },
  },
  {
    id: 'nl-r20',
    text: 'Eigenlijk wil ik niet per se winnen, maar ik doe sowieso mee.',
    level: 2,
    focus: ['spelling'],
    note: { en: 'per se is two words, sowieso is one.', local: 'per se schrijf je los, sowieso aan elkaar.' },
  },
  {
    id: 'nl-r21',
    text: 'Het enige wat ik wil, is dat iedereen te allen tijde veilig is.',
    level: 2,
    focus: ['spelling', 'de-het'],
    note: { en: 'het enige wat (not dat), and te allen tijde with allen.', local: 'het enige wat (niet dat), en te allen tijde met allen.' },
  },
  {
    id: 'nl-r22',
    text: 'Beide kinderen waren ziek, dus zijn ze allebei thuisgebleven.',
    level: 2,
    focus: ['compound'],
    note: { en: 'thuisgebleven is one word.', local: 'thuisgebleven is één woord.' },
  },
  {
    id: 'nl-r23',
    text: 'Op maandag 3 januari spreken we Nederlands, Engels en Arabisch met onze nieuwe buren.',
    level: 3,
    focus: ['capital'],
    note: {
      en: 'Days and months are lowercase in Dutch. Languages get a capital.',
      local: 'Dagen en maanden schrijf je met een kleine letter, talen met een hoofdletter.',
    },
  },
  {
    id: 'nl-r24',
    text: 'Het verhaal dat jij vertelde, klopte niet; dat heb ik meteen gemerkt.',
    level: 2,
    focus: ['past', 'de-het'],
    note: {
      en: "vertellen: l is not in 't kofschip, so vertelde. kloppen: p is, so klopte.",
      local: "vertellen: de l zit niet in 't kofschip, dus vertelde. kloppen: de p wel, dus klopte.",
    },
  },
  {
    id: 'nl-r25',
    text: 'Hij verhuisde vorig jaar naar Utrecht en leefde daar heel rustig.',
    level: 2,
    focus: ['past'],
    note: {
      en: 'Go by the infinitive: verhuizen (z) gives verhuisde, leven (v) gives leefde.',
      local: 'Kijk naar het hele werkwoord: verhuizen (z) wordt verhuisde, leven (v) wordt leefde.',
    },
  },
  {
    id: 'nl-r26',
    text: 'Wie heeft het laatste stuk taart opgegeten dat in de koelkast stond?',
    level: 2,
    focus: ['de-het'],
    note: { en: 'het stuk ... dat, even with taart in between.', local: 'het stuk ... dat, ook al staat taart ertussen.' },
  },
  {
    id: 'nl-r27',
    text: 'Ik zet de vaas op de tafel en ga daarna even op de bank liggen.',
    level: 2,
    focus: ['dt'],
    note: { en: 'ik zet: the stem already ends in t, nothing to add.', local: 'ik zet: de stam eindigt al op t, er komt niets bij.' },
  },
  {
    id: 'nl-r28',
    text: 'Kun jij me vertellen waar mijn tas ligt? Ik heb hem net nog gezien.',
    level: 2,
    focus: ['pronoun'],
    note: { en: 'me is an object (me vertellen), mijn is possessive (mijn tas).', local: 'me is een voorwerp (me vertellen), mijn is bezittelijk (mijn tas).' },
  },
  {
    id: 'nl-r29',
    text: 'Het wordt tijd dat je je kamer opruimt, want het ziet er niet uit.',
    level: 2,
    focus: ['dt', 'pronoun'],
    note: {
      en: 'het wordt: stem + t. dat je je kamer opruimt: je comes before the verb, so stem + t.',
      local: 'het wordt: stam + t. dat je je kamer opruimt: je staat voor het werkwoord, dus stam + t.',
    },
  },
  {
    id: 'nl-r30',
    text: 'Mijn broer rijdt elke ochtend met de fiets naar zijn werk, ook als het regent.',
    level: 2,
    focus: ['dt'],
    note: { en: 'mijn broer rijdt: stem rijd + t. ik rij is allowed, hij rij is not.', local: 'mijn broer rijdt: stam rijd + t. ik rij mag, hij rij niet.' },
  },
  {
    id: 'nl-r31',
    text: 'Ik besef dat ik te laat ben, maar de trein had vertraging.',
    level: 1,
    focus: ['spelling'],
    note: { en: 'ik besef, not ik besef me: beseffen is not reflexive.', local: 'ik besef, niet ik besef me: beseffen is niet wederkerend.' },
  },
  {
    id: 'nl-r32',
    text: 'Het nieuws dat de minister heeft verspreid, verspreidt zich razendsnel.',
    level: 2,
    focus: ['participle', 'de-het'],
    note: {
      en: 'heeft verspreid: participle. het nieuws verspreidt: stem verspreid + t.',
      local: 'heeft verspreid: voltooid deelwoord. het nieuws verspreidt: stam verspreid + t.',
    },
  },
  {
    id: 'nl-r33',
    text: 'Wie heeft dat verzonnen? Ik heb het nooit zo bedoeld.',
    level: 1,
    focus: ['participle'],
    note: { en: "bedoeld: participle with d, because l is not in 't kofschip.", local: "bedoeld: voltooid deelwoord met d, want de l zit niet in 't kofschip." },
  },
  {
    id: 'nl-r34',
    text: 'De vergadering werd uitgesteld omdat de voorzitter ziek was geworden.',
    level: 2,
    focus: ['past', 'dt'],
    note: { en: 'werd: past tense, never dt. uitgesteld ends in d.', local: 'werd: verleden tijd, nooit dt. uitgesteld eindigt op d.' },
  },
  {
    id: 'nl-r35',
    text: 'Hoe vaak heb je dit al gezegd? Het verandert toch niets.',
    level: 1,
    focus: ['participle', 'dt'],
    note: { en: 'het verandert: present tense, stem + t. Compare: het is veranderd.', local: 'het verandert: tegenwoordige tijd, stam + t. Vergelijk: het is veranderd.' },
  },
  {
    id: 'nl-r36',
    text: 'Ik antwoordde meteen, maar hij heeft nog steeds niet geantwoord.',
    level: 2,
    focus: ['past'],
    note: {
      en: "antwoordde: stem antwoord + de, so two d's. geantwoord: no extra d at the end.",
      local: "antwoordde: stam antwoord + de, dus twee d's. geantwoord: geen extra d aan het eind.",
    },
  },
  {
    id: 'nl-r37',
    text: 'Je bent geïnteresseerd in talen, dus je vindt deze oefening vast leuk.',
    level: 2,
    focus: ['trema', 'dt'],
    note: {
      en: 'geïnteresseerd: trema on the i. je vindt: je before the verb, so stem + t.',
      local: 'geïnteresseerd: trema op de i. je vindt: je voor het werkwoord, dus stam + t.',
    },
  },
  {
    id: 'nl-r38',
    text: 'Morgen leg ik het pakketje bij de buren neer, want ik ben de hele dag weg.',
    level: 2,
    focus: ['dt'],
    note: { en: 'leg ik: ik never gets a t, also not after the verb.', local: 'leg ik: ik krijgt nooit een t, ook niet achter het werkwoord.' },
  },
  {
    id: 'nl-r39',
    text: 'Zijn jullie al aan het nieuwe hoofdstuk begonnen, of moeten we nog even wachten?',
    level: 3,
    focus: ['de-het'],
    note: { en: 'het nieuwe hoofdstuk: after het the adjective gets an e.', local: 'het nieuwe hoofdstuk: na het krijgt het bijvoeglijk naamwoord een e.' },
  },
  {
    id: 'nl-r40',
    text: 'Het kind dat zijn fiets kwijt was, vond hem terug achter de schuur.',
    level: 2,
    focus: ['de-het', 'past'],
    note: { en: 'het kind, so dat. vond: past tense without t.', local: 'het kind, dus dat. vond: verleden tijd zonder t.' },
  },
  {
    id: 'nl-r41',
    text: 'De brandweerman redt de kat, die al uren in de boom zat.',
    level: 1,
    focus: ['dt', 'compound'],
    note: { en: 'redden: stem red + t gives redt.', local: 'redden: stam red + t wordt redt.' },
  },
  {
    id: 'nl-r42',
    text: 'Zij lijdt al jaren aan migraine, maar ze leidt toch haar eigen bedrijf.',
    level: 2,
    focus: ['ei-ij', 'dt'],
    note: {
      en: 'lijden (suffer) with ij, leiden (lead) with ei. Both: stem + t.',
      local: 'lijden (pijn hebben) met ij, leiden (de leiding hebben) met ei. Allebei stam + t.',
    },
  },
  {
    id: 'nl-r43',
    text: 'Hij belooft dat hij op tijd komt, maar dat heeft hij vorige week ook beloofd.',
    level: 3,
    focus: ['participle', 'dt'],
    note: {
      en: 'hij belooft: stem + t. heeft beloofd: participle with d, because beloven has a v.',
      local: 'hij belooft: stam + t. heeft beloofd: voltooid deelwoord met d, want beloven heeft een v.',
    },
  },
  {
    id: 'nl-r44',
    text: 'Gisteren fietste ik naar de markt en kocht ik verse groente.',
    level: 2,
    focus: ['past'],
    note: { en: "fietsen: s is in 't kofschip, so fietste. kocht is a strong verb.", local: "fietsen: de s zit in 't kofschip, dus fietste. kocht is sterk." },
  },
  {
    id: 'nl-r45',
    text: 'Het water bevroor, dus we schaatsten de hele middag op de vijver.',
    level: 2,
    focus: ['past'],
    note: { en: 'schaatsen: the stem schaats ends in s, so schaatste(n).', local: 'schaatsen: de stam schaats eindigt op s, dus schaatste(n).' },
  },
  {
    id: 'nl-r46',
    text: 'Ze heeft de foto geliket en daarna haar profiel geüpdatet.',
    level: 2,
    focus: ['past', 'trema'],
    note: {
      en: 'liken: the stem like is said with a k sound, so geliket. updaten gives geüpdatet.',
      local: 'liken: de stam like klinkt op een k, dus geliket. updaten wordt geüpdatet.',
    },
  },

  /* ---------------- dutch-errors.md §9, listen-and-type extras ---------------- */
  { id: 'nl-k01', text: 'Omdat ik moe ben, ga ik vanavond vroeg naar bed.', level: 1, focus: [] },
  {
    id: 'nl-k02',
    text: 'Ik ken hem niet, maar ik weet wel waar hij woont.',
    level: 1,
    focus: ['spelling'],
    note: { en: 'kennen is for people and places, weten for facts.', local: 'Een persoon ken je, een feit weet je.' },
  },
  {
    id: 'nl-k03',
    text: 'Wij hebben gisteren een groot huis met een mooie tuin gezien.',
    level: 1,
    focus: ['de-het'],
    note: {
      en: 'een groot huis: het-word, no e after een. een mooie tuin: de-word, so an e.',
      local: 'een groot huis: het-woord, na een geen e. een mooie tuin: de-woord, dus wel een e.',
    },
  },
  {
    id: 'nl-k04',
    text: 'Het grote huis op de hoek is van een oude dame die alleen woont.',
    level: 2,
    focus: ['de-het'],
    note: { en: 'het grote huis: after het the adjective gets an e.', local: 'het grote huis: na het krijgt het bijvoeglijk naamwoord een e.' },
  },
  {
    id: 'nl-k05',
    text: 'Ik wachtte een uur op de bus, maar hij kwam niet.',
    level: 1,
    focus: ['past'],
    note: { en: "wachten: stem wacht + te, so two t's.", local: "wachten: stam wacht + te, dus twee t's." },
  },
  {
    id: 'nl-k06',
    text: 'Hebt u het formulier al ingevuld, of zal ik u even helpen?',
    level: 2,
    focus: ['dt'],
    note: { en: 'u hebt and u heeft are both fine. ingevuld ends in d.', local: 'u hebt en u heeft zijn allebei goed. ingevuld eindigt op d.' },
  },
  {
    id: 'nl-k07',
    text: 'Zij zijn vorige zomer naar Marokko gegaan en zijn daar drie weken gebleven.',
    level: 2,
    focus: ['capital'],
    note: { en: 'Countries get a capital: Marokko. Seasons do not: zomer.', local: 'Landen krijgen een hoofdletter: Marokko. Seizoenen niet: zomer.' },
  },
  {
    id: 'nl-k08',
    text: 'Ik ben het helemaal met je eens: dit is een heel mooie dag.',
    level: 1,
    focus: ['spelling'],
    note: { en: 'het eens zijn, without mee. heel mooie, not hele mooie.', local: 'het met iemand eens zijn, zonder mee. heel mooie, niet hele mooie.' },
  },

  /* ---------------- exercises-and-content.md §11.1 ---------------- */
  {
    id: 'nl-d01',
    text: 'Ik word elke ochtend om zeven uur wakker.',
    level: 1,
    focus: ['dt'],
    note: { en: 'ik + stem: ik word.', local: 'ik + stam: ik word.' },
  },
  {
    id: 'nl-d02',
    text: 'Hij wordt morgen twintig jaar.',
    level: 1,
    focus: ['dt'],
    note: { en: 'hij + stem + t: hij wordt.', local: 'hij + stam + t: hij wordt.' },
  },
  {
    id: 'nl-d03',
    text: 'Vind jij die nieuwe fiets ook mooi?',
    level: 1,
    focus: ['dt', 'de-het'],
    note: { en: 'jij after the verb: no t. de fiets, so die.', local: 'jij achter het werkwoord: geen t. de fiets, dus die.' },
  },
  {
    id: 'nl-d04',
    text: 'Mijn zus vindt het huis te klein.',
    level: 1,
    focus: ['dt'],
    note: { en: 'mijn zus is like zij, so stem + t: vindt.', local: 'mijn zus is zij, dus stam + t: vindt.' },
  },
  {
    id: 'nl-d05',
    text: 'Het meisje zit onder de grote eik in de tuin.',
    level: 1,
    focus: ['ei-ij'],
    note: { en: 'eik is spelled with ei.', local: 'eik schrijf je met ei.' },
  },
  {
    id: 'nl-d06',
    text: 'Wij rijden in mei naar de zee.',
    level: 1,
    focus: ['ei-ij', 'capital'],
    note: { en: 'rijden with ij, mei with ei and a lowercase m.', local: 'rijden met ij, mei met ei en een kleine letter.' },
  },
  {
    id: 'nl-d07',
    text: "De baby's slapen al in hun bedjes.",
    level: 1,
    focus: ['apostrophe'],
    note: { en: "baby's: an English word ending in y gets 's.", local: "baby's: een Engels woord op -y krijgt 's." },
  },
  {
    id: 'nl-d08',
    text: 'Ik heb twee ideeën voor het feest.',
    level: 1,
    focus: ['trema'],
    note: { en: 'ideeën: the trema shows a new syllable starts.', local: 'ideeën: het trema laat zien dat er een nieuwe lettergreep begint.' },
  },
  {
    id: 'nl-d09',
    text: 'Het is koud, dus ik trek mijn jas aan.',
    level: 1,
    focus: ['ei-ij'],
    note: { en: 'koud is spelled with ou.', local: 'koud schrijf je met ou.' },
  },
  {
    id: 'nl-d10',
    text: 'De hond van de buren slaapt in een grote hondenmand.',
    level: 1,
    focus: ['compound'],
    note: { en: 'hondenmand: one word, with a linking -en-.', local: 'hondenmand: één woord, met tussen-n.' },
  },
  {
    id: 'nl-d11',
    text: 'Wordt het vandaag warm of koud?',
    level: 1,
    focus: ['dt'],
    note: { en: 'Wordt het: only jij/je drops the t after the verb.', local: 'Wordt het: alleen bij jij/je valt de t weg achter het werkwoord.' },
  },
  {
    id: 'nl-d12',
    text: 'Ik fiets elke dag naar mijn werk.',
    level: 1,
    focus: ['dt'],
    note: { en: 'ik fiets: the stem is fiets, the t belongs to it.', local: 'ik fiets: de stam is fiets, die t hoort erbij.' },
  },
  {
    id: 'nl-d13',
    text: 'Het ijs op de vijver is nog te dun.',
    level: 1,
    focus: ['ei-ij'],
    note: { en: 'ijs and vijver: both with ij.', local: 'ijs en vijver: allebei met ij.' },
  },
  {
    id: 'nl-d14',
    text: "Mijn twee opa's wonen allebei in Zeeland.",
    level: 1,
    focus: ['apostrophe', 'capital'],
    note: { en: "opa's: a final long a gets 's.", local: "opa's: na een lange a aan het eind komt 's." },
  },
  {
    id: 'nl-d15',
    text: 'Word je morgen door je vader of door je moeder opgehaald?',
    level: 2,
    focus: ['dt'],
    note: { en: 'Word je: je after the verb, so no t.', local: 'Word je: je achter het werkwoord, dus geen t.' },
  },
  {
    id: 'nl-d16',
    text: 'Het pakketje is gisteren bezorgd, maar het wordt pas morgen geopend.',
    level: 2,
    focus: ['participle', 'dt'],
    note: { en: 'is bezorgd: participle with d. het wordt: stem + t.', local: 'is bezorgd: voltooid deelwoord met d. het wordt: stam + t.' },
  },
  {
    id: 'nl-d17',
    text: 'Wat er vorige week is gebeurd, vertel ik je later wel.',
    level: 2,
    focus: ['participle'],
    note: { en: 'is gebeurd: participle after is, so d.', local: 'is gebeurd: voltooid deelwoord na is, dus d.' },
  },
  {
    id: 'nl-d18',
    text: 'Hij verbetert zijn fouten meteen, want hij wil een tien halen.',
    level: 2,
    focus: ['participle', 'dt'],
    note: {
      en: 'hij verbetert: present tense, stem + t. There is no auxiliary, so no participle.',
      local: 'hij verbetert: tegenwoordige tijd, stam + t. Er staat geen hulpwerkwoord, dus geen voltooid deelwoord.',
    },
  },
  {
    id: 'nl-d19',
    text: 'Het boek dat op tafel ligt, is van mijn oudste broer.',
    level: 2,
    focus: ['de-het'],
    note: { en: 'het boek, so dat.', local: 'het boek, dus dat.' },
  },
  {
    id: 'nl-d20',
    text: 'De sleutel die ik zocht, lag gewoon in mijn jaszak.',
    level: 2,
    focus: ['de-het', 'compound'],
    note: { en: 'de sleutel, so die. jaszak is one word.', local: 'de sleutel, dus die. jaszak is één woord.' },
  },
  {
    id: 'nl-d21',
    text: 'Ze fietste gisteren naar het strand en zwom een uur in zee.',
    level: 2,
    focus: ['past'],
    note: { en: "fietste: s is in 't kofschip. zwom is strong, no ending.", local: "fietste: de s zit in 't kofschip. zwom is sterk, zonder uitgang." },
  },
  {
    id: 'nl-d22',
    text: 'We hebben de kamer geverfd en daarna de ramen gepoetst.',
    level: 2,
    focus: ['past'],
    note: { en: 'verven has a v, so geverfd. poetsen has an s, so gepoetst.', local: 'verven heeft een v, dus geverfd. poetsen heeft een s, dus gepoetst.' },
  },
  {
    id: 'nl-d23',
    text: "Mijn collega's drinken liever thee dan koffie.",
    level: 2,
    focus: ['apostrophe', 'als-dan'],
    note: { en: "collega's: 's after a long a. liever ... dan.", local: "collega's: 's na een lange a. liever ... dan." },
  },
  {
    id: 'nl-d24',
    text: 'Zij is twee jaar ouder dan ik, maar even groot als mijn broer.',
    level: 2,
    focus: ['als-dan'],
    note: { en: 'ouder dan (comparative), even groot als (equal).', local: 'ouder dan (vergrotende trap), even groot als (gelijkheid).' },
  },
  {
    id: 'nl-d25',
    text: 'Op het station kocht ik een treinkaartje en een broodje kaas.',
    level: 2,
    focus: ['compound'],
    note: { en: 'treinkaartje is one word.', local: 'treinkaartje is één woord.' },
  },
  {
    id: 'nl-d26',
    text: 'In België eten ze vaak frieten met mayonaise.',
    level: 2,
    focus: ['trema', 'spelling'],
    note: { en: 'België with a trema, mayonaise with ai.', local: 'België met trema, mayonaise met ai.' },
  },
  {
    id: 'nl-d27',
    text: 'De reis naar Spanje duurde lang, maar het uitzicht was prachtig.',
    level: 2,
    focus: ['ei-ij', 'past'],
    note: { en: "reis with ei. duren: r is not in 't kofschip, so duurde.", local: "reis met ei. duren: de r zit niet in 't kofschip, dus duurde." },
  },
  {
    id: 'nl-d28',
    text: 'Hoeveel weegt dat pakket? Het lijkt me erg zwaar.',
    level: 2,
    focus: ['ei-ij', 'de-het'],
    note: { en: 'het pakket, so dat. lijkt with ij.', local: 'het pakket, dus dat. lijkt met ij.' },
  },
  {
    id: 'nl-d29',
    text: 'Wordt het rapport dat de directeur vorige week heeft geschreven, morgen eindelijk besproken?',
    level: 3,
    focus: ['dt', 'de-het'],
    note: {
      en: 'Wordt het rapport: the subject is het rapport, so stem + t. het rapport, so dat.',
      local: 'Wordt het rapport: het onderwerp is het rapport, dus stam + t. het rapport, dus dat.',
    },
  },
  {
    id: 'nl-d30',
    text: 'Ik vind het jammer dat je je ideeën niet eerder met ons hebt gedeeld.',
    level: 3,
    focus: ['dt', 'trema', 'participle'],
    note: { en: 'ik vind: stem only. ideeën: trema. gedeeld: participle with d.', local: 'ik vind: alleen de stam. ideeën: trema. gedeeld: voltooid deelwoord met d.' },
  },
  {
    id: 'nl-d31',
    text: 'Nadat ze de vergadering had geleid, leidde ze ook nog een rondleiding door het gebouw.',
    level: 3,
    focus: ['past', 'ei-ij'],
    note: {
      en: 'had geleid: participle, no extra d. leidde: stem leid + de.',
      local: 'had geleid: voltooid deelwoord, geen extra d. leidde: stam leid + de.',
    },
  },
  {
    id: 'nl-d32',
    text: 'Het bedrijf heeft vorig jaar veel verlies geleden, dus wordt er nu streng bezuinigd.',
    level: 3,
    focus: ['ei-ij', 'dt'],
    note: {
      en: 'geleden comes from lijden but is spelled with e. wordt er: stem + t.',
      local: 'geleden komt van lijden, maar schrijf je met e. wordt er: stam + t.',
    },
  },
  {
    id: 'nl-d33',
    text: "Mijn schoonzus heeft gisteren haar nieuwe e-mailadres naar alle collega's gestuurd.",
    level: 3,
    focus: ['compound', 'apostrophe'],
    note: { en: 'e-mailadres: one word, with a hyphen after the e.', local: 'e-mailadres: één woord, met een streepje na de e.' },
  },
  {
    id: 'nl-d34',
    text: 'De coördinator wil weten of de reünie in het voorjaar of in het najaar wordt gehouden.',
    level: 3,
    focus: ['trema', 'dt'],
    note: { en: 'coördinator and reünie both have a trema. de reünie wordt: stem + t.', local: 'coördinator en reünie hebben allebei een trema. de reünie wordt: stam + t.' },
  },
  {
    id: 'nl-d35',
    text: 'Als je je fiets niet op slot zet, wordt hij vroeg of laat gestolen.',
    level: 3,
    focus: ['dt'],
    note: { en: 'wordt hij: hij keeps stem + t after the verb too.', local: 'wordt hij: ook achter het werkwoord krijgt hij stam + t.' },
  },
  {
    id: 'nl-d36',
    text: 'Het oude meubelstuk dat we op de rommelmarkt hebben gekocht, staat nu in de woonkamer.',
    level: 3,
    focus: ['de-het', 'compound'],
    note: { en: 'het meubelstuk, so dat. rommelmarkt and woonkamer are single words.', local: 'het meubelstuk, dus dat. rommelmarkt en woonkamer zijn één woord.' },
  },
  {
    id: 'nl-d37',
    text: 'Zij antwoordde pas na een week, omdat ze de vraag eerst niet had begrepen.',
    level: 3,
    focus: ['past'],
    note: { en: "antwoordde: stem antwoord + de, two d's.", local: "antwoordde: stam antwoord + de, twee d's." },
  },
  {
    id: 'nl-d38',
    text: "Hoewel de taxi's al klaarstonden, vertrokken de gasten pas na middernacht.",
    level: 3,
    focus: ['apostrophe', 'compound'],
    note: { en: "taxi's: a final i gets 's. klaarstonden is one word.", local: "taxi's: na een i aan het eind komt 's. klaarstonden is één woord." },
  },
  {
    id: 'nl-d39',
    text: 'Ik verwacht dat de prijzen van zonnepanelen volgend jaar opnieuw zullen dalen.',
    level: 3,
    focus: ['ei-ij', 'compound'],
    note: { en: 'prijzen with ij. zonnepanelen: linking -e-, no n.', local: 'prijzen met ij. zonnepanelen: tussenklank -e-, zonder n.' },
  },
  {
    id: 'nl-d40',
    text: 'Op het strand vonden we een zee-egel, twee zeesterren en een kapotte schelp.',
    level: 3,
    focus: ['compound', 'past'],
    note: { en: 'zee-egel gets a hyphen, or you would read eee. zeesterren is one word.', local: 'zee-egel krijgt een streepje, anders lees je eee. zeesterren is één woord.' },
  },
]

export const PAIRS_NL: MinimalPair[] = [
  {
    id: 'word-wordt',
    lang: 'nl',
    words: ['word', 'wordt'],
    note: {
      en: 'ik word, and word je/jij when je/jij follows the verb. Everyone else: wordt (jij wordt, hij wordt, wordt u).',
      local: 'ik word, en word je/jij als je/jij achter het werkwoord staat. Verder overal wordt (jij wordt, hij wordt, wordt u).',
    },
    sentences: [
      { text: 'Ik word morgen dertig.', word: 'word' },
      { text: 'Hij wordt morgen dertig.', word: 'wordt' },
      { text: 'Word jij ook zo moe van dit weer?', word: 'Word' },
      { text: 'Jij wordt steeds beter in tennis.', word: 'wordt' },
      { text: 'Wordt het morgen weer zo warm?', word: 'Wordt' },
      { text: 'Ik word een beetje zenuwachtig van die hond.', word: 'word' },
      { text: 'Wordt u al geholpen?', word: 'Wordt' },
      { text: 'Word je vaak gebeld door je baas?', word: 'Word' },
    ],
  },
  {
    id: 'vind-vindt',
    lang: 'nl',
    words: ['vind', 'vindt'],
    note: {
      en: 'ik vind, and vind je/jij when je/jij follows the verb. Everyone else: vindt.',
      local: 'ik vind, en vind je/jij als je/jij achter het werkwoord staat. Verder overal vindt.',
    },
    sentences: [
      { text: 'Ik vind dit boek erg spannend.', word: 'vind' },
      { text: 'Mijn moeder vindt dit boek erg spannend.', word: 'vindt' },
      { text: 'Vind jij het ook te warm hier?', word: 'Vind' },
      { text: 'Hij vindt zijn sleutels nooit terug.', word: 'vindt' },
      { text: 'Je vindt de handdoeken in de kast.', word: 'vindt' },
      { text: 'Vind je dat niet een beetje raar?', word: 'Vind' },
    ],
  },
  {
    id: 'gebeurd-gebeurt',
    lang: 'nl',
    words: ['gebeurd', 'gebeurt'],
    note: {
      en: 'With a form of hebben, zijn or worden: participle, gebeurd. Without one: present tense, gebeurt.',
      local: 'Staat er een vorm van hebben, zijn of worden bij: voltooid deelwoord, gebeurd. Zonder hulpwerkwoord: tegenwoordige tijd, gebeurt.',
    },
    sentences: [
      { text: 'Wat is er gisteren gebeurd?', word: 'gebeurd' },
      { text: 'Wat gebeurt er als ik op deze knop druk?', word: 'gebeurt' },
      { text: 'Dat gebeurt ons niet nog een keer.', word: 'gebeurt' },
      { text: 'Het ongeluk is vlak bij school gebeurd.', word: 'gebeurd' },
      { text: 'Er gebeurt hier nooit iets.', word: 'gebeurt' },
      { text: 'Is het echt zo gebeurd?', word: 'gebeurd' },
    ],
  },
  {
    id: 'verbeterd-verbetert',
    lang: 'nl',
    words: ['verbeterd', 'verbetert'],
    note: {
      en: 'heeft/is verbeterd: participle with d. Without an auxiliary: verbetert, stem + t.',
      local: 'heeft/is verbeterd: voltooid deelwoord met d. Zonder hulpwerkwoord: verbetert, stam + t.',
    },
    sentences: [
      { text: 'De juf heeft mijn toets al verbeterd.', word: 'verbeterd' },
      { text: 'De juf verbetert de toetsen in het weekend.', word: 'verbetert' },
      { text: 'Mijn Nederlands is flink verbeterd.', word: 'verbeterd' },
      { text: 'Hij verbetert elke fout die hij ziet.', word: 'verbetert' },
      { text: 'Het weer verbetert vanaf woensdag.', word: 'verbetert' },
    ],
  },
  {
    id: 'betekend-betekent',
    lang: 'nl',
    words: ['betekend', 'betekent'],
    note: {
      en: 'heeft betekend: participle with d. Without an auxiliary: betekent, stem + t.',
      local: 'heeft betekend: voltooid deelwoord met d. Zonder hulpwerkwoord: betekent, stam + t.',
    },
    sentences: [
      { text: 'Wat betekent dit woord?', word: 'betekent' },
      { text: 'Dat heeft veel voor me betekend.', word: 'betekend' },
      { text: 'Dit betekent dat we later beginnen.', word: 'betekent' },
      { text: 'Wat heeft die opmerking eigenlijk betekend?', word: 'betekend' },
    ],
  },
  {
    id: 'beantwoord-beantwoordt',
    lang: 'nl',
    words: ['beantwoord', 'beantwoordt'],
    note: {
      en: 'The stem is beantwoord. hij + stem + t = beantwoordt. The participle gets no ge- and stays beantwoord.',
      local: 'De stam is beantwoord. hij + stam + t = beantwoordt. Het voltooid deelwoord krijgt geen ge- en blijft beantwoord.',
    },
    sentences: [
      { text: 'Zij beantwoordt elke mail binnen een uur.', word: 'beantwoordt' },
      { text: 'Heb jij zijn vraag al beantwoord?', word: 'beantwoord' },
      { text: 'Hij beantwoordt de telefoon nooit.', word: 'beantwoordt' },
      { text: 'Alle vragen zijn beantwoord.', word: 'beantwoord' },
    ],
  },
  {
    id: 'leidt-lijdt',
    lang: 'nl',
    words: ['leidt', 'lijdt'],
    note: {
      en: 'leiden (ei) = lead or run something. lijden (ij) = suffer. Both: stem + t.',
      local: 'leiden (ei) = de leiding hebben of de weg wijzen. lijden (ij) = pijn of verdriet hebben. Allebei stam + t.',
    },
    sentences: [
      { text: 'Mijn tante leidt een klein hotel aan zee.', word: 'leidt' },
      { text: 'Mijn tante lijdt aan hooikoorts.', word: 'lijdt' },
      { text: 'Deze weg leidt naar het station.', word: 'leidt' },
      { text: 'De patiënt lijdt veel pijn.', word: 'lijdt' },
    ],
  },
  {
    id: 'jou-jouw',
    lang: 'nl',
    words: ['jou', 'jouw'],
    note: {
      en: 'jouw belongs to you (jouw fiets). jou is you as an object (voor jou).',
      local: 'jouw is bezittelijk (jouw fiets). jou is een voorwerp (voor jou).',
    },
    sentences: [
      { text: 'Ik heb een cadeautje voor jou.', word: 'jou' },
      { text: 'Is dit jouw fiets?', word: 'jouw' },
      { text: 'Ik denk vaak aan jou.', word: 'jou' },
      { text: 'Jouw zus heeft net gebeld.', word: 'Jouw' },
    ],
  },
  {
    id: 'hart-hard',
    lang: 'nl',
    words: ['hart', 'hard'],
    note: {
      en: 'hart is the organ (harten), hard means tough or fast (harder). Make the word longer to hear the d or t.',
      local: 'hart is het orgaan (harten), hard betekent stevig of snel (harder). Maak het woord langer, dan hoor je de d of t.',
    },
    sentences: [
      { text: 'Mijn hart klopt heel snel.', word: 'hart' },
      { text: 'Ze werkt heel hard.', word: 'hard' },
      { text: 'Hij heeft een goed hart.', word: 'hart' },
      { text: 'Het regent hard vandaag.', word: 'hard' },
    ],
  },
]
