import { definePack } from '../build'

// Dutch pronouns and comparisons: hun/hen/zij, jou/jouw, me/mijn, als/dan.

export const hunHen = definePack({
  id: 'nl.hun-hen',
  lang: 'nl',
  title: 'zij / hun / hen',
  blurb: 'Subject, possessive and object forms. Hun is never the subject.',
  rule: {
    en: '*Zij* (or *ze*) is the subject: *zij hebben*. *Hun* is never the subject, so *hun hebben* is always wrong. Use *hun* for something they own (*hun huis*) and for someone receiving something without a preposition (*ik geef hun een boek*). Use *hen* as the direct object (*ik zie hen*) and after a preposition (*met hen*, *voor hen*).\n\nThe trick: ask what the word does. Doing the action: *zij*. Owning something: *hun*. Receiving something, no preposition: *hun*. Undergoing the action, or after a preposition: *hen*. In speech *ze* also works for objects, and the gym accepts it there.',
    local: '*Zij* (of *ze*) is het onderwerp: *zij hebben*. *Hun* is nooit onderwerp, dus *hun hebben* is altijd fout. *Hun* gebruik je voor bezit (*hun huis*) en voor iemand die iets krijgt, zonder voorzetsel (*ik geef hun een boek*). *Hen* gebruik je als lijdend voorwerp (*ik zie hen*) en na een voorzetsel (*met hen*, *voor hen*).\n\nDe truc: vraag je af wat het woord doet. Doet het iets: *zij*. Bezit het iets: *hun*. Krijgt het iets, zonder voorzetsel: *hun*. Ondergaat het iets, of staat er een voorzetsel voor: *hen*. In spreektaal kan *ze* ook als voorwerp, en de gym rekent dat daar goed.',
  },
  hints: {
    subj: { en: 'The subject (who does it?) is zij or ze. Hun is never the subject.', local: 'Het onderwerp (wie doet het?) is zij of ze. Hun is nooit onderwerp.' },
    poss: { en: 'Something that belongs to them: hun. Hun huis.', local: 'Iets wat van hen is: hun. Hun huis.' },
    io: { en: 'Receiving something, without a preposition: hun. Ik geef hun een boek.', local: 'Iets krijgen, zonder voorzetsel: hun. Ik geef hun een boek.' },
    prep: { en: 'After a preposition (met, voor, bij, aan): hen.', local: 'Na een voorzetsel (met, voor, bij, aan): hen.' },
    do: { en: 'The direct object (who do you see, call, help?): hen.', local: 'Het lijdend voorwerp (wie zie, bel of help je?): hen.' },
  },
  items: [
    ['{{Zij/ze|Hun|Hen}} hebben een nieuwe auto gekocht.', 'subj'],
    ['Dat is {{hun|hen|zij}} huis.', 'poss'],
    ['Ik heb {{hen/ze|hun|zij}} gisteren nog gezien.', 'do'],
    ['Ik ga morgen met {{hen|hun|zij}} naar de film.', 'prep'],
    ['Ik heb {{hun/ze|hen|zij}} een kaartje gestuurd.', 'io'],
    ['{{Zij/ze|Hun}} wonen al tien jaar in Leiden.', 'subj'],
    ['{{Hun|Hen|Zij}} kinderen zitten op dezelfde school.', 'poss'],
    ['Wij wachten op {{hen|hun}}.', 'prep'],
    ['De juf gaf {{hun/ze|hen}} een compliment.', 'io'],
    ['Waarom bellen {{zij/ze|hun}} niet gewoon?', 'subj'],
    ['Morgen komen {{zij/ze|hun}} op bezoek.', 'subj'],
    ['Dit cadeau is voor {{hen|hun}}.', 'prep'],
    ['Ik heb {{hen/ze|hun}} uitgenodigd voor mijn verjaardag.', 'do'],
    ['{{Hun|Hen}} hond blaft de hele dag.', 'poss'],
    ['Kun je {{hun/ze|hen}} de weg wijzen?', 'io'],
    ['Zonder {{hen|hun}} was het nooit gelukt.', 'prep'],
    ['{{Zij/ze|Hun}} zijn de beste buren die we ooit hebben gehad.', 'subj'],
    ['We hebben {{hen/ze|hun}} op het station opgehaald.', 'do'],
    ['Heb je {{hun/ze|hen}} al verteld dat je gaat verhuizen?', 'io'],
    ['Ik weet niet waarom {{zij/ze|hun}} zo laat zijn.', 'subj'],
    ['Ze zijn {{hun|hen}} sleutels kwijt.', 'poss'],
    ['Ik heb een brief aan {{hen|hun}} geschreven.', 'prep'],
    ['De leraar heeft {{hun/ze|hen}} een extra opdracht gegeven.', 'io'],
    ['{{Zij/ze|Hun}} vinden het niet erg.', 'subj'],
    ['Ik ken {{hen/ze|hun}} al sinds de basisschool.', 'do'],
    ['Bij {{hen|hun}} thuis is het altijd gezellig.', 'prep'],
    ['We hebben {{hun/ze|hen}} veel succes gewenst.', 'io'],
    ['{{Hun|Hen}} ouders komen uit Turkije.', 'poss'],
    ['{{Zij/ze|Hun}} moeten nog even wachten.', 'subj'],
    ['Wie heeft {{hen/ze|hun}} gebeld?', 'do'],
    ['Ik werk graag met {{hen|hun}} samen.', 'prep'],
    ['Kun je {{hen/ze|hun}} even helpen met tillen?', 'do'],
    ['Ik heb {{hun/ze|hen}} beloofd dat ik op tijd kom.', 'io'],
    ['Vraag het maar aan {{hen|hun}}.', 'prep'],
    ['{{Zij/ze|Hun}} spreken allebei vloeiend Arabisch.', 'subj'],
    ['De buren gaan met {{hun|hen}} hele familie op vakantie.', 'poss'],
    ['Ik heb {{hen/ze|hun}} nooit goed begrepen.', 'do'],
    ['Wat hebben {{zij/ze|hun}} gezegd?', 'subj'],
    ['Ik zal {{hun/ze|hen}} straks een berichtje sturen.', 'io'],
    ['Achter {{hen|hun}} zat een man die de hele tijd hoestte.', 'prep'],
    ['Gisteren hebben {{zij/ze|hun}} hun examen gehaald.', 'subj'],
  ],
})

export const alsDan = definePack({
  id: 'nl.als-dan',
  lang: 'nl',
  title: 'als / dan',
  blurb: 'Comparisons: groter dan, even groot als. And als that means if.',
  rule: {
    en: 'Comparing things that differ? Use *dan* after a comparative (*groter dan*, *beter dan*, *meer dan*) and after *anders* and *ander(e)*. Comparing things that are the same? Use *als*: *even groot als*, *zo groot als*, *net als*, *hetzelfde als*.\n\nThe trick: a word ending in -er (*groter*, *ouder*, *liever*) or *meer* and *minder* calls for *dan*. Careful: *als* also means if or when, as in *Het is beter als je nu gaat.*',
    local: 'Vergelijk je dingen die verschillen? Dan gebruik je *dan* na een vergrotende trap (*groter dan*, *beter dan*, *meer dan*) en na *anders* en *ander(e)*. Zijn ze gelijk? Dan *als*: *even groot als*, *zo groot als*, *net als*, *hetzelfde als*.\n\nDe truc: een woord op -er (*groter*, *ouder*, *liever*) of *meer* en *minder* vraagt om *dan*. Let op: *als* betekent ook wanneer of indien, zoals in *Het is beter als je nu gaat.*',
  },
  hints: {
    cmp: { en: 'A comparative (groter, ouder, meer): dan.', local: 'Een vergrotende trap (groter, ouder, meer): dan.' },
    anders: { en: 'After anders or ander(e): dan.', local: 'Na anders of ander(e): dan.' },
    eq: { en: 'The same (even, zo, net, hetzelfde): als.', local: 'Gelijk (even, zo, net, hetzelfde): als.' },
    if: { en: 'Here als means if or when. Not a comparison.', local: 'Hier betekent als wanneer of indien. Geen vergelijking.' },
    role: { en: 'als meaning in the role of: ze werkt als kok.', local: 'als in de betekenis van in de rol van: ze werkt als kok.' },
  },
  items: [
    ['Mijn fiets is sneller {{dan|als}} de jouwe.', 'cmp'],
    ['Mijn fiets is even snel {{als|dan}} de jouwe.', 'eq'],
    ['Hij is twee jaar ouder {{dan|als}} ik.', 'cmp'],
    ['Zij is net zo oud {{als|dan}} ik.', 'eq'],
    ['Ik drink liever thee {{dan|als}} koffie.', 'cmp'],
    ['Het was veel drukker {{dan|als}} vorig jaar.', 'cmp'],
    ['Dit boek is minder spannend {{dan|als}} het vorige.', 'cmp'],
    ['Hij verdient meer {{dan|als}} zijn baas.', 'cmp'],
    ['Mijn zus is heel anders {{dan|als}} ik.', 'anders'],
    ['Het is vandaag zo koud {{als|dan}} in januari.', 'eq'],
    ['Ze zingt net {{als|dan}} haar moeder.', 'eq'],
    ['Ik heb hetzelfde shirt {{als|dan}} jij.', 'eq'],
    ['Het weer is beter {{dan|als}} verwacht.', 'cmp'],
    ['Hij werkt {{als|dan}} kok in een hotel.', 'role'],
    ['Ik doe het liever vandaag {{dan|als}} morgen.', 'cmp'],
    ['Het is beter {{als|dan}} je nu vertrekt.', 'if'],
    ['Bel me {{als|dan}} je thuis bent.', 'if'],
    ['Amsterdam is groter {{dan|als}} Utrecht.', 'cmp'],
    ['Utrecht is niet zo groot {{als|dan}} Amsterdam.', 'eq'],
    ['Niemand kookt zo lekker {{als|dan}} mijn oma.', 'eq'],
    ['Dat kost meer {{dan|als}} honderd euro.', 'cmp'],
    ['Het duurde langer {{dan|als}} ik dacht.', 'cmp'],
    ['Ze is even lang {{als|dan}} haar broer.', 'eq'],
    ['Hij is slimmer {{dan|als}} hij lijkt.', 'cmp'],
    ['Ik heb nog nooit zo hard gelachen {{als|dan}} vandaag.', 'eq'],
    ['Dit is een andere jas {{dan|als}} gisteren.', 'anders'],
    ['Ik ben niet meer zo snel {{als|dan}} vroeger.', 'eq'],
    ['Zijn auto is duurder {{dan|als}} ons huis.', 'cmp'],
    ['Het is hier warmer {{dan|als}} in Spanje.', 'cmp'],
    ['Ze spreekt Nederlands {{als|dan}} een moedertaalspreker.', 'eq'],
    ['Het werd later {{dan|als}} gepland.', 'cmp'],
    ['Mijn telefoon is ouder {{dan|als}} die van mijn moeder.', 'cmp'],
    ['Ik vind dit net zo lekker {{als|dan}} vroeger.', 'eq'],
    ['Er waren minder mensen {{dan|als}} vorige week.', 'cmp'],
    ['{{Als|Dan}} het regent, blijven we binnen.', 'if'],
    ['Ik heb niets anders {{dan|als}} dit.', 'anders'],
    ['Mijn kamer is even groot {{als|dan}} de jouwe.', 'eq'],
    ['Hij is veel aardiger {{dan|als}} ik had verwacht.', 'cmp'],
    ['Jij bent eerder klaar {{dan|als}} ik.', 'cmp'],
    ['Het is hier net zo duur {{als|dan}} in Parijs.', 'eq'],
    ['Zij werkt {{als|dan}} verpleegkundige in het ziekenhuis.', 'role'],
  ],
})

export const jouJouw = definePack({
  id: 'nl.jou-jouw',
  lang: 'nl',
  title: 'jou / jouw',
  blurb: 'Possessive before a noun, object form everywhere else.',
  rule: {
    en: '*jouw* is possessive and comes before a noun: *jouw fiets*. *jou* is the object form: *ik zie jou*, *voor jou*, *van jou*. Nothing of yours after it? Then it is *jou*.\n\nThe trick: swap in *mijn* or *mij*. *Mijn fiets*, so *jouw fiets*. *Voor mij*, so *voor jou*.',
    local: '*jouw* is bezittelijk en staat voor een zelfstandig naamwoord: *jouw fiets*. *jou* is de voorwerpsvorm: *ik zie jou*, *voor jou*, *van jou*. Volgt er niets wat van jou is? Dan is het *jou*.\n\nDe truc: vervang het door *mijn* of *mij*. *Mijn fiets*, dus *jouw fiets*. *Voor mij*, dus *voor jou*.',
  },
  hints: {
    poss: { en: 'Something of yours follows: jouw. Test: mijn fiets, so jouw fiets.', local: 'Er volgt iets wat van jou is: jouw. Test: mijn fiets, dus jouw fiets.' },
    obj: { en: 'No noun of yours after it: jou. Test: voor mij, so voor jou.', local: 'Er volgt geen zelfstandig naamwoord dat van jou is: jou. Test: voor mij, dus voor jou.' },
    vanjou: { en: 'Van jou means yours, but no noun follows: jou.', local: 'Van jou betekent dat het van jou is, maar er volgt geen zelfstandig naamwoord: jou.' },
    als: { en: 'Fixed phrase: als ik jou was.', local: 'Vaste uitdrukking: als ik jou was.' },
  },
  items: [
    ['Is dit {{jouw|jou}} fiets?', 'poss'],
    ['Dit cadeau is voor {{jou|jouw}}.', 'obj'],
    ['Is deze fiets van {{jou|jouw}}?', 'vanjou'],
    ['Ik heb {{jou|jouw}} gisteren nog gezien.', 'obj'],
    ['{{Jouw|Jou}} moeder belde net.', 'poss'],
    ['Ik denk vaak aan {{jou|jouw}}.', 'obj'],
    ['Als ik {{jou|jouw}} was, zou ik het doen.', 'als'],
    ['Wat is {{jouw|jou}} lievelingseten?', 'poss'],
    ['Ik ga met {{jou|jouw}} mee.', 'obj'],
    ['Ligt {{jouw|jou}} telefoon nog in de auto?', 'poss'],
    ['Ik geef {{jou|jouw}} de sleutel.', 'obj'],
    ['Is die jas van {{jou|jouw}} of van je broer?', 'vanjou'],
    ['{{Jouw|Jou}} Nederlands is echt beter geworden.', 'poss'],
    ['Ik heb een vraag voor {{jou|jouw}}.', 'obj'],
    ['Ik hou van {{jou|jouw}}.', 'obj'],
    ['Is dat {{jouw|jou}} hond die daar blaft?', 'poss'],
    ['Zonder {{jou|jouw}} is het saai.', 'obj'],
    ['Mag ik {{jouw|jou}} pen even lenen?', 'poss'],
    ['Ik wacht op {{jou|jouw}} bij de ingang.', 'obj'],
    ['Wie heeft {{jou|jouw}} dat verteld?', 'obj'],
    ['Ik vind {{jouw|jou}} plan heel goed.', 'poss'],
    ['Ik bel {{jou|jouw}} morgen.', 'obj'],
    ['De keuze is aan {{jou|jouw}}.', 'obj'],
    ['{{Jouw|Jou}} kamer is groter dan de mijne.', 'poss'],
    ['Ik heb {{jou|jouw}} nodig.', 'obj'],
    ['Hoe gaat het met {{jouw|jou}} studie?', 'poss'],
    ['Ik schrijf {{jou|jouw}} een lange brief.', 'obj'],
    ['Is {{jouw|jou}} huiswerk al af?', 'poss'],
    ['Ik ben trots op {{jou|jouw}}.', 'obj'],
    ['Wat vinden {{jouw|jou}} ouders ervan?', 'poss'],
    ['Ik kom na het werk naar {{jou|jouw}} toe.', 'obj'],
    ['Ik heb {{jouw|jou}} nummer niet meer.', 'poss'],
    ['Het ligt niet aan {{jou|jouw}}.', 'obj'],
    ['Ik zie {{jou|jouw}} straks.', 'obj'],
    ['Is {{jouw|jou}} trein ook vertraagd?', 'poss'],
    ['Dat is lief van {{jou|jouw}}.', 'obj'],
    ['Ik heb {{jou|jouw}} een berichtje gestuurd.', 'obj'],
    ['Hoe heet {{jouw|jou}} zus?', 'poss'],
    ['{{Jouw|Jou}} schoenen staan in de gang.', 'poss'],
    ['Na {{jou|jouw}}.', 'obj'],
    ['Is die tas van {{jou|jouw}}?', 'vanjou'],
  ],
})

export const meMijn = definePack({
  id: 'nl.me-mijn',
  lang: 'nl',
  title: 'me / mijn',
  blurb: "Me is never possessive. Mijn and m'n are.",
  rule: {
    en: "*mijn* (short: *m'n*) is possessive: *mijn broer*, *m'n fiets*. *me* is never possessive. It is the object form of *ik*, like *mij* without stress: *hij belt me*, *ik verveel me*. So *me broer* is always wrong, even though you hear it all the time.\n\nThe trick: English *my* is *mijn*, English *me* and *myself* are *me*. Or: if you could say *m'n*, write *mijn*.",
    local: "*mijn* (kort: *m'n*) is bezittelijk: *mijn broer*, *m'n fiets*. *me* is nooit bezittelijk: het is de voorwerpsvorm van *ik*, net als *mij* maar zonder nadruk: *hij belt me*, *ik verveel me*. *Me broer* is dus altijd fout, ook al hoor je het vaak.\n\nDe truc: kun je er *m'n* van maken? Dan schrijf je *mijn*. Anders is het *me*.",
  },
  hints: {
    poss: { en: "Something of mine follows: mijn, or m'n. Never me.", local: "Er volgt iets wat van mij is: mijn, of m'n. Nooit me." },
    obj: { en: 'Me as the object (English me): me or mij.', local: 'Ik als voorwerp (Engels me): me of mij.' },
    refl: { en: 'A reflexive verb (ik ... me): me. Ik verveel me.', local: 'Een wederkerend werkwoord (ik ... me): me. Ik verveel me.' },
    prep: { en: 'After a preposition: mij, or me without stress.', local: 'Na een voorzetsel: mij, of me zonder nadruk.' },
  },
  items: [
    ["{{Mijn/m'n|Me}} broer woont in Leiden.", 'poss'],
    ['Kun je {{me/mij|mijn}} even helpen?', 'obj'],
    ["Ik ben {{mijn/m'n|me}} sleutels kwijt.", 'poss'],
    ['Hij heeft {{me/mij|mijn}} gisteren gebeld.', 'obj'],
    ['Ik verveel {{me/mij|mijn}} hier dood.', 'refl'],
    ["Waar is {{mijn/m'n|me}} telefoon?", 'poss'],
    ['Geef {{me/mij|mijn}} die pen eens.', 'obj'],
    ["{{Mijn/m'n|Me}} moeder komt uit Marokko.", 'poss'],
    ['Ik heb {{me/mij|mijn}} vergist.', 'refl'],
    ['Ze heeft {{me/mij|mijn}} een mooi boek gegeven.', 'obj'],
    ["Ik ga met {{mijn/m'n|me}} vriendin naar de film.", 'poss'],
    ['Wil je {{me/mij|mijn}} morgen even bellen?', 'obj'],
    ['Ik voel {{me/mij|mijn}} niet zo lekker.', 'refl'],
    ["Heb je {{mijn/m'n|me}} tas gezien?", 'poss'],
    ['Hij vroeg {{me/mij|mijn}} om te helpen.', 'obj'],
    ["{{Mijn/m'n|Me}} fiets is gestolen.", 'poss'],
    ['Ik schaam {{me/mij|mijn}} een beetje.', 'refl'],
    ["Kom je naar {{mijn/m'n|me}} verjaardag?", 'poss'],
    ['Laat {{me/mij|mijn}} even nadenken.', 'obj'],
    ["Ik heb {{mijn/m'n|me}} huiswerk vergeten.", 'poss'],
    ['Ze lachte {{me/mij|mijn}} uit.', 'obj'],
    ['Ik herinner {{me/mij|mijn}} die dag nog goed.', 'refl'],
    ["Bij {{mijn/m'n|me}} oma thuis ruikt het altijd naar koekjes.", 'poss'],
    ['Dat zei hij tegen {{mij/me|mijn}}.', 'prep'],
    ["Ik was {{mijn/m'n|me}} handen.", 'poss'],
    ['Hij keek {{me/mij|mijn}} recht aan.', 'obj'],
    ["{{Mijn/m'n|Me}} buurman heeft een nieuwe auto.", 'poss'],
    ['Ik moet {{me/mij|mijn}} haasten.', 'refl'],
    ["Mag ik {{mijn/m'n|me}} jas hier ophangen?", 'poss'],
    ['Ze heeft {{me/mij|mijn}} niet herkend.', 'obj'],
    ["Ik heb {{mijn/m'n|me}} best gedaan.", 'poss'],
    ['Ik interesseer {{me/mij|mijn}} voor geschiedenis.', 'refl'],
    ["Zonder {{mijn/m'n|me}} bril zie ik niets.", 'poss'],
    ['Wil je {{me/mij|mijn}} het zout even aangeven?', 'obj'],
    ["{{Mijn/m'n|Me}} Nederlands wordt steeds beter.", 'poss'],
    ['Hij heeft {{me/mij|mijn}} uitgenodigd.', 'obj'],
    ['Ik verheug {{me/mij|mijn}} op de vakantie.', 'refl'],
    ["Dat is {{mijn/m'n|me}} plekje.", 'poss'],
    ['Ze belde {{me/mij|mijn}} midden in de nacht.', 'obj'],
    ["Ik heb in {{mijn/m'n|me}} vinger gesneden.", 'poss'],
    ['Kom maar naast {{mij/me|mijn}} zitten.', 'prep'],
  ],
})
