import { definePack } from '../build'

// Dutch spelling by sight: ei/ij, au/ou, trema and apostrophe, compounds.

export const eiIj = definePack({
  id: 'nl.ei-ij',
  lang: 'nl',
  title: 'ei / ij',
  blurb: 'Same sound, two spellings. Minimal pairs and words to know by sight.',
  rule: {
    en: '*ei* and *ij* sound exactly the same, so no rule tells them apart. Learn them as pairs with a meaning: *leiden* (to lead) and *lijden* (to suffer), *peil* (level) and *pijl* (arrow), *zei* (said) and *zij* (she).\n\nA rough trick: if the English word has the sound of the i in *mine* or *time*, Dutch usually writes ij: *mijn*, *tijd*, *wijn* (wine), *ijs* (ice), *vijf* (five). A hint, not a law.',
    local: '*ei* en *ij* klinken precies hetzelfde, dus geen regel helpt je kiezen. Leer ze als paren met een betekenis: *leiden* (de leiding hebben) en *lijden* (pijn hebben), *peil* (niveau) en *pijl* (om mee te schieten), *zei* (van zeggen) en *zij*.\n\nEen ruwe truc: klinkt het Engelse woord als de i in *mine* of *time*? Dan schrijf je in het Nederlands vaak ij: *mijn*, *tijd*, *wijn* (wine), *ijs* (ice), *vijf* (five). Een hulpje, geen wet.',
  },
  hints: {
    zei: { en: 'zei is the past tense of zeggen: hij zei.', local: 'zei is de verleden tijd van zeggen: hij zei.' },
    zij: { en: 'zij is the pronoun: zij komt. zei comes from zeggen.', local: 'zij is het persoonlijk voornaamwoord: zij komt. zei komt van zeggen.' },
    lijden: { en: 'lijden: to suffer. Lijden aan een ziekte.', local: 'lijden: pijn of verdriet hebben. Lijden aan een ziekte.' },
    leiden: { en: 'leiden: to lead, or to lead somewhere. De weg leidt naar zee.', local: 'leiden: de leiding hebben, of ergens heen gaan. De weg leidt naar zee.' },
    peil: { en: 'het peil: the level. De pijl: an arrow.', local: 'het peil: de hoogte of het niveau. De pijl: om mee te schieten.' },
    pijl: { en: 'de pijl: an arrow, also on signs. Het peil: a level.', local: 'de pijl: om mee te schieten, of op een bord. Het peil: het niveau.' },
    steil: { en: 'steil: steep. De stijl: a style.', local: 'steil: heel schuin omhoog. De stijl: de manier waarop.' },
    stijl: { en: 'de stijl: style. Steil: steep.', local: 'de stijl: de manier waarop. Steil: heel schuin omhoog.' },
    reis: { en: 'de reis: the trip. Reizen, ik reis, hij reist.', local: 'de reis: de tocht. Reizen, ik reis, hij reist.' },
    rijst: { en: 'de rijst: rice. Hij reist: he travels.', local: 'de rijst: wat je eet. Hij reist: van reizen.' },
    eis: { en: 'de eis: a demand. Het ijs: ice.', local: 'de eis: wat je vraagt of wilt. Het ijs: bevroren water.' },
    ijs: { en: 'het ijs, het ijsje: ice, ice cream. De eis: a demand.', local: 'het ijs, het ijsje: bevroren water of iets lekkers. De eis: wat je vraagt.' },
    wei: { en: 'de wei: a meadow. Wij: we.', local: 'de wei: een grasveld voor koeien. Wij: wij samen.' },
    wij: { en: 'wij: we. De wei: a meadow.', local: 'wij: wij samen. De wei: een grasveld.' },
    mei: { en: 'mei: the month of May. Mij: me.', local: 'mei: de maand. Mij: ik als voorwerp.' },
    mij: { en: 'mij: me. Mei is the month.', local: 'mij: ik als voorwerp. Mei is de maand.' },
    bereiden: { en: 'bereiden: to prepare. Berijden: to ride (a horse).', local: 'bereiden: klaarmaken. Berijden: rijden op een paard.' },
    reizen: { en: 'reizen: to travel. Rijzen: to rise, like dough.', local: 'reizen: op reis gaan. Rijzen: omhoogkomen, zoals deeg.' },
    rijzen: { en: 'rijzen: to rise, like dough. Reizen: to travel.', local: 'rijzen: omhoogkomen, zoals deeg. Reizen: op reis gaan.' },
    ijen: { en: 'English has the i of time here (wine, five, price, wise): Dutch writes ij.', local: 'Het Engels heeft hier de i van time (wine, five, price, wise): in het Nederlands schrijf je ij.' },
    ij: { en: 'No rule here: this word is written with ij. Learn how it looks.', local: 'Geen regel: dit woord schrijf je met ij. Onthoud hoe het eruitziet.' },
    ei: { en: 'No rule here: this word is written with ei. Learn how it looks.', local: 'Geen regel: dit woord schrijf je met ei. Onthoud hoe het eruitziet.' },
  },
  items: [
    ['Hij {{zei|zij}} dat hij later zou komen.', 'zei'],
    ['{{Zij|Zei}} komt morgen ook.', 'zij'],
    ['"Ik ben moe," {{zei|zij}} mijn moeder.', 'zei'],
    ['Wat {{zei|zij}} je?', 'zei'],
    ['Mijn oma {{lijdt|leidt}} aan suikerziekte.', 'lijden'],
    ['Mijn tante {{leidt|lijdt}} een groot bedrijf.', 'leiden'],
    ['Deze weg {{leidt|lijdt}} naar het dorp.', 'leiden'],
    ['Hij {{lijdt|leidt}} erg onder de hitte.', 'lijden'],
    ['Het {{peil|pijl}} van de rivier stijgt.', 'peil'],
    ['Volg de {{pijl|peil}} naar de uitgang.', 'pijl'],
    ['De trap naar de zolder is erg {{steil|stijl}}.', 'steil'],
    ['Ik hou van haar {{stijl|steil}} van schrijven.', 'stijl'],
    ['We maken een {{reis|rijs}} door Japan.', 'reis'],
    ['Ik eet graag {{rijst|reist}} met kip.', 'rijst'],
    ['Hij {{reist|rijst}} elke week naar Brussel.', 'reis'],
    ['De vakbond heeft maar één {{eis|ijs}}: meer loon.', 'eis'],
    ['Wil je een {{ijsje|eisje}}?', 'ijs'],
    ['De koeien staan in de {{wei|wij}}.', 'wei'],
    ['{{Wij|Wei}} gaan morgen naar het strand.', 'wij'],
    ['In {{mei|mij}} is het vaak al warm.', 'mei'],
    ['Geef {{mij|mei}} maar een kop thee.', 'mij'],
    ['Ze {{bereidt|berijdt}} het eten voor tien gasten.', 'bereiden'],
    ['We {{reizen|rijzen}} met de nachttrein naar Wenen.', 'reizen'],
    ['Het deeg moet een uur {{rijzen|reizen}}.', 'rijzen'],
    ['Hij is erg {{blij|blei}} met zijn cadeau.', 'ij'],
    ['De {{trein|trijn}} heeft tien minuten vertraging.', 'ei'],
    ['Het is al laat, ik heb geen {{tijd|teid}} meer.', 'ijen'],
    ['Mijn broertje is nog {{klein|klijn}}.', 'ei'],
    ['Ik heb {{vijf|veif}} zussen.', 'ijen'],
    ['Ik drink geen {{wijn|wein}}.', 'ijen'],
    ['We {{blijven|bleiven}} vannacht bij oma slapen.', 'ij'],
    ['Ik moet nog een brief {{schrijven|schreiven}}.', 'ij'],
    ['Het {{meisje|mijsje}} speelt viool.', 'ei'],
    ['Dat is een {{feit|fijt}}.', 'ei'],
    ['Hij woont in een nieuwe {{wijk|weik}}.', 'ij'],
    ['We fietsten over de {{dijk|deik}}.', 'ij'],
    ['Ik eet elke ochtend een gekookt {{ei|ij}}.', 'ei'],
    ['De {{prijs|preis}} van benzine stijgt weer.', 'ijen'],
    ['Het {{ijzer|eizer}} is gaan roesten.', 'ij'],
    ['Kom je {{bij|bei}} ons eten?', 'ij'],
    ['Ik ben {{vrij|vrei}} op vrijdag.', 'ij'],
    ['Hij is {{wijs|weis}} genoeg om niets te zeggen.', 'ijen'],
    ['De {{geit|gijt}} eet alles op.', 'ei'],
    ['De pijn is gelukkig snel {{voorbij|voorbei}}.', 'ij'],
    ['Het {{eiland|ijland}} ligt vlak voor de kust.', 'ei'],
  ],
})

export const auOu = definePack({
  id: 'nl.au-ou',
  lang: 'nl',
  title: 'au / ou',
  blurb: 'Same sound again. Two tricks and one short list cover most words.',
  rule: {
    en: '*au* and *ou* sound the same. Two tricks cover most words. Where English has an l, as in *old*, *cold*, *gold*, *salt* or *shoulder*, Dutch writes ou: *oud*, *koud*, *goud*, *zout*, *schouder*. That l turned into a u centuries ago. Loanwords keep their au: *auto*, *augustus*, *pauze*, *saus*.\n\nWords ending in -auw are a short list worth knowing by heart: *blauw*, *gauw*, *lauw*, *rauw*, *nauw*, *flauw*, *grauw*, *dauw*, *pauw*, *klauw*, *kauw*. Most other words with this sound and a w end in -ouw: *vrouw*, *touw*, *mouw*, *bouwen*.',
    local: '*au* en *ou* klinken hetzelfde. Twee trucs helpen bij de meeste woorden. Waar het Engels een l heeft, zoals in *old*, *cold*, *gold*, *salt* of *shoulder*, schrijf je ou: *oud*, *koud*, *goud*, *zout*, *schouder*. Die l is eeuwen geleden een u geworden. Leenwoorden houden hun au: *auto*, *augustus*, *pauze*, *saus*.\n\nWoorden op -auw vormen een kort rijtje om uit je hoofd te leren: *blauw*, *gauw*, *lauw*, *rauw*, *nauw*, *flauw*, *grauw*, *dauw*, *pauw*, *klauw*, *kauw*. De meeste andere woorden met deze klank en een w eindigen op -ouw: *vrouw*, *touw*, *mouw*, *bouwen*.',
  },
  hints: {
    ol: { en: 'English has an l here (old, cold, gold, salt, shoulder): Dutch writes ou.', local: 'Het Engels heeft hier een l (old, cold, gold, salt, shoulder): in het Nederlands schrijf je ou.' },
    auw: { en: 'On the -auw list: blauw, gauw, lauw, rauw, nauw, flauw, grauw, dauw, pauw, klauw, kauw.', local: 'Staat in het -auw-rijtje: blauw, gauw, lauw, rauw, nauw, flauw, grauw, dauw, pauw, klauw, kauw.' },
    ouw: { en: 'Not on the -auw list, so -ouw: vrouw, touw, mouw, bouwen, vouwen.', local: 'Staat niet in het -auw-rijtje, dus -ouw: vrouw, touw, mouw, bouwen, vouwen.' },
    loan: { en: 'A loanword, and loanwords keep au: auto, augustus, pauze, saus.', local: 'Een leenwoord, en die houden au: auto, augustus, pauze, saus.' },
    rauw: { en: 'rauw: raw, not cooked. De rouw: mourning.', local: 'rauw: niet gekookt. De rouw: verdriet om iemand die is overleden.' },
    rouw: { en: 'de rouw: mourning. Rauw: raw.', local: 'de rouw: verdriet om iemand die is overleden. Rauw: niet gekookt.' },
    kou: { en: 'de kou: the cold. De kauw: a jackdaw, a bird.', local: 'de kou: het koud zijn. De kauw: een vogel.' },
    kauw: { en: 'de kauw: a jackdaw, a small black bird. De kou: the cold.', local: 'de kauw: een kleine zwarte vogel. De kou: het koud zijn.' },
    ou: { en: 'No trick for this one: it is written with ou. Fout, jou, nou.', local: 'Geen truc voor dit woord: het schrijf je met ou. Fout, jou, nou.' },
  },
  items: [
    ['Het is vandaag erg {{koud|kaud}}.', 'ol'],
    ['Mijn opa is negentig jaar {{oud|aud}}.', 'ol'],
    ['Ze draagt een {{gouden|gauden}} ring.', 'ol'],
    ['Doe er nog wat {{zout|zaut}} bij.', 'ol'],
    ['De tafel is van {{hout|haut}}.', 'ol'],
    ['Mijn {{schouder|schauder}} doet pijn.', 'ol'],
    ['Hij {{houdt|haudt}} van warme chocolademelk.', 'ol'],
    ['Ze heeft een {{blauwe|blouwe}} jas.', 'auw'],
    ['Kom {{gauw|gouw}} terug.', 'auw'],
    ['Het vlees is nog {{rauw|rouw}}.', 'rauw'],
    ['De familie is in de {{rouw|rauw}}.', 'rouw'],
    ['Brr, wat een {{kou|kauw}} vandaag.', 'kou'],
    ['Er zit een {{kauw|kou}} op het dak.', 'kauw'],
    ['Mijn {{auto|outo}} staat bij de garage.', 'loan'],
    ['In {{augustus|ougustus}} gaan we op vakantie.', 'loan'],
    ['Ik neem patat met {{saus|sous}}.', 'loan'],
    ['Even {{pauze|pouze}}, ik heb honger.', 'loan'],
    ['Dat was mijn {{fout|faut}}.', 'ou'],
    ['Die {{vrouw|vrauw}} is mijn tante.', 'ouw'],
    ['Ze zijn vorig jaar {{getrouwd|getrauwd}}.', 'ouw'],
    ['Houd het {{touw|tauw}} goed vast.', 'ouw'],
    ['De {{mouwen|mauwen}} van mijn trui zijn te lang.', 'ouw'],
    ['Ik denk vaak aan {{jou|jau}}.', 'ou'],
    ['{{Nou|Nau}}, dat valt mee.', 'ou'],
    ['Het badwater is {{lauw|louw}}.', 'auw'],
    ['De {{pauw|pouw}} spreidt zijn veren.', 'auw'],
    ['Het is {{benauwd|benouwd}} in de trein.', 'auw'],
    ['De kat heeft scherpe {{klauwen|klouwen}}.', 'auw'],
    ['Ik voel me een beetje {{flauw|flouw}}.', 'auw'],
    ['Op het gras ligt nog {{dauw|douw}}.', 'auw'],
    ['Ik {{vouw|vauw}} de was op.', 'ouw'],
    ['Ze {{bouwen|bauwen}} een nieuwe brug.', 'ouw'],
    ['Het {{goud|gaud}} glinstert in de zon.', 'ol'],
    ['Gooi die {{oude|aude}} batterijen niet zomaar weg.', 'ol'],
    ['Hij {{kauwt|kouwt}} op een stuk kauwgom.', 'auw'],
    ['Mijn {{oudste|audste}} broer woont in Canada.', 'ol'],
    ['Het is een {{nauwe|nouwe}} straat.', 'auw'],
    ['De lucht is {{grauw|grouw}} vandaag.', 'auw'],
    ['Na het sporten gingen we naar de {{sauna|souna}}.', 'loan'],
    ['Zijn dat {{jouw|jauw}} schoenen?', 'ou'],
    ['Het {{koude|kaude}} water deed pijn aan mijn tanden.', 'ol'],
    ['Ik {{vertrouw|vertrauw}} hem niet.', 'ouw'],
  ],
})

export const tremaApostrof = definePack({
  id: 'nl.trema-apostrof',
  lang: 'nl',
  title: "ideeën / auto's",
  blurb: 'Trema on new syllables, apostrophe plurals, and when neither belongs.',
  rule: {
    en: "A trema marks where a new syllable starts with a vowel that you would otherwise read together with the one before: *ide-eën*, *Bel-gi-ë*, *ge-ïnteresseerd*. No risk of misreading, no trema: *financieel*, but *financiële*.\n\nA plural in -s gets an apostrophe after a long a, i, o, u or y, so the vowel stays long: *auto's*, *foto's*, *baby's*, and after abbreviations: *cd's*. After a consonant, a silent e or an accented vowel there is no apostrophe: *computers*, *garages*, *cafés*. In *'s avonds* the apostrophe stands for missing letters (des), so it comes before the s.",
    local: "Een trema laat zien dat er een nieuwe lettergreep begint met een klinker die je anders samen met de vorige zou lezen: *ide-eën*, *Bel-gi-ë*, *ge-ïnteresseerd*. Kun je het niet verkeerd lezen, dan geen trema: *financieel*, maar wel *financiële*.\n\nEen meervoud op -s krijgt een apostrof na een lange a, i, o, u of y, zodat de klinker lang blijft: *auto's*, *foto's*, *baby's*, en na afkortingen: *cd's*. Na een medeklinker, een stomme e of een klinker met accent komt er geen apostrof: *computers*, *garages*, *cafés*. In *'s avonds* staat de apostrof voor weggevallen letters (des), dus hij komt vóór de s.",
  },
  hints: {
    trema: { en: 'A new syllable starts with a vowel you could read together with the one before: trema.', local: 'Een nieuwe lettergreep begint met een klinker die je samen met de vorige zou lezen: trema.' },
    notrema: { en: 'financieel has nothing to misread, so no trema. Add an e and you need one: financiële.', local: 'In financieel kun je niets verkeerd lezen, dus geen trema. Komt er een e bij, dan wel: financiële.' },
    apos: { en: "Plural -s after a long a, i, o, u or y: apostrophe, so the vowel stays long. Auto's.", local: "Meervoud op -s na een lange a, i, o, u of y: apostrof, dan blijft de klinker lang. Auto's." },
    abbr: { en: "Abbreviations get an apostrophe before the s: cd's, tv's.", local: "Afkortingen krijgen een apostrof voor de s: cd's, tv's." },
    noapos: { en: 'After a consonant, a silent e or an accented vowel: just -s, no apostrophe.', local: 'Na een medeklinker, een stomme e of een klinker met accent: alleen -s, geen apostrof.' },
    time: { en: "'s stands for des, with letters missing, so the apostrophe comes first: 's avonds.", local: "'s staat voor des, er vallen letters weg, dus de apostrof komt eerst: 's avonds." },
    timecap: { en: "At the start of a sentence 's stays small and the next word gets the capital: 's Morgens.", local: "Aan het begin van een zin blijft 's klein en krijgt het volgende woord de hoofdletter: 's Morgens." },
    gen: { en: "Possessive s: an apostrophe only after a long vowel (Anna's), none after a consonant (Jans).", local: "Bezits-s: alleen een apostrof na een lange klinker (Anna's), niet na een medeklinker (Jans)." },
    gens: { en: "A name ending in an s sound gets only an apostrophe, no extra s: Max' hond.", local: "Een naam die eindigt op een s-klank krijgt alleen een apostrof, geen extra s: Max' hond." },
    zon: { en: "zo'n is short for zo een. De zon is the sun.", local: "zo'n is kort voor zo een. De zon schijnt aan de hemel." },
  },
  items: [
    ['Ik heb veel {{ideeën|ideeen}} voor het feest.', 'trema'],
    ['We gaan in de zomer naar {{België|Belgie}}.', 'trema'],
    ['Ben je {{geïnteresseerd|geinteresseerd}} in kunst?', 'trema'],
    ['De {{coördinator|coordinator}} belt je morgen.', 'trema'],
    ['Op de {{reünie|reunie}} zag ik al mijn oude klasgenoten.', 'trema'],
    ['Mijn {{knieën|knieen}} doen pijn na het hardlopen.', 'trema'],
    ['Hij is een beetje {{naïef|naief}}.', 'trema'],
    ['We bezochten de {{ruïne|ruine}} van een oud kasteel.', 'trema'],
    ['Ze gaan in februari {{skiën|skien}}.', 'trema'],
    ['Het bedrijf heeft {{financiële|financiele}} problemen.', 'notrema'],
    ['De situatie is {{financieel|financiëel}} gezond.', 'notrema'],
    ['Dit is de {{officiële|officiele}} uitslag.', 'notrema'],
    ['Het is nog niet {{officieel|officiëel}}.', 'notrema'],
    ['De {{zeeën|zeeen}} rond IJsland zijn ijskoud.', 'trema'],
    ['Reclame probeert ons te {{beïnvloeden|beinvloeden}}.', 'trema'],
    ['Ik lees graag {{poëzie|poezie}}.', 'trema'],
    ['De film duurt {{tweeënhalf|tweeenhalf}} uur.', 'trema'],
    ["Alle {{auto's|autos}} staan in de file.", 'apos'],
    ["Ik heb honderd {{foto's|fotos}} gemaakt.", 'apos'],
    ["Kun je de {{menu's|menus}} even brengen?", 'apos'],
    ["Op de kraamafdeling liggen vijf {{baby's|babys}}.", 'apos'],
    ["Er staan geen {{taxi's|taxis}} bij het station.", 'apos'],
    ["Mijn beide {{opa's|opas}} komen uit Groningen.", 'apos'],
    ["De {{paraplu's|paraplus}} liggen in de gang.", 'apos'],
    ["We aten {{pizza's|pizzas}} met de hele klas.", 'apos'],
    ["Alle {{hobby's|hobbys}} kosten geld.", 'apos'],
    ["De {{radio's|radios}} spelen allemaal hetzelfde liedje.", 'apos'],
    ["We hebben nog een doos oude {{cd's|cds}}.", 'abbr'],
    ["In de winkel hangen tien {{tv's|tvs}} naast elkaar.", 'abbr'],
    ["Er zijn twee nieuwe {{cafés|café's}} in de straat.", 'noapos'],
    ["Op kantoor staan twintig {{computers|computer's}}.", 'noapos'],
    ["We hebben drie {{films|film's}} gekeken.", 'noapos'],
    ["De {{garages|garage's}} in de buurt zijn allemaal dicht.", 'noapos'],
    ["De {{meisjes|meisje's}} spelen voetbal.", 'noapos'],
    ["Ik werk {{'s avonds|s'avonds}} het liefst.", 'time'],
    ["{{'s Morgens|S'morgens}} drink ik altijd koffie.", 'timecap'],
    ["Hij werkt {{'s nachts|s'nachts}} in een fabriek.", 'time'],
    ["Dat is {{Anna's|Annas}} fiets.", 'gen'],
    ["Dat is {{Jans|Jan's}} jas.", 'gen'],
    ["{{Max'|Max's}} hond is ontsnapt.", 'gens'],
    ["Ik heb {{zo'n|zon}} honger.", 'zon'],
    ['Doe niet zo {{egoïstisch|egoistisch}}.', 'trema'],
  ],
})

export const compounds = definePack({
  id: 'nl.compounds',
  lang: 'nl',
  title: 'aaneen / los',
  blurb: 'Compounds are one word in Dutch. Plus the few groups that stay apart.',
  rule: {
    en: 'Dutch writes compounds as one word: *tandarts*, *ziekenhuis*, *telefoonnummer*. English words inside a compound too: *accountmanager*. Writing them apart is common enough to have a name, *Engelse ziekte*, and it can change the meaning.\n\nA hyphen only appears where two vowels would clash (*auto-ongeluk*) or with an abbreviation (*tv-programma*). Some fixed groups go the other way and stay apart: *in plaats van*, *te veel*, *nog steeds*, *zo meteen*, *van alles*. The trick: one thing with one meaning is one word.',
    local: 'Samenstellingen schrijf je in het Nederlands aan elkaar: *tandarts*, *ziekenhuis*, *telefoonnummer*. Ook met Engelse woorden: *accountmanager*. Los schrijven gebeurt zo vaak dat het een naam heeft, de *Engelse ziekte*, en het kan de betekenis veranderen.\n\nEen streepje komt er alleen als twee klinkers botsen (*auto-ongeluk*) of bij een afkorting (*tv-programma*). Sommige vaste groepen gaan juist andersom en schrijf je los: *in plaats van*, *te veel*, *nog steeds*, *zo meteen*, *van alles*. De truc: één ding met één betekenis is één woord.',
  },
  hints: {
    join: { en: 'A compound is one thing with one meaning: one word.', local: 'Een samenstelling is één ding met één betekenis: één woord.' },
    eng: { en: 'English words in a Dutch compound are joined too.', local: 'Ook Engelse woorden in een samenstelling schrijf je aan elkaar.' },
    hyph: { en: 'Two vowels would clash at the join and be misread: use a hyphen.', local: 'Twee klinkers botsen op de grens en je zou ze verkeerd lezen: een streepje.' },
    abbr: { en: 'A compound with an abbreviation gets a hyphen: tv-programma.', local: 'Een samenstelling met een afkorting krijgt een streepje: tv-programma.' },
    tussenn: { en: 'The first part only has a plural in -en (pannen), so the link is -en-: pannenkoek.', local: 'Het eerste deel heeft alleen een meervoud op -en (pannen), dus de tussenklank is -en-: pannenkoek.' },
    tussens: { en: 'A linking s you can hear, and still one word: verjaardagsfeest.', local: 'Een tussen-s die je hoort, en toch één woord: verjaardagsfeest.' },
    apart: { en: 'Not a compound but a fixed group of words: these stay apart.', local: 'Geen samenstelling maar een vaste woordgroep: die schrijf je los.' },
  },
  items: [
    ['Ik moet morgen naar de {{tandarts|tand arts}}.', 'join'],
    ['Het {{ziekenhuis|zieken huis}} ligt aan de rand van de stad.', 'join'],
    ['Wat is je {{telefoonnummer|telefoon nummer}}?', 'join'],
    ['Mijn {{e-mailadres|e-mail adres}} is veranderd.', 'eng'],
    ['Hij werkt als {{accountmanager|account manager}} bij een bank.', 'eng'],
    ['Ik heb maandag een {{sollicitatiegesprek|sollicitatie gesprek}}.', 'join'],
    ['Bel de {{klantenservice|klanten service}} maar.', 'join'],
    ['We wachten bij de {{bushalte|bus halte}}.', 'join'],
    ['Ik heb mijn {{zonnebril|zonne bril}} in de auto laten liggen.', 'join'],
    ['De {{koffiemachine|koffie machine}} is weer kapot.', 'join'],
    ['Ik ben mijn {{wachtwoord|wacht woord}} vergeten.', 'join'],
    ['Voor deze baan heb je {{werkervaring|werk ervaring}} nodig.', 'join'],
    ['Na de {{zomervakantie|zomer vakantie}} begint de school weer.', 'join'],
    ['Ik zet het boek terug in de {{boekenkast|boeken kast}}.', 'join'],
    ['Hij had een {{auto-ongeluk|auto ongeluk}} op de snelweg.', 'hyph'],
    ['We eten vanavond {{pannenkoeken|pannekoeken}}.', 'tussenn'],
    ['Op mijn {{verjaardagsfeest|verjaardags feest}} kwamen dertig mensen.', 'tussens'],
    ['Hij heeft vorige week zijn {{rijbewijs|rij bewijs}} gehaald.', 'join'],
    ['Wat staat er op de {{boodschappenlijst|boodschappen lijst}}?', 'join'],
    ['We kijken naar de {{voetbalwedstrijd|voetbal wedstrijd}}.', 'join'],
    ['Is de {{zorgverzekering|zorg verzekering}} weer duurder geworden?', 'join'],
    ['Ik zet mijn fiets in de {{fietsenstalling|fietsen stalling}}.', 'join'],
    ['Ik wil een {{salarisverhoging|salaris verhoging}}.', 'join'],
    ['Bel even met de {{huisarts|huis arts}}.', 'join'],
    ['Mijn {{gebruikersnaam|gebruikers naam}} klopt niet.', 'tussens'],
    ['Bij de snackbar bestel ik een {{kaassoufflé|kaas soufflé}}.', 'join'],
    ['De {{kinderopvang|kinder opvang}} gaat om zes uur dicht.', 'join'],
    ['Ze werkt bij de {{helpdesk|help desk}}.', 'eng'],
    ['Mijn {{studentenkamer|studenten kamer}} is heel klein.', 'join'],
    ['Ik drink elke ochtend {{sinaasappelsap|sinaasappel sap}}.', 'join'],
    ['We gaan met de trein {{in plaats|inplaats}} van met de auto.', 'apart'],
    ['Je hebt {{te veel|teveel}} suiker in je thee gedaan.', 'apart'],
    ['Ik woon {{nog steeds|nogsteeds}} in Utrecht.', 'apart'],
    ['We gaan {{zo meteen|zometeen}} eten.', 'apart'],
    ['Er is {{van alles|vanalles}} te doen in de stad.', 'apart'],
    ['Mijn {{schoonmoeder|schoon moeder}} komt zondag eten.', 'join'],
    ['Het {{managementteam|management team}} vergadert elke week.', 'eng'],
    ['We lopen naar het {{treinstation|trein station}}.', 'join'],
    ['Ik heb vreselijke {{hoofdpijn|hoofd pijn}}.', 'join'],
    ['Ik ga even naar de {{supermarkt|super markt}}.', 'join'],
    ['Je hebt een {{taalfout|taal fout}} gemaakt.', 'join'],
    ['Op het {{schoolplein|school plein}} spelen de kinderen.', 'join'],
    ['Wat is je favoriete {{tv-programma|tv programma}}?', 'abbr'],
    ['Er zit een {{zee-egel|zeeëgel}} tussen de rotsen.', 'hyph'],
    ['Morgen hebben we een {{teamuitje|team uitje}}.', 'eng'],
  ],
})
