import { definePack } from '../build'

// Dutch verb spelling: d/t in the present, participle vs present, 't kofschip.
// The less frequent form of each homophone is drilled on purpose (word jij, gebeurd).

export const dt = definePack({
  id: 'nl.dt',
  lang: 'nl',
  title: 'word / wordt',
  blurb: 'd/t in the present tense, inversion traps included.',
  rule: {
    en: 'Present tense: the stem is the infinitive without -en (worden → *word*). With *ik*, write only the stem: *ik word*. With *hij*, *zij*, *het*, *u* or any single person or thing, add a t: *hij wordt*. *Jij* or *je* before the verb also gets the t (*jij wordt*), but when *jij* or *je* comes after the verb, the t goes: *word jij?* Only jij and je do that: *wordt u?* and *wordt het?* keep their t.\n\nThe trick: swap in *lopen*, where you can hear the t. *Hij loopt*, so *hij wordt*. *Loop jij?*, so *word jij?* One trap: in *Wordt je zus opgehaald?* the word *je* means *jouw*, the subject is *je zus*, and she gets the t.',
    local: 'Tegenwoordige tijd: de stam is het hele werkwoord zonder -en (worden → *word*). Bij *ik* schrijf je alleen de stam: *ik word*. Bij *hij*, *zij*, *het*, *u* of één persoon of ding komt er een t bij: *hij wordt*. *Jij* of *je* vóór het werkwoord krijgt ook een t (*jij wordt*), maar staat *jij* of *je* achter het werkwoord, dan valt de t weg: *word jij?* Alleen jij en je doen dat: *wordt u?* en *wordt het?* houden hun t.\n\nDe truc: vervang het werkwoord door *lopen*, daar hoor je de t wel. *Hij loopt*, dus *hij wordt*. *Loop jij?*, dus *word jij?* Eén valkuil: in *Wordt je zus opgehaald?* betekent *je* \'jouw\', het onderwerp is *je zus*, en die krijgt de t.',
  },
  hints: {
    ik: { en: 'With ik: just the stem, no t. Ik word.', local: 'Bij ik: alleen de stam, geen t. Ik word.' },
    ikinv: { en: 'ik after the verb: still just the stem. Morgen word ik.', local: 'Ook als ik achter het werkwoord staat: alleen de stam. Morgen word ik.' },
    jij: { en: 'jij or je before the verb: stem + t. Jij wordt.', local: 'Jij of je vóór het werkwoord: stam + t. Jij wordt.' },
    inv: { en: 'jij or je after the verb: the t drops. Test with lopen: loop jij?', local: 'Jij of je achter het werkwoord: de t valt weg. Test met lopen: loop jij?' },
    hij: { en: 'One person or thing: stem + t. Test with lopen: hij loopt, so hij wordt.', local: 'Eén persoon of ding: stam + t. Test met lopen: hij loopt, dus hij wordt.' },
    hijinv: { en: 'Only jij and je lose the t after the verb. Het, hij and zij keep it: wordt het?', local: 'Alleen jij en je verliezen de t achter het werkwoord. Het, hij en zij houden hem: wordt het?' },
    u: { en: 'With u: always stem + t, also after the verb. Wordt u geholpen?', local: 'Bij u altijd stam + t, ook achter het werkwoord. Wordt u geholpen?' },
    jouw: { en: 'Here je means jouw. The subject is a third person, so stem + t.', local: 'Hier betekent je \'jouw\'. Het onderwerp is een derde persoon, dus stam + t.' },
  },
  items: [
    ['Ik {{word|wordt}} morgen achttien.', 'ik'],
    ['Morgen {{word|wordt}} ik achttien.', 'ikinv'],
    ['{{Word|Wordt}} je morgen ook opgehaald?', 'inv'],
    ['Mijn zus {{wordt|word}} volgende maand dertig.', 'hij'],
    ['{{Wordt|Word}} je zus ook opgehaald?', 'jouw'],
    ['Jij {{wordt|word}} later vast een goede kok.', 'jij'],
    ['Hoe laat {{word|wordt}} jij morgen wakker?', 'inv'],
    ['{{Wordt|Word}} u al geholpen?', 'u'],
    ['Hij {{vindt|vind}} het een goed idee.', 'hij'],
    ['{{Vind|Vindt}} jij het ook een goed idee?', 'inv'],
    ['Ik {{vind|vindt}} spruitjes eigenlijk best lekker.', 'ik'],
    ['Wat {{vind|vindt}} je van mijn nieuwe fiets?', 'inv'],
    ['Jij {{vindt|vind}} alles leuk wat met treinen te maken heeft.', 'jij'],
    ['Mijn moeder {{vindt|vind}} haar sleutels nooit.', 'hij'],
    ['Hij {{houdt|houd}} de deur voor ons open.', 'hij'],
    ['Ik {{houd/hou|houdt}} niet van koude koffie.', 'ik'],
    ['Mijn vader {{rijdt|rijd}} elke dag naar Utrecht.', 'hij'],
    ['De trein {{rijdt|rijd}} vandaag niet.', 'hij'],
    ['Hij {{antwoordt|antwoord}} nooit op mijn berichten.', 'hij'],
    ['Ik {{antwoord|antwoordt}} morgen wel op je mail.', 'ik'],
    ['Waarom {{antwoord|antwoordt}} jij niet gewoon?', 'inv'],
    ['Het vliegtuig {{landt|land}} om half drie.', 'hij'],
    ['De kaars {{brandt|brand}} al de hele avond.', 'hij'],
    ['De badmeester {{redt|red}} een jongen uit het water.', 'hij'],
    ['Ik {{wed|wedt}} dat hij weer te laat komt.', 'ik'],
    ['Zij {{leidt|leid}} het project sinds januari.', 'hij'],
    ['Mijn opa {{lijdt|lijd}} aan reuma.', 'hij'],
    ['Deze weg {{leidt|leid}} naar het strand.', 'hij'],
    ['De winkel {{biedt|bied}} vandaag korting op alle jassen.', 'hij'],
    ['{{Bied|Biedt}} jij ook op die oude fiets?', 'inv'],
    ['Hij {{snijdt|snijd}} het brood in dunne plakjes.', 'hij'],
    ['Ik {{meld|meldt}} me morgen ziek.', 'ik'],
    ['{{Meld|Meldt}} jij je ook aan voor de cursus?', 'inv'],
    ['De wond {{bloedt|bloed}} nog een beetje.', 'hij'],
    ['Het pakket {{wordt|word}} morgen bezorgd.', 'hij'],
    ['{{Wordt|Word}} het morgen mooi weer?', 'hijinv'],
    ['Waar {{wordt|word}} het feest gehouden?', 'hijinv'],
    ['{{Vindt|Vind}} u het goed als ik het raam opendoe?', 'u'],
    ['U {{wordt|word}} zo geholpen.', 'u'],
    ['{{Word|Wordt}} jij ook zo moe van dit weer?', 'inv'],
    ['Jij {{antwoordt|antwoord}} altijd zo snel.', 'jij'],
    ['Wie {{wordt|word}} de nieuwe voorzitter?', 'hij'],
    ['Dat {{wordt|word}} lastig.', 'hij'],
    ['{{Wordt|Word}} je broer ook uitgenodigd?', 'jouw'],
    ['Je {{wordt|word}} er niet vrolijker van.', 'jij'],
    ['{{Werk|Werkt}} jij morgen ook?', 'inv'],
    ['Hij {{werkt|werk}} al twintig jaar bij de bank.', 'hij'],
    ['{{Kom|Komt}} je morgen ook naar het feest?', 'inv'],
    ['Ik {{loop|loopt}} elke ochtend een rondje door het park.', 'ik'],
    ['Volgend jaar {{verhuis|verhuist}} ik naar Den Haag.', 'ikinv'],
  ],
})

export const participle = definePack({
  id: 'nl.participle',
  lang: 'nl',
  title: 'gebeurd / gebeurt',
  blurb: 'Past participle or present tense, for verbs that sound the same.',
  rule: {
    en: 'Verbs that start with be-, ge-, ver-, ont-, her- or er- get no extra ge- in the past participle, so the participle and the present tense sound exactly alike: *het gebeurt* (now) and *het is gebeurd* (done).\n\nThe trick: is there a helper verb such as *heeft*, *is*, *wordt* or *werd* in the clause? Then you need the participle. Put the verb in the past tense to hear its letter: *het gebeurde*, so *gebeurd* with a d. *Ik verhuisde*, so *verhuisd*. No helper verb? Then it is the present tense, stem + t: *het gebeurt*. A stem that already ends in d stays as it is in the participle (*beantwoord*) and gets dt in the present (*hij beantwoordt*).',
    local: 'Werkwoorden die beginnen met be-, ge-, ver-, ont-, her- of er- krijgen geen extra ge- in het voltooid deelwoord. Daardoor klinken deelwoord en tegenwoordige tijd precies hetzelfde: *het gebeurt* (nu) en *het is gebeurd* (klaar).\n\nDe truc: staat er een hulpwerkwoord in de zin, zoals *heeft*, *is*, *wordt* of *werd*? Dan heb je het voltooid deelwoord nodig. Zet het werkwoord in de verleden tijd om de letter te horen: *het gebeurde*, dus *gebeurd* met een d. *Ik verhuisde*, dus *verhuisd*. Geen hulpwerkwoord? Dan is het tegenwoordige tijd, stam + t: *het gebeurt*. Eindigt de stam al op d? Dan blijft het deelwoord zo (*beantwoord*) en krijgt de tegenwoordige tijd dt (*hij beantwoordt*).',
  },
  hints: {
    part: { en: 'A helper verb (is, heeft, wordt) means a participle. Past tense in -de, so it ends in d.', local: 'Een hulpwerkwoord (is, heeft, wordt) betekent een voltooid deelwoord. Verleden tijd op -de, dus een d.' },
    pres: { en: 'No helper verb: present tense. One person or thing: stem + t.', local: 'Geen hulpwerkwoord: tegenwoordige tijd. Eén persoon of ding: stam + t.' },
    sub: { en: 'The helper verb can come last: dat het gebeurd is. Still a participle.', local: 'Het hulpwerkwoord kan ook achteraan staan: dat het gebeurd is. Toch een deelwoord.' },
    subpres: { en: 'No helper verb anywhere in this clause, so present tense: dat het gebeurt.', local: 'Nergens in deze bijzin een hulpwerkwoord, dus tegenwoordige tijd: dat het gebeurt.' },
    dpart: { en: 'The stem already ends in d, so the participle gets no extra t: beantwoord, gemeld.', local: 'De stam eindigt al op d, dus het deelwoord krijgt geen extra t: beantwoord, gemeld.' },
    dpres: { en: 'Stem ending in d, present tense with hij or zij: stem + t gives dt.', local: 'Stam op d, tegenwoordige tijd bij hij of zij: stam + t geeft dt.' },
    vz: { en: 'Look at the whole verb: beloven has a v, verhuizen a z. Not in \'t kofschip, so a d.', local: 'Kijk naar het hele werkwoord: beloven heeft een v, verhuizen een z. Niet in \'t kofschip, dus een d.' },
  },
  items: [
    ['Wat is er gisteren {{gebeurd|gebeurt}}?', 'part'],
    ['Wat {{gebeurt|gebeurd}} er als ik op deze knop druk?', 'pres'],
    ['Dat {{gebeurt|gebeurd}} me niet nog een keer.', 'pres'],
    ['Het ongeluk is op de A12 {{gebeurd|gebeurt}}.', 'part'],
    ['Is er iets {{gebeurd|gebeurt}}?', 'part'],
    ['Ik weet niet wat er {{gebeurd|gebeurt}} is.', 'sub'],
    ['Ik hoop dat het nooit meer {{gebeurt|gebeurd}}.', 'subpres'],
    ['Ze heeft haar fouten al {{verbeterd|verbetert}}.', 'part'],
    ['De docent {{verbetert|verbeterd}} de toetsen in de trein.', 'pres'],
    ['Zijn Nederlands is flink {{verbeterd|verbetert}}.', 'part'],
    ['Wat {{betekent|betekend}} dit woord?', 'pres'],
    ['Dit heeft veel voor mij {{betekend|betekent}}.', 'part'],
    ['Wat heeft hij daarmee {{bedoeld|bedoelt}}?', 'part'],
    ['Hij {{bedoelt|bedoeld}} het niet zo.', 'pres'],
    ['Ik heb de rekening al {{betaald|betaalt}}.', 'part'],
    ['Wie {{betaalt|betaald}} er vanavond?', 'pres'],
    ['Mijn buurman {{verhuist|verhuisd}} morgen naar Groningen.', 'pres'],
    ['Wij zijn vorig jaar {{verhuisd|verhuist}}.', 'vz'],
    ['Hij {{belooft|beloofd}} altijd veel.', 'pres'],
    ['Je hebt het zelf {{beloofd|belooft}}.', 'vz'],
    ['Ik heb de vraag nog niet {{beantwoord|beantwoordt}}.', 'dpart'],
    ['Ze {{beantwoordt|beantwoord}} elke mail binnen een uur.', 'dpres'],
    ['Het nieuws heeft zich snel {{verspreid|verspreidt}}.', 'dpart'],
    ['Het virus {{verspreidt|verspreid}} zich via de lucht.', 'dpres'],
    ['Is alles goed {{voorbereid|voorbereidt}}?', 'dpart'],
    ['Hij {{bereidt|bereid}} de soep altijd met veel knoflook.', 'dpres'],
    ['Ik heb oma {{verteld|vertelt}} over mijn nieuwe baan.', 'part'],
    ['Opa {{vertelt|verteld}} elke kerst hetzelfde verhaal.', 'pres'],
    ['Er is in tien jaar niets {{veranderd|verandert}}.', 'part'],
    ['Het weer {{verandert|veranderd}} hier elk uur.', 'pres'],
    ['De film is in het Arabisch {{vertaald|vertaalt}}.', 'part'],
    ['Zij {{vertaalt|vertaald}} boeken uit het Engels.', 'pres'],
    ['Heb je de pizza al {{besteld|bestelt}}?', 'part'],
    ['Hij {{bestelt|besteld}} altijd hetzelfde.', 'pres'],
    ['Wie {{herkent|herkend}} deze man?', 'pres'],
    ['Niemand heeft hem {{herkend|herkent}}.', 'part'],
    ['Mijn baas {{verdient|verdiend}} drie keer zoveel als ik.', 'pres'],
    ['Dat heb je echt {{verdiend|verdient}}.', 'part'],
    ['Ze heeft haar kamer mooi {{versierd|versiert}}.', 'part'],
    ['Zij {{versiert|versierd}} de taart met aardbeien.', 'pres'],
    ['Dit {{bepaalt|bepaald}} of je slaagt.', 'pres'],
    ['De datum is nog niet {{bepaald|bepaalt}}.', 'part'],
    ['Waarom heb je dat niet eerder {{gemeld|gemelt}}?', 'dpart'],
    ['Het pakket is gisteren {{verstuurd|verstuurt}}.', 'part'],
    ['Hij {{verstuurt|verstuurd}} elke vrijdag een nieuwsbrief.', 'pres'],
    ['Wat {{gebeurt|gebeurd}} hier eigenlijk?', 'pres'],
    ['De huur wordt elke maand automatisch {{betaald|betaalt}}.', 'part'],
    ['Mijn uitspraak {{verbetert|verbeterd}} elke week een beetje.', 'pres'],
  ],
})

export const kofschip = definePack({
  id: 'nl.kofschip',
  lang: 'nl',
  title: 'fietste / woonde',
  blurb: 'Past tense with -te or -de, and the participle with -t or -d.',
  rule: {
    en: 'Regular verbs form the past tense with -te or -de. Take the stem (fietsen → *fiets*). If it ends in one of the consonants of *\'t kofschip* (t, k, f, s, ch, p), add -te: *fietste*. Otherwise add -de: *woonde*. The past participle follows the same choice: *gefietst*, *gewoond*.\n\nTwo traps. Look at the infinitive, not the stem: *leven* has a v and *reizen* a z, which are not in \'t kofschip, so *leefde* and *reisde*. And a stem that already ends in t or d still gets the full ending, so you write the letter twice: *wachtte*, *antwoordde*.',
    local: 'Zwakke werkwoorden krijgen in de verleden tijd -te of -de. Neem de stam (fietsen → *fiets*). Eindigt die op een medeklinker uit *\'t kofschip* (t, k, f, s, ch, p)? Dan -te: *fietste*. Anders -de: *woonde*. Het voltooid deelwoord volgt dezelfde keuze: *gefietst*, *gewoond*.\n\nTwee valkuilen. Kijk naar het hele werkwoord, niet naar de stam: *leven* heeft een v en *reizen* een z, en die zitten niet in \'t kofschip, dus *leefde* en *reisde*. En een stam die al op t of d eindigt, krijgt toch de hele uitgang, dus je schrijft de letter twee keer: *wachtte*, *antwoordde*.',
  },
  hints: {
    te: { en: 'Stem ends in a \'t kofschip consonant (t, k, f, s, ch, p): -te.', local: 'Stam eindigt op een medeklinker uit \'t kofschip (t, k, f, s, ch, p): -te.' },
    de: { en: 'Stem does not end in t, k, f, s, ch or p: -de.', local: 'Stam eindigt niet op t, k, f, s, ch of p: -de.' },
    dde: { en: 'Stem ends in d, plus -de: a double d. Antwoord + de = antwoordde.', local: 'Stam op d, plus -de: dubbele d. Antwoord + de = antwoordde.' },
    tte: { en: 'Stem ends in t, plus -te: a double t. Wacht + te = wachtte.', local: 'Stam op t, plus -te: dubbele t. Wacht + te = wachtte.' },
    vz: { en: 'Look at the whole verb: v and z are not in \'t kofschip, so -de. Leven, leefde.', local: 'Kijk naar het hele werkwoord: v en z zitten niet in \'t kofschip, dus -de. Leven, leefde.' },
    pt: { en: 'The participle makes the same choice: \'t kofschip gives -t, otherwise -d.', local: 'Het voltooid deelwoord maakt dezelfde keuze: \'t kofschip geeft -t, anders -d.' },
    ptvz: { en: 'Participle of a verb with v or z in the infinitive: -d. Leven, geleefd.', local: 'Deelwoord van een werkwoord met v of z: -d. Leven, geleefd.' },
  },
  items: [
    ['Gisteren {{fietste|fietsde}} ik naar mijn werk.', 'te'],
    ['Ze {{werkte|werkde}} vroeger bij een bakker.', 'te'],
    ['Wij {{woonden|woonten}} drie jaar in Rotterdam.', 'de'],
    ['Hij {{speelde|speelte}} elke zaterdag voetbal.', 'de'],
    ['Ik {{wachtte|wachte}} een uur op de bus.', 'tte'],
    ['Hij {{antwoordde|antwoorde}} meteen.', 'dde'],
    ['Het vliegtuig {{landde|lande}} midden in de nacht.', 'dde'],
    ['Mijn opa {{leefde|leefte}} tot zijn honderdste.', 'vz'],
    ['Ze {{verhuisde|verhuiste}} vorig jaar naar Delft.', 'vz'],
    ['We {{reisden|reisten}} drie weken door Marokko.', 'vz'],
    ['Ik {{geloofde|geloofte}} er niets van.', 'vz'],
    ['Hij {{praatte|prate}} de hele avond over zijn auto.', 'tte'],
    ['De kat {{krabde|krabte}} aan de deur.', 'de'],
    ['Zij {{legde|legte}} het boek op tafel.', 'de'],
    ['Ik {{maakte|maakde}} pannenkoeken voor iedereen.', 'te'],
    ['We {{kookten|kookden}} samen een grote pan soep.', 'te'],
    ['Hij {{hoopte|hoopde}} op beter weer.', 'te'],
    ['Het {{regende|regente}} de hele dag.', 'de'],
    ['Ze {{lachte|lachde}} om zijn grap.', 'te'],
    ['De kinderen {{dansten|dansden}} tot middernacht.', 'te'],
    ['Ik {{zette|zete}} koffie voor de gasten.', 'tte'],
    ['De bus {{stopte|stopde}} vlak voor de deur.', 'te'],
    ['Hij {{bouwde|bouwte}} zelf een schuur in de tuin.', 'de'],
    ['Ze {{verbrandde|verbrande}} haar hand aan de hete pan.', 'dde'],
    ['Wie {{redde|rede}} de hond uit het water?', 'dde'],
    ['Ik {{huilde|huilte}} bij het einde van de film.', 'de'],
    ['Hij {{belde|belte}} me midden in de nacht.', 'de'],
    ['Ik {{wenste|wensde}} haar veel succes.', 'te'],
    ['De hond {{blafte|blafde}} naar de postbode.', 'te'],
    ['We {{wandelden|wandelten}} door het bos.', 'de'],
    ['Ze {{fluisterde|fluisterte}} iets in zijn oor.', 'de'],
    ['Ze {{kuste|kusde}} hem op zijn wang.', 'te'],
    ['Hij {{verfde|verfte}} de deur groen.', 'vz'],
    ['We {{verbaasden|verbaasten}} ons over de prijs.', 'vz'],
    ['Hij {{plakte|plakde}} een postzegel op de envelop.', 'te'],
    ['Ze {{haalde|haalte}} de trein net op tijd.', 'de'],
    ['Mijn broer {{trainde|trainte}} elke dag voor de marathon.', 'de'],
    ['Ik {{printte|printe}} het formulier twee keer.', 'tte'],
    ['Hij {{lunchte|lunchde}} altijd achter zijn bureau.', 'te'],
    ['De docent {{zuchtte|zuchte}} diep.', 'tte'],
    ['We {{bewaarden|bewaarten}} de brieven in een oude doos.', 'de'],
    ['Ik heb vandaag hard {{gewerkt|gewerkd}}.', 'pt'],
    ['Hij heeft lang in Spanje {{geleefd|geleeft}}.', 'ptvz'],
    ['Heb je al {{gestemd|gestemt}}?', 'pt'],
    ['Ze hebben de hele avond {{gedanst|gedansd}}.', 'pt'],
    ['Ik heb je drie keer {{gebeld|gebelt}}.', 'pt'],
    ['We zijn met de trein naar Parijs {{gereisd|gereist}}.', 'ptvz'],
  ],
})
