import { definePack } from '../build'

// Dutch articles and relative pronouns: de/het, die/dat.

export const deHet = definePack({
  id: 'nl.de-het',
  lang: 'nl',
  title: 'de / het',
  blurb: 'Articles: the groups that are always de or always het, and the rest.',
  rule: {
    en: 'About three in four Dutch nouns take *de*; the rest take *het*. Most het-words just have to be learned, but some groups are safe. Always *het*: diminutives (*het huisje*), verbs used as nouns (*het eten*) and words ending in -isme. Always *de*: plurals (*de huizen*) and words ending in -heid, -ing, -tie or -teit. A compound takes the article of its last part: *het ziekenhuis*, because *het huis*.\n\nThe trick for the rest: learn every noun together with its article, as if it were one word: *het raam*, *de deur*.',
    local: 'Ongeveer drie op de vier zelfstandige naamwoorden zijn de-woorden. De meeste het-woorden moet je gewoon leren, maar sommige groepen zijn zeker. Altijd *het*: verkleinwoorden (*het huisje*), werkwoorden als zelfstandig naamwoord (*het eten*) en woorden op -isme. Altijd *de*: meervouden (*de huizen*) en woorden op -heid, -ing, -tie of -teit. Een samenstelling krijgt het lidwoord van het laatste deel: *het ziekenhuis*, want *het huis*.\n\nDe truc voor de rest: leer elk woord samen met zijn lidwoord, alsof het één woord is: *het raam*, *de deur*.',
  },
  hints: {
    het: { en: 'A het-word. No rule for this one: learn it together with het.', local: 'Een het-woord. Hier is geen regel voor: leer het woord samen met het.' },
    de: { en: 'A de-word. About three in four nouns are, so de is the safe bet.', local: 'Een de-woord. Ongeveer drie op de vier woorden zijn dat, dus de is de veilige gok.' },
    dim: { en: 'Diminutives (-je, -tje, -pje) are always het.', local: 'Verkleinwoorden (-je, -tje, -pje) zijn altijd het-woorden.' },
    plural: { en: 'Plurals always take de.', local: 'Meervouden krijgen altijd de.' },
    inf: { en: 'A verb used as a noun is always het: het eten.', local: 'Een werkwoord als zelfstandig naamwoord is altijd het: het eten.' },
    suffix: { en: 'Words ending in -heid, -ing, -tie or -teit are always de.', local: 'Woorden op -heid, -ing, -tie of -teit zijn altijd de-woorden.' },
    compound: { en: 'A compound takes the article of its last part: het ziekenhuis, because het huis.', local: 'Een samenstelling krijgt het lidwoord van het laatste deel: het ziekenhuis, want het huis.' },
    isme: { en: 'Words ending in -isme are het-words.', local: 'Woorden op -isme zijn het-woorden.' },
    person: { en: 'Kind and meisje are het-words, even though they are people.', local: 'Kind en meisje zijn het-woorden, ook al zijn het mensen.' },
  },
  items: [
    ['Ik heb {{het|de}} raam opengezet.', 'het'],
    ['{{De|Het}} sleutel ligt onder de mat.', 'de'],
    ['Waar is {{het|de}} station?', 'het'],
    ['{{Het|De}} meisje naast mij leest een boek.', 'dim'],
    ['{{Het|De}} huisje aan het water is te koop.', 'dim'],
    ["{{De|Het}} auto's staan in de garage.", 'plural'],
    ['{{De|Het}} kinderen spelen buiten.', 'plural'],
    ['Ik vind {{het|de}} eten hier heerlijk.', 'inf'],
    ['{{Het|De}} zwemmen gaat steeds beter.', 'inf'],
    ['{{De|Het}} vergadering begint om negen uur.', 'suffix'],
    ['{{De|Het}} informatie staat op de website.', 'suffix'],
    ['{{De|Het}} gezondheid van mijn opa is goed.', 'suffix'],
    ['{{Het|De}} ziekenhuis ligt aan de rand van de stad.', 'compound'],
    ['{{De|Het}} voordeur staat open.', 'compound'],
    ['{{Het|De}} boek dat je me gaf, is erg spannend.', 'het'],
    ['{{De|Het}} computer doet het weer niet.', 'de'],
    ['{{Het|De}} weer is vandaag prachtig.', 'het'],
    ['Hoe laat begint {{de|het}} film?', 'de'],
    ['{{Het|De}} water is nog te koud om te zwemmen.', 'het'],
    ['Ik heb {{het|de}} geld al overgemaakt.', 'het'],
    ['{{Het|De}} probleem is opgelost.', 'het'],
    ['{{De|Het}} foto hangt boven de bank.', 'de'],
    ['{{Het|De}} jaar is bijna voorbij.', 'het'],
    ['{{De|Het}} familie komt met kerst bij ons.', 'de'],
    ['{{Het|De}} gesprek duurde twee uur.', 'het'],
    ['{{Het|De}} antwoord staat achter in het boek.', 'het'],
    ['Ik zoek {{het|de}} adres van de tandarts.', 'het'],
    ['{{De|Het}} melk is over de datum.', 'de'],
    ['{{Het|De}} bed is te kort voor mij.', 'het'],
    ['{{De|Het}} stoel wiebelt.', 'de'],
    ['{{Het|De}} toetsenbord van mijn laptop is kapot.', 'compound'],
    ['{{De|Het}} keuken is net geverfd.', 'de'],
    ['{{Het|De}} vliegtuig vertrekt om zes uur.', 'het'],
    ['{{Het|De}} museum is op maandag gesloten.', 'het'],
    ['{{De|Het}} oplossing is simpeler dan je denkt.', 'suffix'],
    ['{{Het|De}} brood is nog warm.', 'het'],
    ['{{De|Het}} tafel staat bij het raam.', 'de'],
    ['{{Het|De}} kopje koffie is koud geworden.', 'dim'],
    ['{{Het|De}} toerisme groeit elk jaar.', 'isme'],
    ['{{De|Het}} hond van de buren blaft de hele nacht.', 'de'],
    ['{{Het|De}} paard staat in de wei.', 'het'],
    ['{{Het|De}} gras moet nodig gemaaid worden.', 'het'],
    ['{{De|Het}} universiteit ligt midden in de stad.', 'suffix'],
    ['{{Het|De}} kind wil nog een ijsje.', 'person'],
    ['{{De|Het}} trein naar Zwolle heeft vertraging.', 'de'],
    ["{{Het|De}} park is 's avonds gesloten.", 'het'],
  ],
})

export const dieDat = definePack({
  id: 'nl.die-dat',
  lang: 'nl',
  title: 'die / dat',
  blurb: 'Relative and pointing pronouns after de-words, het-words and plurals.',
  rule: {
    en: 'In a relative clause, *die* refers back to de-words and to all plurals, and *dat* refers back to het-words: *de man die*, *het huis dat*, *de huizen die*. Pointing words work the same way: *die stoel*, *dat boek*, *die boeken*.\n\nThe trick: look at the noun right before the gap and ask yourself *de* or *het*. Diminutives are always het-words, so *het meisje dat*.',
    local: 'In een bijzin verwijst *die* naar de-woorden en naar alle meervouden, en *dat* naar het-woorden: *de man die*, *het huis dat*, *de huizen die*. Aanwijzende woorden werken hetzelfde: *die stoel*, *dat boek*, *die boeken*.\n\nDe truc: kijk naar het zelfstandig naamwoord vlak voor het gat en vraag je af: *de* of *het*? Verkleinwoorden zijn altijd het-woorden, dus *het meisje dat*.',
  },
  hints: {
    de: { en: 'De-word, so die: de man die.', local: 'De-woord, dus die: de man die.' },
    het: { en: 'Het-word, so dat: het huis dat.', local: 'Het-woord, dus dat: het huis dat.' },
    plural: { en: 'Plural, always die: de huizen die.', local: 'Meervoud, altijd die: de huizen die.' },
    dim: { en: 'Diminutives are het-words, so dat: het meisje dat.', local: 'Verkleinwoorden zijn het-woorden, dus dat: het meisje dat.' },
    demde: { en: 'Pointing at a de-word: die stoel.', local: 'Aanwijzen bij een de-woord: die stoel.' },
    demhet: { en: 'Pointing at a het-word: dat boek.', local: 'Aanwijzen bij een het-woord: dat boek.' },
    demplural: { en: 'Pointing at a plural: always die. Die schoenen.', local: 'Aanwijzen bij een meervoud: altijd die. Die schoenen.' },
  },
  items: [
    ['Het huis {{dat|die}} we hebben gekocht, is oud.', 'het'],
    ['De man {{die|dat}} naast ons woont, is aardig.', 'de'],
    ['Het meisje {{dat|die}} de hoofdrol speelt, is pas twaalf.', 'dim'],
    ['De boeken {{die|dat}} op tafel liggen, zijn van mij.', 'plural'],
    ['Het boek {{dat|die}} ik nu lees, is erg spannend.', 'het'],
    ['De fiets {{die|dat}} ik gisteren kocht, is al kapot.', 'de'],
    ['Het kind {{dat|die}} daar speelt, is mijn neefje.', 'het'],
    ['De kinderen {{die|dat}} daar spelen, zijn mijn neven.', 'plural'],
    ['Het liedje {{dat|die}} op de radio was, zit nog in mijn hoofd.', 'dim'],
    ['De stad {{die|dat}} ik het mooist vind, is Leiden.', 'de'],
    ['Het land {{dat|die}} hij het vaakst heeft bezocht, is Portugal.', 'het'],
    ['Ken je de vrouw {{die|dat}} bij de bakker werkt?', 'de'],
    ['Het cadeau {{dat|die}} je me gaf, gebruik ik elke dag.', 'het'],
    ['De film {{die|dat}} we zagen, duurde drie uur.', 'de'],
    ['Het werk {{dat|die}} ze doet, is zwaar.', 'het'],
    ['De mensen {{die|dat}} hier wonen, zijn erg vriendelijk.', 'plural'],
    ['Het bericht {{dat|die}} je stuurde, is nooit aangekomen.', 'het'],
    ['De trein {{die|dat}} om acht uur vertrekt, is altijd vol.', 'de'],
    ['Het team {{dat|die}} wint, krijgt een beker.', 'het'],
    ['Het gebouw {{dat|die}} je daar ziet, is het stadhuis.', 'het'],
    ['De taart {{die|dat}} oma bakte, was in tien minuten op.', 'de'],
    ['Het woord {{dat|die}} ik zocht, schiet me nu te binnen.', 'het'],
    ['{{Die|Dat}} stoel is te hoog voor mij.', 'demde'],
    ['{{Dat|Die}} boek heb ik al gelezen.', 'demhet'],
    ['Wie is {{die|dat}} man met de hoed?', 'demde'],
    ['{{Dat|Die}} meisje zit bij mij in de klas.', 'demhet'],
    ['Ik wil {{dat|die}} huis graag een keer vanbinnen zien.', 'demhet'],
    ['{{Die|Dat}} schoenen passen niet.', 'demplural'],
    ['Het verhaal {{dat|die}} hij vertelde, klopte niet.', 'het'],
    ['De sleutel {{die|dat}} je zoekt, ligt op de kast.', 'de'],
    ['Het jaar {{dat|die}} we in Spanje woonden, was het mooiste.', 'het'],
    ['De collega {{die|dat}} ziek was, is weer beter.', 'de'],
    ['Het probleem {{dat|die}} je noemt, is al opgelost.', 'het'],
    ['De brief {{die|dat}} ik kreeg, kwam van de gemeente.', 'de'],
    ['Het museum {{dat|die}} we bezochten, was gratis.', 'het'],
    ['Het hondje {{dat|die}} altijd blaft, heet Bram.', 'dim'],
    ['De vragen {{die|dat}} je stelt, zijn heel goed.', 'plural'],
    ['Het spel {{dat|die}} we speelden, duurde eindeloos.', 'het'],
    ['Het adres {{dat|die}} je me gaf, bestaat niet.', 'het'],
    ['De jas {{die|dat}} je aanhebt, staat je goed.', 'de'],
    ['Het water {{dat|die}} uit de kraan komt, is drinkbaar.', 'het'],
    ['{{Dat|Die}} raam moet dicht, want het tocht.', 'demhet'],
    ['Zie je {{die|dat}} vogels op het dak?', 'demplural'],
  ],
})
