import { describe, expect, it } from 'vitest'
import { runRules } from '../../engine'
import { nlDict } from '../../test-utils/nlDict'
import { nlRules } from '.'

// Every rule must stay silent on correct Dutch. These are the 46 verified dictee sentences and the
// 8 listen-and-type sentences from docs/research/dutch-errors.md §9, plus correct paragraphs in news,
// chat and learner style. Any high/medium flag here is a false positive.

const DICTEE = [
  'Word je morgen ook om zeven uur opgehaald, of wordt je zus eerst gebracht?',
  'Hij wordt elke dag om zes uur wakker, maar ik word pas om acht uur wakker.',
  'Vind jij het ook raar dat hij nooit antwoordt als je hem iets vraagt?',
  'Wat er gisteren is gebeurd, gebeurt hopelijk nooit meer.',
  'Ze heeft haar tekst drie keer verbeterd en nu verbetert ze die van haar broer.',
  'De docent beantwoordt nu de vragen die hij vorige week niet heeft beantwoord.',
  'Wordt u al geholpen, of mag ik u even iets vragen?',
  'Hij vond zijn sleutels pas terug nadat hij het hele huis had doorzocht.',
  'Ik houd van pannenkoeken met stroop, maar mijn vriendin houdt meer van poffertjes.',
  'Het meisje dat naast mij woont, heeft een hond die heel hard blaft.',
  'Het boek dat ik gisteren heb gekocht, ligt nu op de tafel in de woonkamer.',
  'Zij zijn groter dan wij, maar niet zo groot als onze buren.',
  'Zij hebben hun huiswerk vergeten, dus de leraar heeft hun een extra opdracht gegeven.',
  'Hoe laat begint de film die jij zo graag wilt zien?',
  "Ik heb mijn telefoon geüpdatet en daarna alle foto's gedownload.",
  "De auto's van mijn ooms staan al dagen voor het ziekenhuis geparkeerd.",
  'Bij de snackbar bestel ik altijd een kaassoufflé en een portie patat.',
  "Mijn ideeën over de coördinatie van het project zijn heel anders dan die van mijn collega's.",
  'We zijn in België geweest en hebben daar veel cafés en musea bezocht.',
  'Eigenlijk wil ik niet per se winnen, maar ik doe sowieso mee.',
  'Het enige wat ik wil, is dat iedereen te allen tijde veilig is.',
  'Beide kinderen waren ziek, dus zijn ze allebei thuisgebleven.',
  'Op maandag 3 januari spreken we Nederlands, Engels en Arabisch met onze nieuwe buren.',
  'Het verhaal dat jij vertelde, klopte niet; dat heb ik meteen gemerkt.',
  'Hij verhuisde vorig jaar naar Utrecht en leefde daar heel rustig.',
  'Wie heeft het laatste stuk taart opgegeten dat in de koelkast stond?',
  'Ik zet de vaas op de tafel en ga daarna even op de bank liggen.',
  'Kun jij me vertellen waar mijn tas ligt? Ik heb hem net nog gezien.',
  'Het wordt tijd dat je je kamer opruimt, want het ziet er niet uit.',
  'Mijn broer rijdt elke ochtend met de fiets naar zijn werk, ook als het regent.',
  'Ik besef dat ik te laat ben, maar de trein had vertraging.',
  'Het nieuws dat de minister heeft verspreid, verspreidt zich razendsnel.',
  'Wie heeft dat verzonnen? Ik heb het nooit zo bedoeld.',
  'De vergadering werd uitgesteld omdat de voorzitter ziek was geworden.',
  'Hoe vaak heb je dit al gezegd? Het verandert toch niets.',
  'Ik antwoordde meteen, maar hij heeft nog steeds niet geantwoord.',
  'Je bent geïnteresseerd in talen, dus je vindt deze oefening vast leuk.',
  'Morgen leg ik het pakketje bij de buren neer, want ik ben de hele dag weg.',
  'Zijn jullie al aan het nieuwe hoofdstuk begonnen, of moeten we nog even wachten?',
  'Het kind dat zijn fiets kwijt was, vond hem terug achter de schuur.',
  'De brandweerman redt de kat, die al uren in de boom zat.',
  'Zij lijdt al jaren aan migraine, maar ze leidt toch haar eigen bedrijf.',
  'Hij belooft dat hij op tijd komt, maar dat heeft hij vorige week ook beloofd.',
  'Gisteren fietste ik naar de markt en kocht ik verse groente.',
  'Het water bevroor, dus we schaatsten de hele middag op de vijver.',
  'Ze heeft de foto geliket en daarna haar profiel geüpdatet.',
]

const LISTEN = [
  'Omdat ik moe ben, ga ik vanavond vroeg naar bed.',
  'Ik ken hem niet, maar ik weet wel waar hij woont.',
  'Wij hebben gisteren een groot huis met een mooie tuin gezien.',
  'Het grote huis op de hoek is van een oude dame die alleen woont.',
  'Ik wachtte een uur op de bus, maar hij kwam niet.',
  'Hebt u het formulier al ingevuld, of zal ik u even helpen?',
  'Zij zijn vorige zomer naar Marokko gegaan en zijn daar drie weken gebleven.',
  'Ik ben het helemaal met je eens: dit is een heel mooie dag.',
]

const NEWS = `Het kabinet heeft dinsdag besloten dat de huurprijzen volgend jaar minder hard mogen stijgen. Volgens de minister is dat nodig omdat veel huishoudens moeite hebben om hun vaste lasten te betalen. De Tweede Kamer moet nog met het plan instemmen. Woningcorporaties zijn kritisch: zij vrezen dat er minder geld overblijft voor onderhoud en nieuwbouw. "We begrijpen de keuze, maar het is niet genoeg," zegt een woordvoerder van de koepelorganisatie. In Amsterdam en Utrecht staan inmiddels duizenden mensen op een wachtlijst. Het onderzoek dat de gemeente vorige maand publiceerde, laat zien dat de gemiddelde wachttijd al bijna tien jaar is.`

const CHAT = `Hoi! Hoe gaat het met je? Ik heb je bericht pas net gezien, sorry. Morgen kan ik helaas niet, want ik moet werken. Zaterdag lukt wel, als jij dan ook kunt. Zullen we om twee uur bij het station afspreken? Ik neem de fiets mee. Laat maar weten wat je ervan vindt! Groetjes en tot snel.`

const LEARNER = `Mijn naam is Karim en ik woon sinds twee jaar in Rotterdam. Ik werk in een restaurant en 's avonds volg ik een cursus Nederlands. De lessen zijn soms moeilijk, maar de leraar legt alles heel goed uit. Gisteren hebben we geleerd hoe je een brief schrijft. Ik vind de Nederlandse taal mooi, al is de uitspraak lastig. Mijn vrouw en ik willen volgend jaar een groter huis zoeken, omdat ons appartement te klein is geworden. Wat vind jij van de buurt waar wij nu wonen? Het park is dichtbij en de kinderen kunnen er veilig spelen.`

const STORY = `Het was een koude ochtend in januari. Anna stond vroeg op, zette koffie en keek naar buiten. De straat was nog donker en stil. Toen ze haar jas aantrok, hoorde ze iemand op de deur kloppen. Het was haar buurman, die zijn sleutels was vergeten. "Mag ik even bij jou wachten tot mijn vrouw thuiskomt?" vroeg hij. Natuurlijk mocht dat. Ze dronken samen koffie en praatten over het weer, het werk en de kinderen. Na een halfuur werd er gebeld: zijn vrouw was er. Hij bedankte Anna hartelijk en ging naar huis. Ze glimlachte. Zo'n begin van de dag had ze niet verwacht.`

const MIXED = `Wat er ook gebeurt, ik blijf positief. Hij zegt dat het al betaald is. Het is gebeurd en het gebeurt nooit meer. Ik vind het top. Is het gebeurd? Heb je het verbeterd? Hij gaf me boeken. Het is beter als je komt. Ik hou van je. Hou je van koffie? Jij kan het en jij kunt het. Wil je thee? Jij wilt koffie. U hebt gelijk en u heeft gelijk. Wordt je broer ook opgehaald? Het meisje, die nogal verlegen is, zegt niets. Toch blijft het theorie. Is dat waar? Kan je me helpen? Dat vind ik leuk. Die film vind ik saai. Wat vind je ervan? Daar ben ik het mee eens. Ik heb het boek gelezen dat je me gaf. De man die daar loopt, is mijn oom. Ik ken hem al jaren. Ik weet niet wat er gebeurd is. Vandaag ga ik naar de markt. Natuurlijk, ik kom morgen. Ook ik ben moe. Nu ik erover nadenk, heb je gelijk. Toen ik thuiskwam, was iedereen al weg. Dit betekent veel voor mij. Wat betekent dit? Het is voor jou. Bedankt voor uw bericht. Ze wonen in Den Haag. De zon schijnt. In de zon zitten is fijn. Ik ga even liggen. Zij zei dat het klopte. Het boek ligt op tafel. Het licht in de kamer is uit. Ik heb te veel gegeten. Zowel kinderen als ouders waren blij. Even groot als jij. Hetzelfde als gisteren. Hij is ouder dan ik. Dat is het enige wat ik weet. Beide broers zijn ziek. Hun huis is groot. Ik geef hun een cadeau. Met jou ga ik graag op reis. Ik zie je morgen. De school heeft haar leerlingen geld gegeven. Hij heeft een groot huis. Een mooi meisje en een lief kind. Dit huis is van ons. Ons huis staat aan het water. Ik heb geen tijd. Het is niet een probleem maar een kans.`


/** antipatterns from the research notes and tricky constructions that look like errors but are not */
const TRICKY = [
  'Terwijl hij verbaasd opkeek, liep zij de kamer uit.',
  'Omdat ze beledigd wegliep, bleef hij alleen achter.',
  'Ik weet niet of ik het red.',
  'Als ik het vind, laat ik het je weten.',
  'Ik vind het verbeterd, maar nog niet perfect.',
  'Het verhaal, verteld door mijn opa, was spannend.',
  'Dat het verandert, is duidelijk.',
  'Hij heeft gezegd dat het gebeurt.',
  'Is het waar dat hij verhuist?',
  'Het is een systeem dat goed betaalt.',
  'Het is iets dat steeds verandert.',
  'Ik heb geen idee hoe het werkt.',
  'Ik ben blij met hoe het verandert.',
  'Ik ben benieuwd of het verandert.',
  'We hebben afgesproken dat hij betaalt.',
  'Ik heb het gevoel alsof alles verandert.',
  'Het is jammer dat niemand het herhaalt.',
  'De man die alles vertaalt, is mijn buurman.',
  'Hij is degene die altijd betaalt.',
  'Het boek bleef onbewaard liggen.',
  'Dat bewaard gebleven boek is oud.',
  'Hij leek verbaasd.',
  'Wie betaalt de rekening?',
  'Wat betekent dat woord?',
  'Dat betekent niets.',
  'Wie heeft dat bedacht?',
  'Het is al betaald.',
  'Het geld is verdwenen.',
  'Ik heb het verdwenen geld gevonden.',
  'Hij heeft het overleden familielid begraven.',
  'Ik heb een kind dat geboren is in mei.',
  'Hij is gisteren overleden.',
  'Ik heb het gevoel opnieuw geboren te zijn.',
  'Hij zal het wel gedaan hebben.',
  'Ik heb hem zien gaan.',
  'Hebben jullie het gezien?',
  'Morgen ga ik naar Amsterdam.',
  'Natuurlijk, ik help je graag.',
  'Ook ik heb honger.',
  'Zelfs ik weet dat.',
  'Nu ik hier ben, wil ik iets zeggen.',
  'Toen ik binnenkwam, zat iedereen al aan tafel.',
  'Daarom ben ik zo blij.',
  'Misschien kom ik later.',
  'Gisteren heb ik hard gewerkt.',
  'Hij woont in Amsterdam omdat hij daar werkt.',
  'Ik denk dat het een goed idee is.',
  'Ik weet dat hij wacht op de bus.',
  'Omdat ik heb gewerkt, ben ik moe.',
  'Omdat ik ben gaan zwemmen, heb ik honger.',
  'Net als jij heb ik honger.',
  'Zo groot als ik ben, pas ik er niet in.',
  'Als je wilt, kun je blijven.',
  'Hij is net zo oud als ik.',
  'Het is beter als de kinderen thuis blijven.',
  'Het is beter als het regent.',
  'Hij is liever thuis als het koud is.',
  'Hij is ouder dan ik dacht.',
  'Het is anders als je ouder bent.',
  'Is het zo koud dan?',
  'Ben je echt zo moe dan?',
  'Waarom is het hetzelfde dan?',
  'De zon schijnt en de vogels zingen.',
  'Ik zit graag in de zon.',
  'Het licht op zolder doet het niet.',
  'Zijn gezicht licht op als hij lacht.',
  'Het boek ligt op tafel.',
  'Het is licht in de kamer.',
  'Ze leidt het bedrijf al tien jaar.',
  'Dit leidt tot problemen.',
  'Hij lijdt aan hoofdpijn.',
  'De kwaliteit lijdt onder de drukte.',
  'Het deeg rijst in de oven.',
  'De vraag rijst of dat klopt.',
  'Hij reist veel voor zijn werk.',
  'Ik eet graag rijst met kip.',
  'Hij zei dat hij moe was.',
  'Zij zegt dat het klopt.',
  'Het zij zo.',
  'Hij of zij moet het doen.',
  'Zei hij dat echt?',
  'Ze hebben samen een huis gekocht.',
  'Hun kinderen spelen buiten.',
  'Hun hebben ze niets gegeven.',
  'Ik geef hun een boek.',
  'Ze gaf me een cadeau.',
  'Hij stuurde me berichten.',
  'Ze heeft voor me koffie gezet.',
  'Hij komt naar me toe.',
  'Ik heb het voor jou gekocht.',
  'Ik heb voor jou koffie gezet.',
  'Ik ga met jou mee.',
  'Dit is jouw boek.',
  'Is dit jouw boek of mijn boek?',
  'Jouw en mijn ouders kennen elkaar.',
  'Dat is jouw probleem.',
  'Bedankt voor uw begrip.',
  'Ik heb begrip voor u.',
  'Dit is voor u.',
  'Het meisje dat ik ken, woont hier.',
  'Het boek die man gaf, was saai.',
  'Het kind, die erg verlegen was, zei niets.',
  'Het huis waar ik woon, is oud.',
  'Alles wat ik weet, heb ik van haar geleerd.',
  'Iets wat je niet weet, kan je geen pijn doen.',
  'Een groot huis met een mooie tuin.',
  'Het grote huis en de kleine tuin.',
  'Deze week ga ik naar huis.',
  'Dit huis is groot en deze auto is snel.',
  'Ons huis en onze auto.',
  'Ik vind het mooi weer vandaag.',
  'Ik vind het groot nieuws.',
  'Hij gaf ons goed advies.',
  'Ik geef hun goed advies.',
  'Ze zijn groot fan van voetbal.',
  'De oud-voorzitter was er ook.',
  'Op de been blijven is belangrijk.',
  'In het begin was het moeilijk.',
  'Ik heb het hele jaar gewerkt.',
  'De hele stad was versierd.',
  'Ik woon in het centrum.',
  'De meisjes spelen buiten.',
  'Wat een groot huis!',
  'Ze kamt haar haar.',
  'Ik denk dat dat klopt.',
  'De man die die auto heeft, woont hier.',
  'Het is tijd dat je je huiswerk maakt.',
  'Hij stapt in in Utrecht.',
  'Wat het is is onduidelijk.',
  'Kom je ook?',
  'Ga je mee?',
  'Hoe vind je het?',
  'Vind je het leuk?',
  'Lukt je dat?',
  'Is je iets opgevallen?',
  'Doet je dat pijn?',
  'Wordt je dat verteld?',
  'Wat wordt je gevraagd?',
  'Kost je dat veel?',
  'Ik vind u erg aardig.',
  'Ik zie u morgen.',
  'Mag ik u iets vragen?',
  'Hoe kan ik u helpen?',
  'U bent welkom.',
  'U hebt gelijk.',
  'Ik ben het er niet mee eens.',
  'Daar ben ik het mee eens.',
  'Ik ben het met hem eens.',
  'Ik ken het eten hier niet.',
  'Ik ken mensen die dat doen.',
  'Ken je dat liedje?',
  'Ik ken je wat beter dan hij.',
  'Weet je het nog?',
  'Ik weet hem te vinden.',
  'Ik weet haar adres niet.',
  'Ik ga het even leggen.',
  'Waar ga je dat leggen?',
  'Ik ga thee zetten.',
  'Ik ga even koffie zetten.',
  'Hij is een heel aardige man.',
  'De hele mooie stad was leeg.',
  'Ik heb geen tijd.',
  'Het is niet een maar twee keer gebeurd.',
  'Hij heeft het nooit gedaan.',
  'In huis werk ik graag.',
  'Ik werk thuis.',
  'Ze gaf de school geld.',
  'Hij woont aan de Herengracht.',
  'Op 3 mei 2024 om 10.30 uur begint het.',
  'Het kost €3,50 per stuk.',
  'Bel me op 06-12345678.',
  'Mijn e-mailadres is jan@example.nl.',
  'Kijk op www.parrotype.nl voor meer info.',
  'Dhr. Jansen en mevr. De Vries waren er o.a. ook.',
  'We hadden appels, peren enz. Daarna gingen we naar huis.',
  'Ik las het in het boek van J.K. Rowling.',
  '"Kom je ook?" vroeg hij.',
  'Ze zei: "Ik kom morgen."',
  'Ik weet het niet... misschien morgen.',
  "'s Avonds lees ik graag.",
  "'t Is mooi weer vandaag.",
  "Ik ga 's ochtends altijd hardlopen.",
  "Dat is zo'n leuk idee.",
  "Hij heeft z'n tas vergeten.",
  "Ze heeft de foto's van haar opa's verjaardag.",
  'De cafés in Parijs zijn duur.',
  'Hij speelt in de band van zijn broer.',
  'Hij woont in Leiden, onder de rook van Den Haag.',
  'Voor het eerst sinds jaren regent het hier niet.',
  'Het team heeft hard gewerkt.',
  'Hij heeft het huis geschilderd.',
  'Ik ben in januari jarig.',
  'We gaan in de zomer naar Spanje.',
  'Goede Vrijdag valt dit jaar laat.',
  'Keizer Augustus regeerde lang.',
  'Ik spreek Nederlands, Engels en Arabisch.',
  'De engelen zongen.',
  'Ik heb het helemaal gehad.',
  'Zijn moeder verhuist volgende week.',
  'Zij zijn verhuisd.',
  'Ik ben verhuisd naar Utrecht.',
  'Was de was al droog?',
  'Hij was moe.',
  'Het team bestaat uit vijf spelers.',
  'Dat geldt voor iedereen.',
  'De kat ligt in de zon.',
  'Iemand vindt het altijd leuk.',
  'Niemand weet het.',
  'Iedereen houdt van ijs.',
  'Men zegt dat het waar is.',
  'Dat land is mooi.',
  'Het antwoord is ja.',
  'Je antwoord is goed.',
  'Je geld ligt op tafel.',
  'Omdat hij antwoord gaf, was ik blij.',
  'Omdat zij bloed verloor, ging ze naar het ziekenhuis.',
  'Als u antwoord wilt, moet u bellen.',
  'Is hij bereid om te helpen?',
  'Ben jij bereid om te komen?',
  'Hij is bereid om te helpen.',
  'Ze zijn er klaar voor.',
  'Ik denk aan jou, schat.',
  'Tot morgen!',
]

/** longer texts in different registers: travel story, formal mail, chat, news, recipe, memoir */
const PARAGRAPHS = [
  'Vorige week ben ik met mijn zus naar Antwerpen geweest. We hebben de trein genomen, want met de auto sta je daar alleen maar in de file. Toen we aankwamen, regende het, maar dat mocht de pret niet drukken. Eerst hebben we koffie gedronken in een klein café vlak bij het station. Daarna zijn we naar het museum gelopen. Het gebouw is prachtig gerenoveerd en de collectie is indrukwekkend. Mijn zus, die kunstgeschiedenis heeft gestudeerd, kon bij elk schilderij wel iets vertellen. Ik vond dat erg leuk, al heb ik niet alles onthouden.',
  "'s Middags hebben we gewinkeld. Mijn zus kocht een jas die ze al maanden wilde hebben, en ik vond een boek over de geschiedenis van de stad. Rond zes uur gingen we eten in een restaurant dat een vriendin ons had aangeraden. Het eten was heerlijk en de bediening was vriendelijk. We hebben nog lang nagepraat over vroeger. Om tien uur namen we de trein terug. In de trein viel mijn zus in slaap, en ik las nog een paar hoofdstukken uit mijn nieuwe boek.",
  'Beste meneer Jansen, hartelijk dank voor uw snelle reactie. Graag bevestig ik onze afspraak op donderdag 12 september om 14.00 uur. Mocht u verhinderd zijn, dan hoor ik dat graag zo snel mogelijk. Ik stuur u alvast de documenten die we tijdens het gesprek willen bespreken. Met vriendelijke groet, Fatima el Amrani.',
  'Hé, ben je er al? Ik sta bij de ingang. Het is hier superdruk, dus ik zie je misschien niet meteen. Bel me even als je er bent! Ik heb trouwens kaartjes voor ons allebei gekocht, dus dat hoef jij niet meer te doen. Tot zo!',
  'De gemeente wil het centrum autovrij maken. Volgens de wethouder wordt de binnenstad daardoor aantrekkelijker voor bewoners en bezoekers. Ondernemers zijn verdeeld: sommigen verwachten meer klanten, anderen vrezen dat mensen wegblijven omdat ze niet meer voor de deur kunnen parkeren. Er komt een proef van een halfjaar. Daarna wordt bekeken of de maatregel blijft. Wie bezwaar wil maken, kan dat tot het einde van de maand doen via de website.',
  'Ik heb gisteren mijn rijexamen gehaald! Ik was ontzettend zenuwachtig, want de eerste keer was ik gezakt. De examinator was gelukkig heel aardig. Hij zei dat ik rustig reed en goed om me heen keek. Alleen bij het inparkeren ging het bijna mis, maar dat heeft hij me vergeven. Nu mag ik eindelijk zelf rijden. Morgen ga ik met mijn moeder naar oma, en dan rijd ik!',
  'Kinderen leren een taal het snelst als ze er veel mee in aanraking komen. Daarom is het belangrijk dat ouders voorlezen, ook als hun kind zelf al kan lezen. Onderzoek laat zien dat kinderen die vaak worden voorgelezen, later beter scoren op school. Het maakt daarbij niet zoveel uit welk boek je kiest, als het kind het maar leuk vindt.',
  'Wat heb jij dit weekend gedaan? Ik ben vooral thuis gebleven, want ik was een beetje ziek. Ik heb veel series gekeken en soep gegeten. Gelukkig voel ik me nu weer beter. Zullen we volgende week iets afspreken? Ik heb dinsdag en vrijdag tijd.',
  'Het recept is eenvoudig. Snijd de ui en de knoflook fijn en bak ze in een beetje olie. Voeg de tomaten toe en laat het geheel tien minuten zachtjes koken. Breng op smaak met zout, peper en een snufje suiker. Kook ondertussen de pasta volgens de aanwijzingen op de verpakking. Serveer met verse basilicum en geraspte kaas.',
  'Mijn opa is in 1945 geboren, vlak na de oorlog. Hij groeide op in een klein dorp in Brabant, waar zijn ouders een boerderij hadden. Als jongen moest hij elke ochtend de koeien melken voordat hij naar school ging. Later is hij naar de stad verhuisd en werd hij leraar. Hij vertelt nog altijd graag over vroeger, en wij luisteren graag.',
  'Volgens de weersverwachting wordt het morgen zonnig en warm. In het zuiden kan het 30 graden worden. Aan het eind van de middag ontstaan er mogelijk onweersbuien. Het KNMI adviseert mensen om veel water te drinken en de zon op het heetst van de dag te vermijden.',
  'Ik snap niet waarom hij dat heeft gedaan. Hij wist toch dat het niet mocht? Als ik hem was geweest, had ik het eerst gevraagd. Maar goed, het is gebeurd en we kunnen het niet meer terugdraaien. Laten we er maar het beste van maken.',
  'De voorzitter opende de vergadering om acht uur. Hij heette iedereen welkom en gaf het woord aan de penningmeester, die de cijfers van het afgelopen jaar toelichtte. Daarna werd er gestemd over het nieuwe beleidsplan. Het plan werd met grote meerderheid aangenomen. Om half tien sloot de voorzitter de vergadering.',
  'Weet jij hoe laat de winkel opengaat? Ik moet nog brood, melk en eieren halen. Als het lukt, haal ik ook bloemen voor mama, want ze is morgen jarig. Heb jij al een cadeau voor haar? Anders kunnen we samen iets kopen.',
  'Sinds ik in Nederland woon, fiets ik elke dag. In het begin vond ik het eng, vooral in de drukke stad, maar nu kan ik niet meer zonder. Het is gezond, goedkoop en vaak sneller dan de bus. Alleen als het hard regent, neem ik het openbaar vervoer.',
  'Hoeveel kost een kaartje naar Groningen? Ik wil zaterdag gaan, maar ik weet niet of er werkzaamheden zijn. Vorige keer moest ik een stuk met de bus, en dat duurde eindeloos. Kun je het voor me opzoeken? Dan trakteer ik je op een ijsje.',
  'Hij heeft het boek dat ik hem had geleend, nooit teruggegeven. Toen ik ernaar vroeg, deed hij alsof hij van niets wist. Dat vind ik jammer, want het was een cadeau van mijn vader. Ik denk dat ik het maar opnieuw koop.',
  'Het was een lange dag. Ik ben om zes uur opgestaan, heb drie vergaderingen gehad en ben pas om acht uur thuisgekomen. Nu lig ik op de bank met een kop thee. Morgen begint alles weer opnieuw, maar daar denk ik nu even niet aan.',
  'Wij wonen al twintig jaar in deze straat. De buren kennen elkaar goed en helpen elkaar waar dat kan. Als iemand op vakantie gaat, geven we de planten water en halen we de post binnen. Elk jaar organiseren we een straatfeest, waar iedereen iets lekkers meeneemt.',
  'Wordt het niet eens tijd dat we de keuken opknappen? De kastjes zijn oud en de kraan lekt al maanden. Ik heb een paar offertes opgevraagd. De goedkoopste is van een bedrijf uit Delft, maar ik weet niet hoe betrouwbaar dat is. Wat vind jij?',
  'Het was een leuk feest. Er werd gedanst, gelachen en veel gegeten. De taart die mijn tante had gebakken, was binnen tien minuten op. Iedereen vond het jammer dat het om twaalf uur al afgelopen was.',
  'Ze vroeg of ik zin had om mee te gaan naar de film. Ik zei dat ik eerst mijn huiswerk moest afmaken, maar dat ik daarna wel kon. Uiteindelijk zijn we naar de voorstelling van negen uur gegaan. De film was spannend en het einde verraste ons allebei.',
  'Ik ben het niet met je eens dat de regels te streng zijn. Ze zijn er juist om iedereen te beschermen. Natuurlijk kun je over details discussiëren, maar het principe is goed. Bovendien zijn de meeste mensen tevreden over hoe het nu geregeld is.',
  'Het team heeft het hele seizoen hard gewerkt en is uiteindelijk kampioen geworden. De spelers werden na afloop door honderden supporters toegejuicht. De trainer was trots: "Dit hebben we samen bereikt," zei hij. Volgend jaar speelt de club in de hoogste divisie.',
]

/** everyday sentences around the broad high-confidence rules (clauses, articles, adjectives, capitals) */
const EVERYDAY = [
  'Het probleem is dat hij niet betaalt.',
  'Het punt is dat niemand het vertelt.',
  'De vraag is wie dat betaalt.',
  'Het idee is dat iedereen meebetaalt.',
  'Hij is iemand die altijd alles vertelt wat hij weet.',
  'Het enige wat telt, is dat je het probeert.',
  'Ik ben er niet zeker van of hij het betaalt.',
  'Het is niet duidelijk hoeveel het kost en wie het betaalt.',
  'Ze zijn bang dat het verandert.',
  'Hij was boos omdat niemand hem iets vertelt.',
  'Het wordt tijd dat iemand het vertelt.',
  'Het is maar de vraag of hij verhuist.',
  'Wat heeft hij je verteld?',
  'Hoe lang heb je daar gewoond?',
  'Waar ben je geboren?',
  'Ik heb gehoord dat ze is verhuisd.',
  'Hij heeft gezegd dat hij wordt opgehaald.',
  'Is het je gelukt om te komen?',
  'Het meisje heeft een boek dat ze graag leest.',
  'Het kind heeft een hond die graag rent.',
  'Ik heb het boek gelezen, dat je me had aangeraden.',
  'Ik ken het verhaal dat hij vertelt.',
  'De meeste mensen die ik ken, wonen in de stad.',
  'Het gaat om een bedrag dat we niet hebben.',
  'Een huis dat leeg staat, is zonde.',
  'Er was eens een meisje dat in het bos woonde.',
  'Wie het eerst komt, het eerst maalt.',
  'Dat is een groot verschil.',
  'Het is een mooi land.',
  'Dat was een leuk feest.',
  'Ik heb een nieuw huis gekocht.',
  'Een goed begin is het halve werk.',
  'De grote stad trekt veel mensen.',
  'Mijn oude fiets is gestolen.',
  'Het nieuwe jaar begint goed.',
  'Elk jaar gaan we op vakantie.',
  'Ieder kind is anders.',
  'Geen enkel probleem!',
  'Veel mensen werken thuis.',
  'Het is een heel groot huis.',
  'Het huis is groot.',
  'Dit is mijn huis.',
  'Ik woon in het oude centrum.',
  'Op het werk is het druk.',
  'Met het oog op de toekomst.',
  'In het algemeen gaat het goed.',
  'Na het eten gaan we wandelen.',
  'Voor het slapen lees ik.',
  'Bij het station staat een fiets.',
  'Door het raam zag ik de zon.',
  'Ik heb in het begin veel geleerd.',
  'Na de zomer begint de school weer.',
  'Hij heeft de hele dag gewerkt.',
  'De hele familie kwam.',
  'In de stad is het druk.',
  'Het nieuws van vandaag.',
  'Vandaag is het mooi weer.',
  'Morgen is er een feest.',
  'Daarna gingen we naar huis.',
  'Soms is het moeilijk.',
  'Misschien wordt het beter.',
  'Eigenlijk weet ik het niet.',
  'Natuurlijk weet ik dat.',
  'Helaas kan ik niet komen.',
  'Gelukkig is iedereen gezond.',
  'Hier is je jas.',
  'Dan zien we elkaar morgen.',
  'Dus jij bent de nieuwe collega?',
  'Hoe gaat het met je moeder?',
  'Wat doe je morgen?',
  'Wie is die man?',
  'Waar woon je?',
  'Wanneer kom je terug?',
  'Waarom ben je zo laat?',
  'Hoeveel kost dat?',
  'Welke kleur vind je mooi?',
  'Ik weet dat jij het weet.',
  'Ik hoop dat je snel beter wordt.',
  'Ik denk dat we morgen gaan.',
  'Als het morgen regent, blijven we thuis.',
  'Omdat het regende, bleven we thuis.',
  'Terwijl ik kookte, deed hij de afwas.',
  'Nadat we hadden gegeten, gingen we wandelen.',
  'Voordat je gaat, moet je je jas aantrekken.',
  'Zodra hij thuis is, bel ik je.',
  'Hoewel het koud was, gingen we zwemmen.',
  'Ik bleef thuis, want ik was ziek.',
  'Ik was ziek, dus ik bleef thuis.',
  'Ik wilde komen, maar ik kon niet.',
  'Wil je thee of koffie?',
  'Ik heb honger en dorst.',
  'Kom je morgen of overmorgen?',
  'Hij woont in Amsterdam en werkt in Utrecht.',
  'Ze lacht en zingt de hele dag.',
  'Het is koud en het regent.',
  'Ik ga ervan uit dat het lukt.',
  'Ik ben het ermee eens.',
  'Ik ben het daar volledig mee eens.',
  'Wij zijn het met elkaar eens.',
  'Ken jij die man?',
  'Kent u de weg?',
  'Ik ken de weg niet.',
  'Ik weet de weg niet.',
  'Wist je dat?',
  'Ik leg het boek op tafel.',
  'Zet de fiets maar in de schuur.',
  'Hij ligt in bed.',
  'Ik zit in de trein.',
  'Je mag gaan zitten.',
  'Hij is een heel goede vriend.',
  'Het was een hele klus.',
  'Een heel jaar lang.',
  'Het hele huis was leeg.',
  'Ik heb geen zin.',
  'Niet een, maar twee.',
  'Ik heb niets gezien.',
  'Niemand heeft het gedaan.',
  'Ik ben nooit in Parijs geweest.',
  'Hij heeft nooit geld.',
  'Het is vandaag maandag 5 mei.',
  'Op 5 mei vieren we de bevrijding.',
  'In de lente bloeien de bloemen.',
  'De herfst is mijn favoriete seizoen.',
  'Hij spreekt vloeiend Turks en Arabisch.',
  'Ze is Nederlandse.',
  'Wij zijn Marokkanen.',
  'Ik heb Engelse les.',
  'Het is half acht.',
  'Om kwart over negen.',
  'Hij is 1,80 meter lang.',
  'Ze woont op nummer 12.',
  'Het is 20 graden.',
  'Bel 112 bij nood.',
  'Lees hoofdstuk 3 en 4.',
  'Zie pagina 10.',
  'De trein van 8.15 uur.',
  'Hij won met 3-1.',
  'Het werd 2-2.',
  'Wat?! Echt waar?',
  'Nee... dat meen je niet!',
  'Ja, hoor.',
  'Oké, prima.',
  'Hmm, even denken.',
  'Haha, wat grappig.',
  'Tot ziens!',
  'Fijne dag!',
  'Succes morgen!',
  'Gefeliciteerd met je verjaardag!',
  'Beterschap!',
  'Dank je wel.',
  'Dank u wel.',
  'Graag gedaan.',
  'Alsjeblieft.',
  'Alstublieft.',
  'Sorry, ik ben te laat.',
  'Pardon, mag ik er even langs?',
  'Excuses voor het ongemak.',
]

const CORRECT = [...DICTEE, ...LISTEN, NEWS, CHAT, LEARNER, STORY, ...MIXED.split(/(?<=[.?!])\s+/), ...TRICKY, ...PARAGRAPHS, ...EVERYDAY]

describe('nl rules: zero false positives on correct Dutch', () => {
  const dict = nlDict()
  for (const strictness of ['normal', 'strict'] as const) {
    for (const withDict of [true, false]) {
      it(`${strictness}, ${withDict ? 'with' : 'without'} dictionary`, () => {
        const flagged: string[] = []
        for (const text of CORRECT) {
          for (const i of runRules(text, 'nl', nlRules, { strictness, dict: withDict ? dict : undefined })) {
            if (i.confidence === 'low') continue
            flagged.push(`[${i.ruleId}] "${i.text}" -> ${i.replacements[0] ?? ''}  in: ${text.slice(0, 80)}`)
          }
        }
        expect(flagged).toEqual([])
      })
    }
  }
})
