import { definePack } from './build'
import type { DrillPack } from './types'

// Arabic spelling: hamza at the start of a word, taa marbuta, alif maqsura.
// Unvoweled MSA, like everyday typing. Harakat are ignored when answers are checked.

const hamza = definePack({
  id: 'ar.hamza',
  lang: 'ar',
  title: 'أ / إ / ا',
  blurb: "Hamzat qat' or hamzat wasl at the start of a word.",
  rule: {
    en: "At the start of a word, a hamza you pronounce even in the middle of a sentence is hamzat al-qat': write أ with a or u, and إ with i: أحمد، أنا، إلى، إن. A hamza that disappears in connected speech is hamzat al-wasl, written as a bare ا: the article ال, nouns like ابن، اسم، امرأة, and the past tense, imperative and masdar of five- and six-letter verbs: استخدم، اجتماع، انتظار.\n\nThe trick: put و in front. If you still hear the hamza (وأحمد), write it. If it disappears (واستخدم), leave it out.",
    local: 'الهمزة في أول الكلمة نوعان. همزة القطع تُنطق دائما، حتى في وسط الكلام: تُكتب أ مع الفتحة أو الضمة، وإ مع الكسرة: أحمد، أنا، إلى، إن. همزة الوصل تسقط في درج الكلام وتُكتب ألفا بلا همزة (ا): ال التعريف، ابن، اسم، امرأة، وماضي الفعل الخماسي والسداسي وأمره ومصدره: استخدم، اجتماع، انتظار.\n\nالحيلة: ضع واوا قبل الكلمة. إذا بقيت الهمزة مسموعة (وأحمد) فاكتبها، وإذا سقطت (واستخدم) فلا تكتبها.',
  },
  hints: {
    qata: { en: "Hamzat qat' with a or u: write أ. You still hear it after و.", local: 'همزة قطع مفتوحة أو مضمومة: تُكتب أ. تبقى مسموعة بعد الواو.' },
    qati: { en: "Hamzat qat' with i: write إ, under the alif.", local: 'همزة قطع مكسورة: تُكتب إ تحت الألف.' },
    nouns: { en: 'ابن، ابنة، اسم، امرأة start with hamzat wasl: no hamza.', local: 'ابن وابنة واسم وامرأة تبدأ بهمزة وصل: لا تُكتب الهمزة.' },
    long: { en: 'Five- and six-letter verbs and their masdar start with hamzat wasl: استخدم، اجتماع.', local: 'الفعل الخماسي والسداسي ومصدره يبدأ بهمزة وصل: استخدم، اجتماع.' },
    form4: { en: "Four-letter verbs like أرسل take hamzat qat', and so does their masdar: إرسال.", local: 'الفعل الرباعي مثل أرسل همزته همزة قطع، وكذلك مصدره: إرسال.' },
    first: { en: "The I-form of the present starts with hamzat qat': أكتب، أذهب.", local: 'همزة المضارع للمتكلم همزة قطع: أكتب، أذهب.' },
    imper: { en: 'The imperative of a three-letter verb starts with hamzat wasl: اكتب.', local: 'أمر الفعل الثلاثي يبدأ بهمزة وصل: اكتب.' },
  },
  items: [
    ['ذهبت {{إلى|الى}} المدرسة.', 'qati'],
    ['{{أنا|انا}} من هولندا.', 'qata'],
    ['صديقي {{أحمد|احمد}} طبيب.', 'qata'],
    ['{{اسمي|إسمي}} سارة.', 'nouns'],
    ['هذا {{ابني|إبني}} الصغير.', 'nouns'],
    ['{{استخدمت|إستخدمت}} الحاسوب طوال اليوم.', 'long'],
    ['حضرت {{اجتماعا|إجتماعا}} مهما.', 'long'],
    ['{{أرسلت|ارسلت}} الرسالة أمس.', 'form4'],
    ['أريد {{إرسال|ارسال}} هذا الطرد.', 'form4'],
    ['أنا {{أكتب|اكتب}} رسالة الآن.', 'first'],
    ['{{اكتب|أكتب}} اسمك هنا من فضلك.', 'imper'],
    ['{{انتظرت|إنتظرت}} صديقي أمام المحطة.', 'long'],
    ['هل تعرف {{أين|اين}} المحطة؟', 'qata'],
    ['نلتقي غدا {{إن|ان}} شاء الله.', 'qati'],
    ['أريد {{أن|ان}} أتعلم الهولندية.', 'qata'],
    ['هذه {{امرأة|إمرأة}} لطيفة.', 'nouns'],
    ['هذا {{أفضل|افضل}} مطعم في المدينة.', 'qata'],
    ['{{أخي|اخي}} يعمل في أمستردام.', 'qata'],
    ['{{أمي|امي}} تطبخ أطيب طعام.', 'qata'],
    ['{{استمعت|إستمعت}} إلى الأخبار في الصباح.', 'long'],
    ['سافرنا إلى {{إسبانيا|اسبانيا}} في الصيف.', 'qati'],
    ['هذا {{الاختبار|الإختبار}} صعب.', 'long'],
    ['{{أكلت|اكلت}} تفاحة في الصباح.', 'qata'],
    ['هل تشرب الشاي {{أو|او}} القهوة؟', 'qata'],
    ['{{إذا|اذا}} تأخرت، اتصل بي.', 'qati'],
    ['{{الانتظار|الإنتظار}} ممل.', 'long'],
    ['{{أمس|امس}} ذهبت إلى السوق.', 'qata'],
    ['أريد {{إجابة|اجابة}} واضحة.', 'form4'],
    ['{{ابنتي|إبنتي}} في المدرسة الآن.', 'nouns'],
    ['{{استيقظت|إستيقظت}} مبكرا اليوم.', 'long'],
  ],
})

const taa = definePack({
  id: 'ar.taa',
  lang: 'ar',
  title: 'ة / ه',
  blurb: 'Taa marbuta or a real haa at the end of a word.',
  rule: {
    en: 'ة (taa marbuta) marks the feminine and many nouns: مدرسة، حديقة، سيارة. ه is a real h: part of the word itself (وجه، مياه) or the pronoun his (كتابه, his book).\n\nThe trick: add a suffix. If the ending turns into ت (مدرسة → مدرستي), write ة. If the h stays an h (وجه → وجهي), write ه. Or read on without a pause: ة sounds like t.',
    local: 'التاء المربوطة (ة) علامة التأنيث في كثير من الأسماء: مدرسة، حديقة، سيارة. أما الهاء (ه) فهي حرف من أصل الكلمة (وجه، مياه) أو ضمير الغائب (كتابه).\n\nالحيلة: أضف ضميرا إلى الكلمة. إذا صارت تاء مفتوحة (مدرسة ← مدرستي) فهي ة، وإذا بقيت هاء (وجه ← وجهي) فهي ه. أو صِل الكلمة بما بعدها: التاء المربوطة تُنطق تاء.',
  },
  hints: {
    fem: { en: 'Add a suffix and it turns into ت (مدرسة → مدرستي): write ة.', local: 'أضف ضميرا فتصير تاء مفتوحة (مدرسة ← مدرستي): اكتب ة.' },
    his: { en: 'The pronoun his (his book, his key): write ه.', local: 'ضمير الغائب (كتابه، مفتاحه): اكتب ه.' },
    root: { en: 'The h belongs to the word itself (فواكه، مياه، وجه): write ه.', local: 'الهاء من أصل الكلمة (فواكه، مياه، وجه): اكتب ه.' },
    tah: { en: 'ة becomes ت before a suffix, then the pronoun ه follows: غرفة → غرفته.', local: 'تصير ة تاء مفتوحة قبل الضمير، ثم تأتي الهاء: غرفة ← غرفته.' },
  },
  items: [
    ['هذه {{مدرسة|مدرسه}} كبيرة.', 'fem'],
    ['ذهبت إلى {{المدرسة|المدرسه}} مبكرا.', 'fem'],
    ['قرأ أخي {{كتابه|كتابة}} الجديد.', 'his'],
    ['{{كتابة|كتابه}} الرسائل تأخذ وقتا.', 'fem'],
    ['هذه {{حديقة|حديقه}} جميلة.', 'fem'],
    ['كان {{وجهه|وجهة}} أحمر من الشمس.', 'his'],
    ['أشرب كوبا من {{القهوة|القهوه}} كل صباح.', 'fem'],
    ['اشترت أختي {{سيارة|سياره}} جديدة.', 'fem'],
    ['أحب {{اللغة|اللغه}} العربية.', 'fem'],
    ['{{الفاكهة|الفاكهه}} مفيدة للصحة.', 'fem'],
    ['أحب أكل {{الفواكه|الفواكة}}.', 'root'],
    ['شربت كثيرا من {{المياه|المياة}}.', 'root'],
    ['{{الحياة|الحياه}} جميلة.', 'fem'],
    ['دخل أحمد {{غرفته|غرفتة}}.', 'tah'],
    ['هذه {{مدينة|مدينه}} قديمة.', 'fem'],
    ['{{الساعة|الساعه}} الآن الثالثة.', 'fem'],
    ['نسي {{مفتاحه|مفتاحة}} في البيت.', 'his'],
    ['ركبت {{الدراجة|الدراجه}} إلى العمل.', 'fem'],
    ['{{الجامعة|الجامعه}} قريبة من البيت.', 'fem'],
    ['سألت المعلم عن {{رأيه|رأية}}.', 'his'],
    ['أعمل في {{شركة|شركه}} كبيرة.', 'fem'],
    ['{{الرحلة|الرحله}} كانت طويلة.', 'fem'],
    ['{{الطاولة|الطاوله}} في وسط الغرفة.', 'fem'],
    ['هذا {{بيته|بيتة}} الجديد.', 'his'],
    ['{{القصة|القصه}} التي قرأتها جميلة.', 'fem'],
    ['ركب أخي {{سيارته|سيارتة}} وذهب.', 'tah'],
    ['أكلت {{تفاحة|تفاحه}} حمراء.', 'fem'],
    ['نظر إلى {{وجه|وجة}} أمه.', 'root'],
    ['اشتريت {{هدية|هديه}} لصديقي.', 'fem'],
    ['كتب الطالب اسمه في {{دفتره|دفترة}}.', 'his'],
  ],
})

const alifMaqsura = definePack({
  id: 'ar.alif-maqsura',
  lang: 'ar',
  title: 'ى / ي',
  blurb: 'Alif maqsura without dots, or a real yaa with two.',
  rule: {
    en: 'At the end of a word, a long a sound written with a yaa shape has no dots: ى (alif maqsura), as in على، إلى، حتى، مشى، مستشفى. A final ي with two dots is pronounced ii or y: في، الذي، التي، العربي.\n\nThe trick: listen to the last vowel. Long a? No dots. Long i? Two dots. Before a suffix ى becomes ي: على → عليه.',
    local: 'الألف المقصورة (ى) تُكتب بلا نقاط في آخر الكلمة وتُنطق ألفا: على، إلى، حتى، مشى، مستشفى. أما الياء (ي) فتُنطق ياء وتُكتب بنقطتين: في، الذي، التي، العربي.\n\nالحيلة: استمع إلى آخر صوت في الكلمة. إن كان ألفا فلا نقاط، وإن كان ياء فنقطتان. وقبل الضمير تصير ى ياء: على ← عليه.',
  },
  hints: {
    maq: { en: 'A long a sound at the end: ى, no dots.', local: 'صوت ألف في آخر الكلمة: ى بلا نقاط.' },
    yaa: { en: 'An ii or y sound at the end: ي, with two dots.', local: 'صوت ياء في آخر الكلمة: ي بنقطتين.' },
    suffix: { en: 'Before a suffix ى becomes ي: على → عليه. A dotless ى never sits inside a word.', local: 'قبل الضمير تصير ى ياء: على ← عليه. لا تأتي ى في وسط الكلمة.' },
    pasti: { en: 'Verbs like نسي and بقي end in a real ii sound (nasiya): ي.', local: 'أفعال مثل نسي وبقي تنتهي بياء حقيقية (نَسِيَ): ي.' },
  },
  items: [
    ['الكتاب {{على|علي}} الطاولة.', 'maq'],
    ['ذهبت {{إلى|إلي}} السوق.', 'maq'],
    ['{{في|فى}} البيت ثلاث غرف.', 'yaa'],
    ['{{مشى|مشي}} الولد إلى المدرسة.', 'maq'],
    ['هذا هو الطالب {{الذي|الذى}} فاز.', 'yaa'],
    ['{{متى|متي}} يبدأ الدرس؟', 'maq'],
    ['انتظرت {{حتى|حتي}} المساء.', 'maq'],
    ['ذهب جدي إلى {{المستشفى|المستشفي}}.', 'maq'],
    ['صديقي {{مصطفى|مصطفي}} طباخ ماهر.', 'maq'],
    ['أحب الطعام {{العربي|العربى}}.', 'yaa'],
    ['{{هي|هى}} طبيبة في المستشفى.', 'yaa'],
    ['{{اشترى|اشتري}} أبي سيارة جديدة.', 'maq'],
    ['أعطني الكتاب، فهو {{لي|لى}}.', 'yaa'],
    ['{{رأى|رأي}} أحمد صديقه في المقهى.', 'maq'],
    ['السلام {{عليكم|علىكم}}.', 'suffix'],
    ['هذه المدينة {{التي|التى}} ولدت فيها.', 'yaa'],
    ['اسمها {{ليلى|ليلي}}.', 'maq'],
    ['جلسنا في {{المقهى|المقهي}} ساعة كاملة.', 'maq'],
    ['هذه الرسالة {{إليك|إلىك}}.', 'suffix'],
    ['{{بقي|بقى}} أحمد في البيت.', 'pasti'],
    ['{{نسي|نسى}} أخي مفتاحه.', 'pasti'],
    ['في المرة {{الأخرى|الأخري}} سأصل مبكرا.', 'maq'],
    ['{{موسى|موسي}} يعمل مهندسا.', 'maq'],
    ['{{يمشي|يمشى}} جدي كل صباح.', 'yaa'],
    ['{{يبقى|يبقي}} الباب مفتوحا طوال اليوم.', 'maq'],
    ['{{عليه|علىه}} أن يدرس أكثر.', 'suffix'],
    ['أين {{كرسي|كرسى}}؟', 'yaa'],
    ['أكلنا {{حلوى|حلوي}} لذيذة.', 'maq'],
  ],
})

export const AR_PACKS: DrillPack[] = [hamza, taa, alifMaqsura]
