// Frequent Dutch misspellings that are not words (§6.8 plus common chat/learner slips).
// Every wrong form is checked to be absent from the Dutch word list in lexicon.test.ts.

export interface Misspelling {
  right: string
  /** short reason shown to the learner (English / Dutch) */
  why?: 'two-words' | 'trema' | 'apostrophe' | 'tussen-n' | 'double' | 'sound' | 'loan'
}

const m = (right: string, why?: Misspelling['why']): Misspelling => ({ right, why })

export const MISSPELLINGS: ReadonlyMap<string, Misspelling> = new Map(
  Object.entries({
    eigelijk: m('eigenlijk'),
    eigenlyk: m('eigenlijk', 'sound'),
    eigenlik: m('eigenlijk', 'sound'),
    eigenluk: m('eigenlijk', 'sound'),
    eigenlek: m('eigenlijk', 'sound'),
    eigelijks: m('eigenlijk'),
    uberhaupt: m('überhaupt', 'trema'),
    uberhaubt: m('überhaupt', 'trema'),
    überhaubt: m('überhaupt'),
    zowieso: m('sowieso'),
    sowiso: m('sowieso'),
    zowiezo: m('sowieso'),
    sowiezo: m('sowieso'),
    zoiezo: m('sowieso'),
    aleen: m('alleen', 'double'),
    interresant: m('interessant', 'double'),
    intressant: m('interessant'),
    interesant: m('interessant', 'double'),
    interressant: m('interessant', 'double'),
    geinteresseerd: m('geïnteresseerd', 'trema'),
    geintereseerd: m('geïnteresseerd', 'trema'),
    geïntereseerd: m('geïnteresseerd', 'double'),
    geinterreseerd: m('geïnteresseerd', 'trema'),
    mischien: m('misschien'),
    misschein: m('misschien'),
    misshien: m('misschien'),
    mishien: m('misschien'),
    accomodatie: m('accommodatie', 'double'),
    abbonement: m('abonnement', 'double'),
    abonnoment: m('abonnement'),
    abonement: m('abonnement', 'double'),
    aggressief: m('agressief', 'double'),
    aparaat: m('apparaat', 'double'),
    carriere: m('carrière'),
    entousiast: m('enthousiast'),
    enthousiasch: m('enthousiast'),
    onmiddelijk: m('onmiddellijk', 'double'),
    onmidellijk: m('onmiddellijk', 'double'),
    paralel: m('parallel', 'double'),
    heelemaal: m('helemaal'),
    helemal: m('helemaal'),
    ingewikkelt: m('ingewikkeld'),
    catagorie: m('categorie'),
    waarschijlijk: m('waarschijnlijk'),
    waarschijnlyk: m('waarschijnlijk', 'sound'),
    waarschijnlik: m('waarschijnlijk', 'sound'),
    natuurluk: m('natuurlijk', 'sound'),
    natuurlyk: m('natuurlijk', 'sound'),
    natuurlik: m('natuurlijk', 'sound'),
    natuurlek: m('natuurlijk', 'sound'),
    natuulijk: m('natuurlijk'),
    natuurijk: m('natuurlijk'),
    natuurlij: m('natuurlijk'),
    natuurlijkk: m('natuurlijk'),
    harstikke: m('hartstikke'),
    hardstikke: m('hartstikke'),
    sucses: m('succes'),
    sukses: m('succes'),
    succesvoll: m('succesvol'),
    sympatiek: m('sympathiek'),
    simpatiek: m('sympathiek'),
    vacantie: m('vakantie'),
    vakansie: m('vakantie'),
    namenlijk: m('namelijk'),
    nivo: m('niveau'),
    kado: m('cadeau'),
    cado: m('cadeau'),
    buro: m('bureau'),
    sinasappel: m('sinaasappel'),
    chagerijnig: m('chagrijnig'),
    pyama: m('pyjama'),
    efficient: m('efficiënt', 'trema'),
    financiëel: m('financieel', 'trema'),
    officiëel: m('officieel', 'trema'),
    adress: m('adres', 'double'),
    defenitief: m('definitief'),
    definitef: m('definitief'),
    uiteindlijk: m('uiteindelijk'),
    uiteindelyk: m('uiteindelijk', 'sound'),
    verantwoordlijk: m('verantwoordelijk'),
    gemakelijk: m('gemakkelijk', 'double'),
    makelijk: m('makkelijk', 'double'),
    gefeliciteert: m('gefeliciteerd'),
    gefeliciteerdt: m('gefeliciteerd'),
    asjeblieft: m('alsjeblieft'),
    asjeblief: m('alsjeblieft'),
    alstublief: m('alstublieft'),
    astublieft: m('alstublieft'),
    ideeen: m('ideeën', 'trema'),
    belgie: m('België', 'trema'),
    italie: m('Italië', 'trema'),
    australie: m('Australië', 'trema'),
    azie: m('Azië', 'trema'),
    israel: m('Israël', 'trema'),
    indonesie: m('Indonesië', 'trema'),
    tunesie: m('Tunesië', 'trema'),
    kopieren: m('kopiëren', 'trema'),
    knieen: m('knieën', 'trema'),
    zeeen: m('zeeën', 'trema'),
    naief: m('naïef', 'trema'),
    beinvloeden: m('beïnvloeden', 'trema'),
    egoist: m('egoïst', 'trema'),
    coordinatie: m('coördinatie', 'trema'),
    reunie: m('reünie', 'trema'),
    pannekoek: m('pannenkoek', 'tussen-n'),
    pannekoeken: m('pannenkoeken', 'tussen-n'),
    zonnenbloem: m('zonnebloem', 'tussen-n'),
    paddestoel: m('paddenstoel', 'tussen-n'),
    boekekast: m('boekenkast', 'tussen-n'),
    kippesoep: m('kippensoep', 'tussen-n'),
    hondehok: m('hondenhok', 'tussen-n'),
    ruggegraat: m('ruggengraat', 'tussen-n'),
    paardebloem: m('paardenbloem', 'tussen-n'),
    zielepiet: m('zielenpiet', 'tussen-n'),
    welliswaar: m('weliswaar', 'double'),
    allebij: m('allebei'),
    belangerijk: m('belangrijk'),
    belangrik: m('belangrijk', 'sound'),
    moelijk: m('moeilijk'),
    moeilik: m('moeilijk', 'sound'),
    moeilyk: m('moeilijk', 'sound'),
    gezelig: m('gezellig', 'double'),
    gezellich: m('gezellig', 'sound'),
    metteen: m('meteen', 'double'),
    presies: m('precies'),
    exuses: m('excuses'),
    bijvoorbeel: m('bijvoorbeeld'),
    bijvoorbeelt: m('bijvoorbeeld'),
    eindelik: m('eindelijk', 'sound'),
    eindelyk: m('eindelijk', 'sound'),
    verschrikelijk: m('verschrikkelijk', 'double'),
    vriendelik: m('vriendelijk', 'sound'),
    tegewoordig: m('tegenwoordig'),
    tegenwoordich: m('tegenwoordig', 'sound'),
    nieuwschierig: m('nieuwsgierig'),
    nieuwsgierich: m('nieuwsgierig', 'sound'),
    rustich: m('rustig', 'sound'),
    prachtich: m('prachtig', 'sound'),
    gelukkich: m('gelukkig', 'sound'),
    nodich: m('nodig', 'sound'),
    geweldich: m('geweldig', 'sound'),
    vervelent: m('vervelend'),
    spannent: m('spannend'),
    opzich: m('op zich', 'two-words'),
    nogsteeds: m('nog steeds', 'two-words'),
    vanalles: m('van alles', 'two-words'),
    inplaats: m('in plaats', 'two-words'),
    zometeen: m('zo meteen', 'two-words'),
    iedergeval: m('ieder geval', 'two-words'),
    iniedergeval: m('in ieder geval', 'two-words'),
    ookal: m('ook al', 'two-words'),
    ofzo: m('of zo', 'two-words'),
    inprincipe: m('in principe', 'two-words'),
    vanplan: m('van plan', 'two-words'),
    metname: m('met name', 'two-words'),
    nogniet: m('nog niet', 'two-words'),
    nogeens: m('nog eens', 'two-words'),
    zn: m("z'n", 'apostrophe'),
    mn: m("m'n", 'apostrophe'),
    savonds: m("'s avonds", 'apostrophe'),
    sochtends: m("'s ochtends", 'apostrophe'),
    smorgens: m("'s morgens", 'apostrophe'),
    smiddags: m("'s middags", 'apostrophe'),
    snachts: m("'s nachts", 'apostrophe'),
    "s'avonds": m("'s avonds", 'apostrophe'),
    "s'ochtends": m("'s ochtends", 'apostrophe'),
    "s'morgens": m("'s morgens", 'apostrophe'),
    "s'middags": m("'s middags", 'apostrophe'),
    "s'nachts": m("'s nachts", 'apostrophe'),
    "s'zomers": m("'s zomers", 'apostrophe'),
    "s'winters": m("'s winters", 'apostrophe'),
    "s'maandags": m("'s maandags", 'apostrophe'),
    "s'zondags": m("'s zondags", 'apostrophe'),
    "z'on": m("zo'n", 'apostrophe'),
  }),
)

/** multi-word misspellings (lowercase, single spaces) */
export const PHRASE_MISSPELLINGS: ReadonlyMap<string, string> = new Map(
  Object.entries({
    'zo wie zo': 'sowieso',
    'ten alle tijden': 'te allen tijde',
    'ten allen tijde': 'te allen tijde',
    'ten allen tijden': 'te allen tijde',
    'te alle tijden': 'te allen tijde',
    'te allen tijden': 'te allen tijde',
    's avonds': "'s avonds",
    's ochtends': "'s ochtends",
    's morgens': "'s morgens",
    's middags': "'s middags",
    's nachts': "'s nachts",
    'in iedergeval': 'in ieder geval',
  }),
)
