// Commonly misspelled English words: right form -> typical wrong forms (space separated).
// From docs/research/english-errors.md section 6 / english-rules-prototype/misspellings.json, cross-checked
// against codespell (CC BY-SA 3.0). Wrong forms that are real words (calender, lightening, therefor,
// copywrite, florescent) are left out on purpose: they need context. misspellings.test.ts checks that no
// wrong form is accepted by the en-US or en-GB Hunspell dictionaries.

const DATA: Record<string, string> = {
  absence: 'absense abscence',
  acceptable: 'acceptible',
  accidentally: 'accidentaly accidently',
  accommodate: 'accomodate acommodate',
  accommodation: 'accomodation',
  achieve: 'acheive',
  acknowledge: 'acknowlege',
  acquaintance: 'acquaintence',
  acquire: 'aquire adquire',
  across: 'accross',
  actually: 'actualy',
  address: 'adress',
  advertisement: 'advertisment',
  aggressive: 'agressive',
  almost: 'allmost',
  already: 'allready',
  amateur: 'amatuer',
  apparent: 'apparant apparrent',
  appearance: 'appearence',
  argument: 'arguement',
  assassination: 'assasination',
  basically: 'basicly basicaly',
  beautiful: 'beatiful beautifull',
  because: 'becouse becuase beacuse',
  beginning: 'begining',
  believe: 'beleive belive',
  bicycle: 'bycicle bicicle',
  business: 'buisness bussiness',
  category: 'catagory',
  cemetery: 'cemetary',
  changeable: 'changable',
  children: 'childs childeren',
  colleague: 'collegue',
  column: 'colum',
  coming: 'comming',
  committee: 'commitee comittee',
  completely: 'completly',
  conscience: 'concience',
  conscious: 'concious',
  convenient: 'convinient',
  curiosity: 'curiousity',
  definitely: 'definately definitly definatly',
  desperate: 'desparate',
  develop: 'develope',
  difference: 'diffrence',
  dilemma: 'dilemna',
  disappear: 'dissapear',
  disappoint: 'dissapoint',
  discipline: 'disipline',
  dumbbell: 'dumbell',
  embarrass: 'embarass',
  embarrassing: 'embarassing',
  environment: 'enviroment enviorment',
  especially: 'especialy',
  exaggerate: 'exagerate',
  excellent: 'excelent',
  exercise: 'excercise exercice',
  existence: 'existance',
  experience: 'experiance',
  familiar: 'familar',
  family: 'familly',
  fascinating: 'facinating',
  February: 'Febuary',
  finally: 'finaly',
  foreign: 'foriegn',
  forty: 'fourty',
  forward: 'foward',
  friend: 'freind',
  fulfil: 'fullfil',
  future: 'futur',
  government: 'goverment',
  grammar: 'grammer',
  grateful: 'greatful',
  guarantee: 'guarentee',
  guard: 'gaurd',
  happened: 'happend',
  harass: 'harrass',
  height: 'heigth heighth',
  hierarchy: 'heirarchy',
  holiday: 'holliday',
  humorous: 'humourous',
  hygiene: 'hygene',
  ignorance: 'ignorence',
  immediately: 'immediatly imediately',
  independent: 'independant',
  intelligence: 'inteligence',
  interested: 'intrested interessted',
  interesting: 'intresting interessting',
  interrupt: 'interupt',
  irrelevant: 'irrelevent',
  island: 'iland',
  knowledge: 'knowlege',
  language: 'langauge languge',
  library: 'libary',
  license: 'lisence',
  maintenance: 'maintainance maintenence',
  marriage: 'marrige',
  medieval: 'mideval',
  millennium: 'millenium',
  miniature: 'miniture',
  mischievous: 'mischievious',
  misspell: 'mispell',
  necessary: 'neccessary necessery neccesary',
  neighbour: 'neigbour nieghbour',
  noticeable: 'noticable',
  occasion: 'occassion ocasion',
  occasionally: 'occasionaly occassionally',
  occurred: 'occured',
  occurrence: 'occurence occurrance',
  official: 'offical',
  opportunity: 'oppurtunity oportunity',
  parallel: 'paralel parrallel',
  parliament: 'parliment',
  pastime: 'pasttime',
  people: 'peaple poeple',
  perseverance: 'perseverence',
  persistent: 'persistant',
  pharaoh: 'pharoah',
  piece: 'peice',
  pollution: 'polution',
  possession: 'posession',
  preferred: 'prefered',
  privilege: 'priviledge privelege',
  probably: 'probaly propably',
  professor: 'proffesor',
  pronunciation: 'pronounciation',
  publicly: 'publically',
  questionnaire: 'questionaire',
  really: 'realy',
  receipt: 'reciept',
  receive: 'recieve',
  recommend: 'reccomend recomend',
  referred: 'refered',
  relevant: 'relevent revelant',
  religious: 'religous',
  remember: 'remeber',
  repetition: 'repitition',
  restaurant: 'restaraunt resturant',
  rhythm: 'rythm',
  schedule: 'schedual',
  secretary: 'secratary',
  seize: 'sieze',
  sense: 'sence',
  separate: 'seperate',
  sergeant: 'sargent',
  similar: 'similiar',
  sincerely: 'sincerly',
  speech: 'speach',
  strength: 'strenght',
  success: 'succes sucess',
  successful: 'succesful sucessful successfull',
  supersede: 'supercede',
  surprise: 'suprise',
  tendency: 'tendancy',
  threshold: 'threshhold',
  tomorrow: 'tommorow tommorrow',
  tongue: 'tounge',
  truly: 'truely',
  twelfth: 'twelth',
  tyranny: 'tyrany',
  until: 'untill',
  unusual: 'unusal',
  vacuum: 'vaccuum vacume',
  vegetable: 'vegatable vegtable',
  vehicle: 'vehical',
  very: 'verry',
  weather: 'wheather waether',
  Wednesday: 'Wensday Wedensday',
  weird: 'wierd',
  which: 'wich whitch',
  writing: 'writting',
  written: 'writen',
}

/**
 * Short memory hooks shown with the fix. Dutch spellings bleed into English for a few of these
 * (succes, adres, interessant), so those notes say so.
 */
export const EN_MISSPELLING_NOTES: Readonly<Record<string, string>> = {
  accommodate: 'Big enough for two c’s and two m’s.',
  accommodation: 'Two c’s and two m’s, like accommodate.',
  address: 'Two d’s and two s’s. Dutch ‘adres’ has one of each, English doubles both.',
  argument: 'Argue drops its e: argument.',
  because: 'be + cause.',
  beginning: 'Double n before -ing: begin, beginning.',
  believe: 'i before e: believe, piece, friend.',
  business: 'busi + ness: the i comes from busy.',
  children: 'The plural of child is children. There is no ‘childs’.',
  definitely: 'It contains the word finite: defi-nite-ly.',
  disappear: 'dis + appear: one s, two p’s.',
  disappoint: 'dis + appoint: one s, two p’s.',
  embarrass: 'Two r’s and two s’s.',
  embarrassing: 'Two r’s and two s’s.',
  environment: 'environ + ment: keep the n.',
  February: 'Feb-ru-ary: there is an r after the b.',
  foreign: 'One of the words that break ‘i before e’.',
  friend: 'i before e: a friend to the end.',
  government: 'govern + ment: keep the n.',
  grammar: 'It ends in -ar, not -er.',
  interested: 'One s: interested. Dutch ‘geïnteresseerd’ doubles it, English does not.',
  interesting: 'One s: interesting. Dutch ‘interessant’ doubles it, English does not.',
  necessary: 'One collar, two sleeves: one c, two s’s.',
  occasion: 'Two c’s, one s.',
  occurred: 'Two c’s and two r’s.',
  occurrence: 'Two c’s, two r’s, and -ence at the end.',
  piece: 'A piece of pie: i before e.',
  receipt: 'i before e, except after c: receipt, receive.',
  receive: 'i before e, except after c: receive.',
  recommend: 'One c, two m’s: re + commend.',
  separate: 'There’s a rat in separate.',
  success: 'Two c’s and two s’s. Dutch ‘succes’ has one s at the end.',
  successful: 'success + ful: two c’s, two s’s, one l.',
  tomorrow: 'One m, two r’s.',
  until: 'One l at the end (but ‘till’ has two).',
  Wednesday: 'Say it slowly: Wed-nes-day.',
  weird: 'Weird is weird: e before i.',
  which: 'There is an h after the w: which.',
}

export interface EnMisspelling {
  /** the correct spelling */
  right: string
  /** a short memory hook, if we have one */
  note?: string
}

/** lowercase wrong form -> correct word */
export const EN_MISSPELLINGS: ReadonlyMap<string, EnMisspelling> = new Map(
  Object.entries(DATA).flatMap(([right, wrong]) =>
    wrong.split(' ').map((w): [string, EnMisspelling] => [w.toLowerCase(), { right, note: EN_MISSPELLING_NOTES[right] }]),
  ),
)
