// Correct English used as regression input: no rule may flag these (test data, not shipped).

/** The 55 dictation sentences from docs/research/english-errors.md section 7 (english-rules-prototype/dictation.mjs). */
export const DICTATION: string[] = [
  "It's raining, so the dog is hiding in its little house.",
  "You're going to love your new bike.",
  "They're sure their bags are over there by the door.",
  "My sister is taller than me, but then again, she is older.",
  "I should have called you before I left.",
  "My jeans are loose now, so I hope I do not lose them on the bus.",
  "The cold weather did not affect the result, but the new rule had a big effect.",
  "It took an hour to walk to a university near an old castle.",
  "Whose phone is ringing, and who's going to answer it?",
  "It is too late to buy two tickets for the concert.",
  "Everyone accepted the invitation except Tom.",
  "My teacher gave me good advice, and I advise you to listen to her too.",
  "I think I left my glasses at home, but I'm not sure.",
  "I definitely need a lot of time to separate the old receipts.",
  "The hotel can accommodate twelve guests, so a separate room is not necessary.",
  "I have lived in Utrecht since 2015.",
  "We have known each other for ten years.",
  "Can you lend me your pen? I will give it back after class.",
  "May I borrow your charger for a moment?",
  "My grandmother taught me how to bake bread.",
  "We took a lot of photos on the beach last weekend.",
  "Have you done your homework, or are you still making mistakes?",
  "What are you doing at the weekend?",
  "Could you give me some information about the trains to Amsterdam?",
  "I agree with you, but my brother doesn't agree with either of us.",
  "He goes to the gym every Monday and Thursday in January.",
  "My parents speak Dutch and Arabic, and I am learning English.",
  "This book is much better than the film.",
  "Most people in my class live near the station.",
  "I want to enjoy my whole life and live by the sea.",
  "We might possibly move next year, and eventually we want to buy a house.",
  "The current situation is difficult, but the actual problem is money.",
  "When do you usually go home after work?",
  "I don't like cold coffee, and he doesn't either.",
  "Please park the car near the big blue building.",
  "Peter put the paper bag on the back seat of the bus.",
  "My brother is a teacher, and my sister is an engineer.",
  "Life is short, so money is not the most important thing.",
  "She is very tired because she is very busy.",
  "Please fill the bin with paper and feel free to sit on the seat.",
  "When can I call you, and why are you late?",
  "I went to the market. I bought some fruit, and then I walked home.",
  "Wait, what is that? Hello, my name is Sara.",
  "We discussed the plan and explained it to our manager.",
  "She has been married to Omar for five years.",
  "Their colleagues were surprised by the beautiful weather on Wednesday.",
  "There are five of us, so we need a bigger table.",
  "In my opinion, the second option is better than the first.",
  "Whether we go or not depends on the weather.",
  "Which restaurant would you recommend for a business dinner?",
  "The babies were asleep, so we turned off the radios and put away the photos.",
  "The woman who lives next door is a nurse.",
  "I will definitely wait until tomorrow before I decide.",
  "She is interested in business, and her first shop was a big success.",
  "It was embarrassing because the mistake occurred twice.",
]

/** Correct American English paragraphs that walk close to the rules (its, than/then, since, a/an, capitals...). */
export const PARAGRAPHS_US: string[] = [
  `Last weekend my sister and I took the train to Amsterdam. It was colder than we expected, so we bought two cups of coffee and walked along the canals. Then we visited a museum that has its own garden. I think it's the best museum in the city, and its cafe is excellent. We have known each other for twenty years, and we still laugh at the same jokes.`,
  `I have worked at this company since 2019. My manager explained the new rules to me on Monday, and I agree with most of them. Whether we finish on time depends on the weather, because half of the team cycles to work. If the project costs more than we planned, we will discuss it with the client. Could you lend me your charger? Mine is at home.`,
  `In my opinion, the second plan is better than the first one. It is less expensive, and it gives us more time. Most people in our group prefer it, but a few of them would rather wait. Their main worry is the budget, and there is no easy answer to that. We should have asked them earlier.`,
  `My brother is an engineer and my mother is a teacher. They speak Arabic at home, but at work they use Dutch and English. When can I visit them? They are very busy in December, so I will go in January. An hour on the train is not too long, and I can read a book on the way.`,
  `Practicing every day helps more than one long session a week. If you make a mistake, slow down and type the word again. Don't worry about speed at first; accuracy comes first, and speed follows. After a month, you will notice that your fingers know where the keys are.`,
  `The dog was hiding under the table again. Nobody knew why, but everyone agreed it was funny. When the storm was over, it walked out slowly, looked at us, and went straight to its bowl. I laughed so hard that I almost dropped my phone.`,
  `Send the file to anna@example.com or visit www.example.org before 9 a.m. on Friday. The meeting is in room 4.12, and it should take an hour. If you can't come, tell me by Thursday and I'll move it to next week.`,
  `She doesn't eat meat, and he doesn't drink coffee, so we cooked rice with vegetables. It was too spicy for the kids, but the adults loved it. Who's bringing dessert, and whose car are we taking to the beach?`,
  `We were going to leave at six, but the train was late again. Their phones were dead, so they couldn't call us. By the time they arrived, it was too dark to walk, and we took a taxi instead. Nobody complained; we were just happy to be home.`,
  `The color of the new logo is a little too bright, and the center of the page looks empty. Could you analyze the feedback and organize a short meeting? I realized yesterday that we never finalized the plan.`,
  `A European student asked me for advice about learning Dutch. I advise everyone to read the news in Dutch every morning, even if they understand only half of it. It is a slow process, but it works, and it is a lot more fun than grammar drills.`,
]

/** Correct British English, checked with the en-GB dictionary. */
export const PARAGRAPHS_GB: string[] = [
  `Our neighbours organised a small party at the weekend. The colour of the sky changed as we travelled home, and the centre of town was quiet. I realised that I had left my umbrella at their flat, so I went back to get it.`,
  `The theatre was full, and the programme was longer than we had expected. We had a cup of tea in the interval and talked about our favourite plays.`,
]
