import { definePack } from '../build'

// Arabic hamza: qat' or wasl at the start of a word, the seat in the middle, and the end.
// Unvoweled MSA, like everyday typing. Harakat are ignored when answers are checked.

export const hamza = definePack({
  id: 'ar.hamza',
  lang: 'ar',
  title: 'أ / إ / ا',
  blurb: "Hamzat qat' or hamzat wasl at the start of a word.",
  rule: {
    en: "At the start of a word, a hamza you pronounce even in the middle of a sentence is hamzat al-qat': write أ with a or u, and إ with i: أحمد، أنا، إلى، إن. A hamza that disappears in connected speech is hamzat al-wasl, written as a bare ا: the article ال, nouns like ابن، اسم، امرأة, and the past tense, imperative and masdar of five- and six-letter verbs: استخدم، اجتماع، انتظار.\n\nThe trick: put و in front. If you still hear the hamza (وأحمد), write it. If it disappears (واستخدم), leave it out.",
    local: 'الهمزة في أول الكلمة نوعان. همزة القطع تنطق دائما، حتى في وسط الكلام: تكتب أ مع الفتحة أو الضمة، وإ مع الكسرة: أحمد، أنا، إلى، إن. وهمزة الوصل تسقط في درج الكلام وتكتب ألفا بلا همزة (ا): ال التعريف، وابن، واسم، وامرأة، وماضي الفعل الخماسي والسداسي وأمره ومصدره: استخدم، اجتماع، انتظار.\n\nالحيلة: ضع واوا قبل الكلمة. إذا بقيت الهمزة مسموعة (وأحمد) فاكتبها، وإذا سقطت (واستخدم) فلا تكتبها.',
  },
  hints: {
    qata: { en: "Hamzat qat' with a or u: write أ. You still hear it after و.", local: 'همزة قطع مفتوحة أو مضمومة: تكتب أ، وتبقى مسموعة بعد الواو.' },
    qati: { en: "Hamzat qat' with i: write إ, under the alif.", local: 'همزة قطع مكسورة: تكتب إ تحت الألف.' },
    nouns: { en: 'ابن، ابنة، اسم، امرأة start with hamzat wasl: no hamza.', local: 'ابن وابنة واسم وامرأة تبدأ بهمزة وصل: لا تكتب الهمزة.' },
    long: { en: 'Five- and six-letter verbs and their masdar start with hamzat wasl: استخدم، اجتماع.', local: 'الفعل الخماسي والسداسي ومصدرهما يبدأ بهمزة وصل: استخدم، اجتماع.' },
    form4: { en: "Four-letter verbs like أرسل take hamzat qat', and so does their masdar: إرسال.", local: 'الفعل الرباعي مثل أرسل همزته همزة قطع، وكذلك مصدره: إرسال.' },
    first: { en: "The I-form of the present starts with hamzat qat': أكتب، أذهب.", local: 'همزة المضارع للمتكلم همزة قطع: أكتب، أذهب.' },
    imper: { en: 'The imperative of a three-letter verb starts with hamzat wasl: اكتب.', local: 'أمر الفعل الثلاثي يبدأ بهمزة وصل: اكتب.' },
  },
  items: [
    ['ذهبت {{إلى|الى}} المدرسة.', 'qati'],
    ['{{أنا|انا}} من هولندا.', 'qata'],
    ['صديقي {{أحمد|احمد}} طبيب.', 'qata'],
    ['{{اسمي|إسمي}} سارة.', 'nouns'],
    ['هذا {{ابني|إبني}} الصغير.', 'nouns'],
    ['{{استخدمت|إستخدمت}} الحاسوب طوال اليوم.', 'long'],
    ['حضرت {{اجتماعا|إجتماعا}} مهما.', 'long'],
    ['{{أرسلت|ارسلت}} الرسالة أمس.', 'form4'],
    ['أريد {{إرسال|ارسال}} هذا الطرد.', 'form4'],
    ['أنا {{أكتب|اكتب}} رسالة الآن.', 'first'],
    ['{{اكتب|أكتب}} اسمك هنا من فضلك.', 'imper'],
    ['{{انتظرت|إنتظرت}} صديقي أمام المحطة.', 'long'],
    ['هل تعرف {{أين|اين}} المحطة؟', 'qata'],
    ['نلتقي غدا {{إن|ان}} شاء الله.', 'qati'],
    ['أريد {{أن|ان}} أتعلم الهولندية.', 'qata'],
    ['هذه {{امرأة|إمرأة}} لطيفة.', 'nouns'],
    ['هذا {{أفضل|افضل}} مطعم في المدينة.', 'qata'],
    ['{{أخي|اخي}} يعمل في أمستردام.', 'qata'],
    ['{{أمي|امي}} تطبخ أطيب طعام.', 'qata'],
    ['{{استمعت|إستمعت}} إلى الأخبار في الصباح.', 'long'],
    ['سافرنا إلى {{إسبانيا|اسبانيا}} في الصيف.', 'qati'],
    ['هذا {{الاختبار|الإختبار}} صعب.', 'long'],
    ['{{أكلت|اكلت}} تفاحة في الصباح.', 'qata'],
    ['هل تشرب الشاي {{أو|او}} القهوة؟', 'qata'],
    ['{{إذا|اذا}} تأخرت، اتصل بي.', 'qati'],
    ['{{الانتظار|الإنتظار}} ممل.', 'long'],
    ['{{أمس|امس}} ذهبت إلى السوق.', 'qata'],
    ['أريد {{إجابة|اجابة}} واضحة.', 'form4'],
    ['{{ابنتي|إبنتي}} في المدرسة الآن.', 'nouns'],
    ['{{استيقظت|إستيقظت}} مبكرا اليوم.', 'long'],
  ],
})

export const hamzaMid = definePack({
  id: 'ar.hamza-mid',
  lang: 'ar',
  title: 'سؤال / رئيس / سأل',
  blurb: 'The seat of a hamza in the middle of a word: ئ, ؤ or أ.',
  rule: {
    en: 'In the middle of a word, the hamza sits on the letter that matches the stronger of two vowels: its own and the one before it. Kasra (i) is strongest and puts it on a dotless ي (ئ), then damma (u) puts it on و (ؤ), then fatha (a) puts it on ا (أ). Sukun is weakest. So رئيس، بئر، أسئلة take ئ, سؤال، مؤتمر، رؤية take ؤ, and سأل، رأس، مسألة take أ.\n\nTwo special cases: a hamza with fatha after a long ā sits on the line (تساءل، قراءة), and after a ي with sukun it sits on a tooth (هيئة، بيئة). The trick: say the word slowly and listen around the hamza. Any i wins: ئ. No i but a u: ؤ. Only a: أ.',
    local: 'الهمزة المتوسطة تكتب على الحرف الذي يناسب أقوى الحركتين: حركتها وحركة الحرف الذي قبلها. أقوى الحركات الكسرة ويناسبها الياء (ئ)، ثم الضمة ويناسبها الواو (ؤ)، ثم الفتحة ويناسبها الألف (أ)، وأضعفها السكون. لذلك نكتب رئيس وبئر وأسئلة على الياء، وسؤال ومؤتمر ورؤية على الواو، وسأل ورأس ومسألة على الألف.\n\nوهناك حالتان خاصتان: إذا جاءت الهمزة مفتوحة بعد ألف المد كتبت على السطر (تساءل، قراءة)، وإذا جاءت مفتوحة بعد ياء ساكنة كتبت على نبرة (هيئة، بيئة). الحيلة: انطق الكلمة ببطء واستمع إلى الحركات حول الهمزة. إذا سمعت كسرة فاكتب ئ، وإذا لم تسمع كسرة وسمعت ضمة فاكتب ؤ، وإلا فاكتب أ.',
  },
  hints: {
    kasra: { en: 'The hamza or the letter before it has a kasra (i): write ئ.', local: 'الهمزة أو ما قبلها مكسور: اكتب ئ.' },
    damma: { en: 'A damma (u) and no kasra around the hamza: write ؤ.', local: 'حول الهمزة ضمة ولا كسرة: اكتب ؤ.' },
    fatha: { en: 'Only fatha or sukun around the hamza: write أ.', local: 'حول الهمزة فتحة أو سكون فقط: اكتب أ.' },
    line: { en: 'A hamza with fatha after a long ā sits on the line: ء.', local: 'الهمزة المفتوحة بعد ألف المد تكتب على السطر: ء.' },
    yaa: { en: 'A hamza with fatha after ي with sukun sits on a tooth: ئ.', local: 'الهمزة المفتوحة بعد ياء ساكنة تكتب على نبرة: ئ.' },
    masuul: { en: 'Damma on the hamza after a sukun: ؤ. مسئول is an older Egyptian habit.', local: 'همزة مضمومة بعد سكون: ؤ. أما مسئول فعادة مصرية قديمة.' },
  },
  items: [
    ['سألني المعلم {{سؤالا|سوالا|سئالا}} صعبا.', 'damma'],
    ['هذا {{رئيس|رأيس|ريس}} الشركة الجديد.', 'kasra'],
    ['شربنا الماء من {{بئر|بأر|بير}} قديمة.', 'kasra'],
    ['حضر أبي {{مؤتمرا|مأتمرا|موتمرا}} في باريس.', 'damma'],
    ['{{سأل|سال}} أحمد البائع عن السعر.', 'fatha'],
    ['وضعت القبعة على {{رأسي|رئسي|راسي}}.', 'fatha'],
    ['ما رأيك في هذه {{المسألة|المسئلة|المسالة}}؟', 'fatha'],
    ['أنا {{متفائل|متفأل|متفاءل}} بالمستقبل.', 'kasra'],
    ['يملأ {{التفاؤل|التفائل|التفاءل}} قلبها.', 'damma'],
    ['{{تساءل|تسائل}} الطفل عن سبب المطر.', 'line'],
    ['أحب {{قراءة|قرائة|قراأة}} الروايات قبل النوم.', 'line'],
    ['نحتاج إلى {{هيئة|هيأة}} مستقلة للانتخابات.', 'yaa'],
    ['يجب أن نحافظ على {{البيئة|البيأة}}.', 'yaa'],
    ['في الامتحان عشرة {{أسئلة|أسألة}}.', 'kasra'],
    ['{{رأيت|رئيت|ريت}} صديقي في السوق أمس.', 'fatha'],
    ['هذا {{الفأر|الفئر|الفار}} صغير جدا.', 'fatha'],
    ['تعمل أختي في {{مؤسسة|مأسسة|موسسة}} خيرية.', 'damma'],
    ['{{يسأل|يسئل|يسال}} الطلاب أسئلة كثيرة.', 'fatha'],
    ['حصل {{المؤلف|المألف|المولف}} على جائزة عن روايته.', 'damma'],
    ['كانت {{الرؤية|الرئية|الروية}} واضحة بعد المطر.', 'damma'],
    ['كان {{السائق|السأق|الساءق}} ينتظرنا أمام الفندق.', 'kasra'],
    ['وصلتني {{رسائل|رسأل|رساءل}} كثيرة اليوم.', 'kasra'],
    ['هل أنت {{مسؤول|مسئول|مسأول}} عن هذا القسم؟', 'masuul'],
    ['وزعت المدرسة {{الجوائز|الجوأز|الجواءز}} على الفائزين.', 'kasra'],
    ['أبي {{يؤمن|يومن|يئمن}} بأن الصبر مفتاح الفرج.', 'damma'],
    ['لا {{بأس|بئس|باس}}، سأنتظرك.', 'fatha'],
    ['ركبنا {{الطائرة|الطأرة|الطاءرة}} إلى عمان.', 'kasra'],
    ['جلست بين {{أصدقائي|أصدقاءي|أصدقاؤي}} في الحفلة.', 'kasra'],
    ['وصل {{أصدقاؤنا|أصدقائنا|أصدقاءنا}} في الموعد.', 'damma'],
    ['هذه {{مكافأة|مكافئة|مكافاة}} على جهدك.', 'fatha'],
  ],
})

export const hamzaEnd = definePack({
  id: 'ar.hamza-end',
  lang: 'ar',
  title: 'شيء / شاطئ / بدأ',
  blurb: 'A hamza at the end of a word: only the letter before it counts.',
  rule: {
    en: 'At the end of a word, only the letter before the hamza counts. After a fatha write أ (بدأ، قرأ، ملجأ), after a damma ؤ (تباطؤ، لؤلؤ), after a kasra ئ (شاطئ، هادئ، مبادئ). After a sukun or a long vowel (ا، و، ي) the hamza sits alone on the line: جزء، ضوء، شيء، بطيء، هدوء، سماء.\n\nThe trick: look only at the letter before. A long vowel or a consonant with no vowel? Then ء on the line: شيء, never شئ or شيئ. Older print wrote ئ as ىء (شاطىء); today it is ئ. One catch: once the alif of tanween or a suffix follows, the hamza is no longer at the end and can join the letter before it: شيء, but شيئا.',
    local: 'الهمزة المتطرفة في آخر الكلمة لا ينظر فيها إلا إلى حركة الحرف الذي قبلها. بعد الفتحة تكتب على الألف (بدأ، قرأ، ملجأ)، وبعد الضمة على الواو (تباطؤ، لؤلؤ)، وبعد الكسرة على الياء (شاطئ، هادئ، مبادئ). وبعد السكون أو حرف المد (ا، و، ي) تكتب مفردة على السطر: جزء، ضوء، شيء، بطيء، هدوء، سماء.\n\nالحيلة: انظر إلى الحرف الذي قبل الهمزة فقط. إذا كان حرف مد أو حرفا ساكنا فالهمزة على السطر: شيء، لا شئ ولا شيئ. وكانت الطباعة القديمة تكتب ئ بصورة ىء (شاطىء)، والصواب اليوم ئ. وانتبه: إذا جاءت بعدها ألف التنوين أو ضمير لم تعد الهمزة متطرفة، فقد تتصل بما قبلها على نبرة: شيء، لكن شيئا.',
  },
  hints: {
    fatha: { en: 'Fatha before the hamza: write أ.', local: 'قبل الهمزة فتحة: اكتب أ.' },
    damma: { en: 'Damma before the hamza: write ؤ.', local: 'قبل الهمزة ضمة: اكتب ؤ.' },
    kasra: { en: 'Kasra before the hamza: write ئ, not the old ىء.', local: 'قبل الهمزة كسرة: اكتب ئ، لا ىء القديمة.' },
    line: { en: 'A long vowel or sukun before the hamza: ء alone on the line.', local: 'قبل الهمزة حرف مد أو سكون: اكتب ء مفردة على السطر.' },
    tanween: { en: 'The alif of tanween follows and ي joins, so the hamza moves onto a tooth: شيئا، مليئا.', local: 'جاءت بعدها ألف التنوين والياء تتصل بما بعدها، فتكتب الهمزة على نبرة: شيئا، مليئا.' },
  },
  items: [
    ['لا أعرف أي {{شيء|شئ|شيئ}} عن الموضوع.', 'line'],
    ['هل تريد {{شيئا|شيءا|شيأ}} من السوق؟', 'tanween'],
    ['جلسنا على {{شاطئ|شاطيء|شاطء}} البحر.', 'kasra'],
    ['{{بدأ|بدء|بداء}} الدرس في الساعة التاسعة.', 'fatha'],
    ['أحب {{الهدوء|الهدوئ|الهدؤ}} في الصباح الباكر.', 'line'],
    ['السلحفاة حيوان {{بطيء|بطيئ|بطئ}}.', 'line'],
    ['{{قرأ|قرء|قرا}} أخي القصة مرتين.', 'fatha'],
    ['هذا {{جزء|جزئ|جزأ}} من المشكلة.', 'line'],
    ['أطفئ {{الضوء|الضوئ|الضؤ}} قبل النوم.', 'line'],
    ['الماء {{دافئ|دافيء|دافء}} اليوم.', 'kasra'],
    ['المتهم {{بريء|برئ|بريئ}} حتى تثبت إدانته.', 'line'],
    ['الحرية من أهم {{مبادئ|مبادىء|مبادء}} الديمقراطية.', 'kasra'],
    ['اتصلنا بقسم {{الطوارئ|الطوارىء|الطوارء}} فورا.', 'kasra'],
    ['البحر {{هادئ|هاديء|هادء}} هذا الصباح.', 'kasra'],
    ['{{نشأ|نشئ|نشا}} جدي في قرية صغيرة.', 'fatha'],
    ['وجدنا {{ملجأ|ملجئ|ملجا}} من المطر تحت الجسر.', 'fatha'],
    ['كل {{لاجئ|لاجيء|لاجء}} يحلم بالعودة إلى وطنه.', 'kasra'],
    ['شربت كوبا من {{الماء|المائ|الماأ}} البارد.', 'line'],
    ['نظرت إلى {{السماء|السمائ|السماأ}} طويلا.', 'line'],
    ['{{يقرأ|يقرئ|يقرا}} جدي الجريدة كل صباح.', 'fatha'],
    ['لاحظ الخبراء {{تباطؤ|تباطئ|تباطء}} الاقتصاد هذا العام.', 'damma'],
    ['هذا العقد من {{اللؤلؤ|اللؤلئ|اللولو}} الطبيعي.', 'damma'],
    ['صديقي {{قارئ|قاريء|قارء}} نهم للروايات.', 'kasra'],
    ['نلتقي {{مساء|مسائ|مساأ}} الخميس.', 'line'],
    ['كان الطريق {{مليئا|مليءا|مليأ}} بالسيارات.', 'tanween'],
    ['يجب أن {{نبدأ|نبدء|نبدا}} الآن.', 'fatha'],
    ['أشعر {{بالدفء|بالدفئ|بالدفأ}} قرب المدفأة.', 'line'],
    ['{{أخطأ|أخطء|أخطا}} اللاعب في التمرير.', 'fatha'],
  ],
})
