import { definePack } from '../build'

// Arabic spellings that do not follow the sound: the hidden alif, the silent ل of ال,
// and a review pack of the words that go wrong most often online.

export const hiddenAlif = definePack({
  id: 'ar.hidden-alif',
  lang: 'ar',
  title: 'هذا / لكن',
  blurb: 'Words you say with a long a but write without the alif.',
  rule: {
    en: 'A handful of very common words are said with a long ā that the spelling leaves out: هذا، هذه، هذان، ذلك، هكذا، لكن، هؤلاء، أولئك, and the religious words الله، الرحمن، إله. Fully vowelled texts mark the sound with a small dagger alif above the letter; normal typing simply leaves it out.\n\nThere is nothing to work out here: it is a short, closed list. Learn it once and trust it. هاذا، ذالك and لاكن are never right.',
    local: 'بعض الكلمات الشائعة جدا تنطق فيها ألف لا تكتب: هذا، هذه، هذان، ذلك، هكذا، لكن، هؤلاء، أولئك، ومن الألفاظ الدينية: الله، الرحمن، إله. وفي النصوص المشكولة ترسم فوق الحرف ألف صغيرة تدل على هذا الصوت، أما في الكتابة العادية فلا تظهر.\n\nلا قاعدة تستنتج هنا، بل قائمة قصيرة محدودة. احفظها مرة واحدة وثق بها: هاذا وذالك ولاكن ليست صحيحة أبدا.',
  },
  hints: {
    this: { en: 'هذا، هذه، هذان: said with ā, written without the alif.', local: 'هذا وهذه وهذان: تنطق الألف ولا تكتب.' },
    that: { en: 'ذلك and لذلك: no alif after ذ.', local: 'ذلك ولذلك: لا ألف بعد الذال.' },
    but: { en: 'لكن keeps its short spelling, also with a suffix: لكنه، لكنني.', local: 'لكن تبقى بلا ألف، حتى مع الضمير: لكنه، لكنني.' },
    these: { en: 'هؤلاء and أولئك: no alif in the middle.', local: 'هؤلاء وأولئك: لا ألف في وسطهما.' },
    thus: { en: 'هكذا: no alif after ه.', local: 'هكذا: لا ألف بعد الهاء.' },
    god: { en: 'الله and الرحمن are written without the alif you hear.', local: 'الله والرحمن تكتبان بلا الألف المنطوقة.' },
  },
  items: [
    ['{{هذا|هاذا}} بيتي الجديد.', 'this'],
    ['{{هذه|هاذه}} أختي الصغيرة.', 'this'],
    ['لم أسمع عن {{ذلك|ذالك}} من قبل.', 'that'],
    ['أحب الشاي، {{لكن|لاكن}} أخي يحب القهوة.', 'but'],
    ['لماذا تتكلم {{هكذا|هاكذا}}؟', 'thus'],
    ['{{هؤلاء|هاؤلاء|هاولاء}} طلاب جدد في صفنا.', 'these'],
    ['من {{أولئك|أولائك}} الرجال عند الباب؟', 'these'],
    ['الحمد {{لله|للاه}} على السلامة.', 'god'],
    ['بسم {{الله|اللاه}} نبدأ.', 'god'],
    ['بسم الله {{الرحمن|الرحمان}} الرحيم.', 'god'],
    ['كان الجو باردا، {{لكن|لاكن}} الشمس كانت مشرقة.', 'but'],
    ['{{ذلك|ذالك}} الرجل جاري.', 'that'],
    ['{{لذلك|لذالك}} قررت أن أبقى في البيت.', 'that'],
    ['{{هذان|هاذان}} الكتابان لي.', 'this'],
    ['ما رأيك في {{هذه|هاذه}} الفكرة؟', 'this'],
    ['كتب {{هؤلاء|هاؤلاء}} الطلاب قصصا جميلة.', 'these'],
    ['ماذا حدث بعد {{ذلك|ذالك}}؟', 'that'],
    ['{{هكذا|هاكذا}} تعلمت السباحة.', 'thus'],
    ['الطقس جميل، {{لكنني|لاكنني}} مشغول اليوم.', 'but'],
    ['هل {{هذا|هاذا}} مقعدك؟', 'this'],
    ['في {{ذلك|ذالك}} اليوم ضحكنا كثيرا.', 'that'],
    ['اتصلت به مرتين، {{لكنه|لاكنه}} لم يجب.', 'but'],
    ['{{هذه|هاذه}} أول مرة أزور فيها مصر.', 'this'],
    ['إلى أين يذهب {{أولئك|أولائك}} الأطفال؟', 'these'],
    ['السلام عليكم ورحمة {{الله|اللاه}}.', 'god'],
    ['لا تفعل {{هكذا|هاكذا}} مرة أخرى.', 'thus'],
  ],
})

export const lamShamsiyya = definePack({
  id: 'ar.lam-shamsiyya',
  lang: 'ar',
  title: 'الشمس / الليل',
  blurb: 'The ل of ال is always written, even when you do not hear it.',
  rule: {
    en: 'The article ال is written the same way before every letter. Before the moon letters you hear the ل: القمر، الكتاب. Before the sun letters (ت ث د ذ ر ز س ش ص ض ط ظ ل ن) it melts into the next letter, which you hear twice: الشمس is said ash-shams. Write the ل anyway. A noun that starts with ل keeps both: الليل، اللغة، الليمون.\n\nThe relative pronouns الذي، التي، الذين take a single ل; only the duals اللذان and اللتان have two. After the preposition لـ the alif of ال drops: للطلاب. The trick: cover the ال with a finger. What is left must be the whole word: الشمس → شمس.',
    local: 'تكتب «ال» التعريف دائما بالطريقة نفسها. قبل الحروف القمرية تنطق اللام: القمر، الكتاب. وقبل الحروف الشمسية (ت ث د ذ ر ز س ش ص ض ط ظ ل ن) تدغم اللام في الحرف الذي بعدها فينطق مشددا: في الشمس نسمع شينا مشددة ولا نسمع اللام. ومع ذلك تكتب اللام. والاسم الذي يبدأ بلام يحتفظ باللامين: الليل، اللغة، الليمون.\n\nأما الأسماء الموصولة الذي والتي والذين فتكتب بلام واحدة، ولا تكتب بلامين إلا في المثنى: اللذان واللتان. وبعد اللام الجارة تحذف ألف «ال»: للطلاب. الحيلة: احجب «ال» بإصبعك، فيجب أن يبقى الاسم كاملا: الشمس ← شمس.',
  },
  hints: {
    sun: { en: 'A sun letter: you do not hear the ل, but you write it.', local: 'حرف شمسي: اللام لا تنطق لكنها تكتب.' },
    lam: { en: 'The word itself starts with ل, so ال + ل gives two: الليل.', local: 'الكلمة نفسها تبدأ بلام، فتجتمع لامان: الليل.' },
    rel: { en: 'الذي، التي، الذين are written with one ل.', local: 'الذي والتي والذين تكتب بلام واحدة.' },
    dual: { en: 'The duals اللذان and اللتان are written with two.', local: 'المثنى اللذان واللتان يكتب بلامين.' },
    li: { en: 'After لـ the alif of ال drops: لـ + الطلاب = للطلاب.', local: 'بعد اللام الجارة تحذف ألف «ال»: لـ + الطلاب = للطلاب.' },
  },
  items: [
    ['تشرق {{الشمس|اشمس}} في الصباح.', 'sun'],
    ['لا أشرب القهوة في {{الليل|اليل}}.', 'lam'],
    ['أحب {{اللغة|الغة}} العربية كثيرا.', 'lam'],
    ['هل رأيت {{النجوم|انجوم}} الليلة؟', 'sun'],
    ['نسيت {{الساعة|اساعة}} في البيت.', 'sun'],
    ['هذا هو الكتاب {{الذي|اللذي}} أبحث عنه.', 'rel'],
    ['المدينة {{التي|اللتي}} أحبها هي القاهرة.', 'rel'],
    ['شكرا {{للطلاب|لالطلاب}} على مشاركتهم.', 'li'],
    ['أضف قليلا من الملح {{للحم|لللحم|لالحم}}.', 'li'],
    ['{{الطقس|اطقس}} جميل اليوم.', 'sun'],
    ['اشتريت {{الزيت|ازيت}} والسكر من السوق.', 'sun'],
    ['جلسنا في {{الظل|اظل}} حتى العصر.', 'sun'],
    ['{{الدرس|ادرس}} الأول سهل.', 'sun'],
    ['فتحت {{النافذة|انافذة}} لأن الجو حار.', 'sun'],
    ['أحب {{الصيف|اصيف}} أكثر من الشتاء.', 'sun'],
    ['هذا هو {{الرجل|ارجل}} الذي ساعدني.', 'sun'],
    ['{{الثلاثاء|اثلاثاء}} يوم عطلتي.', 'sun'],
    ['وضعت {{الصحون|اصحون}} في الخزانة.', 'sun'],
    ['هؤلاء هم {{الذين|اللذين}} ساعدوا جدي.', 'rel'],
    ['الطالبان {{اللذان|الذان}} فازا من صفي.', 'dual'],
    ['{{الضيوف|اضيوف}} في غرفة الجلوس.', 'sun'],
    ['قرأت {{التعليمات|اتعليمات}} بعناية.', 'sun'],
    ['أين {{السيارة|اسيارة}}؟', 'sun'],
    ['أعطني {{الليمون|اليمون}} من فضلك.', 'lam'],
    ['اشتريت {{اللحم|الحم}} من الجزار.', 'lam'],
    ['البنتان {{اللتان|التان}} تغنيان أختاي.', 'dual'],
    ['{{الذهب|اذهب}} أغلى من الفضة.', 'sun'],
    ['نزلنا إلى {{الشارع|اشارع}} بعد المطر.', 'sun'],
    ['هذا {{النهر|انهر}} طويل جدا.', 'sun'],
  ],
})

export const common = definePack({
  id: 'ar.common',
  lang: 'ar',
  title: 'الآن / لأن / إن شاء الله',
  blurb: 'The everyday words that go wrong most often, from every pack in one round.',
  rule: {
    en: "These are the words that go wrong most often in everyday Arabic writing, a mix from every other pack. إن شاء الله is three words: إنشاء means creating. ما شاء الله is three words too, and بإذن الله keeps its hamza under the alif.\n\nThe most common slip is a dropped hamzat al-qat': أكثر، الأطفال، الأخبار، أول، أريد all keep their أ. آ is a hamza followed by a long ā: الآن، آسف، آخر. And dialect sounds creep in: كتير and تلاتة are the spoken forms of كثير and ثلاثة.",
    local: 'هذه الكلمات هي الأكثر خطأ في الكتابة العربية اليومية، وتجمع أخطاء من كل المجموعات الأخرى. «إن شاء الله» ثلاث كلمات، أما «إنشاء» فمعناها الخلق والبناء. و«ما شاء الله» ثلاث كلمات أيضا، و«بإذن الله» تبقى همزتها تحت الألف.\n\nوأكثر الأخطاء شيوعا نسيان همزة القطع: أكثر، الأطفال، الأخبار، أول، أريد كلها بهمزة. والمدة (آ) همزة بعدها ألف مد: الآن، آسف، آخر. وتتسلل أصوات اللهجات أيضا: كتير وتلاتة نطق عامي لكثير وثلاثة.',
  },
  hints: {
    split: { en: 'Three separate words: إن شاء الله. إنشاء means creating.', local: 'ثلاث كلمات منفصلة: إن شاء الله. أما إنشاء فمعناها الخلق.' },
    masha: { en: 'Three separate words: ما شاء الله.', local: 'ثلاث كلمات منفصلة: ما شاء الله.' },
    idhn: { en: 'بـ + إذن: the hamza stays under the alif. بإذن الله.', local: 'الباء ثم إذن: تبقى الهمزة تحت الألف. بإذن الله.' },
    madda: { en: 'A hamza followed by a long ā is written آ.', local: 'الهمزة التي بعدها ألف مد تكتب آ.' },
    qat: { en: "Hamzat al-qat': the hamza stays, also after ال or a prefix.", local: 'همزة قطع: تبقى الهمزة، حتى بعد ال أو حرف متصل.' },
    ila: { en: 'إلى: a hamza under the alif, and a dotless ى at the end.', local: 'إلى: همزة تحت الألف، وألف مقصورة في آخرها.' },
    wasl: { en: 'Hamzat al-wasl: no hamza on the alif.', local: 'همزة وصل: لا همزة على الألف.' },
    end: { en: 'After a long vowel the final hamza sits alone on the line: شيء.', local: 'بعد حرف المد تكتب الهمزة المتطرفة على السطر: شيء.' },
    seat: { en: 'A hamza with damma after a sukun sits on و: سؤال، مسؤول، الشؤون.', local: 'الهمزة المضمومة بعد سكون تكتب على الواو: سؤال، مسؤول، الشؤون.' },
    fatha: { en: 'Only fatha around the hamza: it sits on the alif. متأكد، مسألة.', local: 'حول الهمزة فتحة فقط: تكتب على الألف. متأكد، مسألة.' },
    dialect: { en: 'The spoken t is a ث in writing: كثير، ثلاثة.', local: 'التاء المنطوقة في العامية ثاء في الكتابة: كثير، ثلاثة.' },
    taa: { en: 'The feminine ending is ة, not ه.', local: 'علامة التأنيث تاء مربوطة لا هاء.' },
  },
  items: [
    ['سأزورك يوم الجمعة {{إن شاء|إنشاء}} الله.', 'split'],
    ['{{ما شاء|ماشاء}} الله، بيتك جميل جدا.', 'masha'],
    ['سننجح {{بإذن|بأذن|باذن}} الله.', 'idhn'],
    ['أين أنت {{الآن|الان|الأن}}؟', 'madda'],
    ['بقيت في البيت {{لأن|لان}} الجو بارد.', 'qat'],
    ['هل تحتاج إلى {{شيء|شئ|شيئ}}؟', 'end'],
    ['من {{المسؤول|المسئول|المسأول}} عن هذا الخطأ؟', 'seat'],
    ['أحب الشاي {{أكثر|اكثر}} من القهوة.', 'qat'],
    ['{{إلى|الى|إلي}} اللقاء يا أصدقائي.', 'ila'],
    ['عندي {{سؤال|سوال}} صغير.', 'seat'],
    ['أنا {{متأكد|متاكد|متئكد}} من ذلك.', 'fatha'],
    ['{{كثير|كتير}} من الناس يحبون الشاي.', 'dialect'],
    ['عندي {{ثلاثة|تلاتة}} إخوة.', 'dialect'],
    ['يعمل في المكتب {{اثنان|إثنان}} فقط.', 'wasl'],
    ['هذه {{مسألة|مسئلة|مسالة}} صعبة.', 'fatha'],
    ['يعمل أبي في وزارة {{الشؤون|الشئون}} الخارجية.', 'seat'],
    ['لم آت {{لأنني|لانني}} كنت مريضا.', 'qat'],
    ['أين الكتاب {{الآخر|الأخر|الاخر}}؟', 'madda'],
    ['هذا {{آخر|أخر|اخر}} يوم في العطلة.', 'madda'],
    ['{{آسف|أسف|اسف}}، لم أقصد ذلك.', 'madda'],
    ['{{أريد|اريد}} كوبا من الشاي.', 'qat'],
    ['كل {{إنسان|انسان}} يخطئ.', 'qat'],
    ['نجحت في {{الامتحان|الإمتحان}}.', 'wasl'],
    ['أتكلم {{الإنجليزية|الانجليزية}} والهولندية.', 'qat'],
    ['مع {{السلامة|السلامه}}، نراك غدا.', 'taa'],
    ['يلعب {{الأطفال|الاطفال}} في الحديقة.', 'qat'],
    ['هل سمعت {{الأخبار|الاخبار}} اليوم؟', 'qat'],
    ['هذه {{أول|اول}} مرة أزور فيها المغرب.', 'qat'],
  ],
})
