// Correct Dutch in many registers, written for the false-positive hunt. Every sentence here must come
// out of the full free-writing pipeline (rules + Hunspell) without a high or medium flag.
// Grouped by register so a failure says what kind of writing broke.

export const CORRECT_NL: Record<string, string[]> = {
  chat: [
    'Hoi Sanne, ben je er al? Ik sta bij spoor 5.',
    'Top, dank je! Ik zie je om 8 uur bij het station.',
    'Haha, nee joh, dat was Daan, niet ik.',
    'Heb je de foto’s van zaterdag al gezien?',
    'Kun je even bellen als je klaar bent?',
    'Ik ben er over tien minuten, de trein had vertraging.',
    'Oké, dan neem ik de bus van 17.42 uur.',
    'Yusra komt ook, ze neemt haar broertje mee.',
    'Wat vind jij, pizza of sushi?',
    'Vind je het goed als ik later kom?',
    'Hou je van Indiaas eten? Dan weet ik een leuk adres.',
    'Ik hou het kort: ik kan morgen niet.',
    'Word je morgen opgehaald of kom je met de fiets?',
    'Wordt je broer ook opgehaald?',
    'Morgen word ik dertig, dus kom je ook?',
    'Fatima’s verjaardag is op 12 mei.',
    'Gefeliciteerd met je diploma, Bram!',
    'Ik heb je berichtje pas net gelezen, sorry.',
    'Zullen we zondag gaan wandelen in het Amsterdamse Bos?',
    'Mehmet zegt dat het feest om half negen begint.',
    'Ik heb nog 3 kaartjes over voor het concert van vrijdag.',
    'Lukt het jou om de sleutel bij de buren af te geven?',
    'Kom je ook naar de barbecue? Neem wel je eigen stoel mee.',
    'Ik zit nog op kantoor, maar ik kom zo.',
    'Hebben jullie zin om vanavond een film te kijken?',
    'Thijs heeft zijn telefoon in de trein laten liggen.',
    'Ik stuur je straks het adres via WhatsApp.',
    'Het is al laat, ik ga slapen. Welterusten!',
    'Wie heeft mijn oplader meegenomen?',
    'Noor en ik zitten in het café op de hoek.',
  ],
  email: [
    'Beste mevrouw Jansen,',
    'Hierbij stuur ik u de offerte voor de nieuwe keuken.',
    'In de bijlage vindt u het verslag van de vergadering van dinsdag.',
    'Kunt u mij laten weten of donderdag 14 maart om 10.00 uur schikt?',
    'Mocht u nog vragen hebben, dan hoor ik het graag.',
    'Alvast bedankt voor uw snelle reactie.',
    'Met vriendelijke groet,',
    'Geachte heer De Vries,',
    'Naar aanleiding van ons telefoongesprek stuur ik u de gegevens.',
    'Helaas kan ik niet aanwezig zijn bij de bijeenkomst van volgende week.',
    'Ik wil u hartelijk bedanken voor de prettige samenwerking.',
    'Wilt u de factuur binnen dertig dagen betalen?',
    'Graag ontvang ik uiterlijk vrijdag een bevestiging.',
    'Bent u in de gelegenheid om de stukken vóór maandag te sturen?',
    'De afspraak is verplaatst naar woensdag 2 april.',
    'Ik ben vanaf 1 augustus bereikbaar op een nieuw telefoonnummer.',
    'U kunt mij bereiken via j.devries@voorbeeld.nl of 06-12345678.',
    'Hebt u de documenten al ontvangen?',
    'Heeft u de documenten al ontvangen?',
    'Zoals afgesproken stuur ik u hierbij het contract ter ondertekening.',
    'Ik kijk uit naar uw reactie.',
    'Excuses voor de late reactie; ik was een week op vakantie.',
    'Wij hebben uw aanvraag in goede orde ontvangen.',
    'Uw bestelling wordt binnen twee werkdagen geleverd.',
    'Het pakket is gisteren bezorgd en in goede staat aangekomen.',
    'Ik solliciteer naar de functie van klantenservicemedewerker.',
    'Ik werk al drie jaar bij een webwinkel in Utrecht.',
    'Mijn collega’s vinden mij behulpzaam en nauwkeurig.',
    'Graag kom ik op gesprek om mijn motivatie toe te lichten.',
    'Met hartelijke groet, Fatima el Amrani',
  ],
  essay: [
    'Uit onderzoek blijkt dat steeds meer jongeren hun nieuws online lezen.',
    'Toch zijn er ook nadelen aan sociale media.',
    'Ten eerste kost het scrollen veel tijd, en ten tweede ligt desinformatie op de loer.',
    'Enerzijds biedt thuiswerken vrijheid, anderzijds mis je het contact met collega’s.',
    'Kortom, de voordelen wegen niet op tegen de nadelen.',
    'Al met al ben ik van mening dat de overheid meer moet investeren in onderwijs.',
    'Het is belangrijk dat iedereen de kans krijgt om een taal te leren.',
    'Wie een nieuwe taal leert, ontdekt ook een nieuwe cultuur.',
    'Dit betekent niet dat het probleem vanzelf verdwijnt.',
    'Daarnaast speelt de prijs van woningen een grote rol.',
    'Volgens veel deskundigen wordt het tekort aan leraren de komende jaren groter.',
    'Het enige wat helpt, is geduld en veel oefenen.',
    'Alles wat je leert, kun je later weer gebruiken.',
    'Dat is het mooiste wat ik ooit heb gezien.',
    'Het boek dat ik nu lees, gaat over de Tweede Wereldoorlog.',
    'Het meisje dat naast mij zit, komt uit Turkije.',
    'De man die daar staat, is mijn oom.',
    'De stad waar ik ben opgegroeid, ligt aan de kust.',
    'Het huis waarin ze wonen, is meer dan honderd jaar oud.',
    'Een groot huis is niet altijd een gelukkig huis.',
    'Het oude station wordt omgebouwd tot een bibliotheek.',
    'Mijn zus is twee jaar ouder dan ik.',
    'Hij is net zo lang als zijn vader.',
    'Het was drukker dan we hadden verwacht.',
    'Ik lees liever een boek dan dat ik televisie kijk.',
    'Hoewel het regende, gingen we toch naar het strand.',
    'Omdat de trein uitviel, kwam ik te laat op mijn werk.',
    'Nadat we hadden gegeten, maakten we een wandeling.',
    'Als je goed oefent, word je vanzelf sneller.',
    'Zodra het droog is, ga ik de tuin in.',
    'Wat er precies is gebeurd, weet niemand.',
    'Het is nog onduidelijk hoe de brand is ontstaan.',
    'Dat gebeurt vaker dan je denkt.',
    'Er wordt veel over gepraat, maar er gebeurt weinig.',
    'Ik vind dat hij gelijk heeft.',
    'Hij vindt dat ik te veel werk.',
    'Zij vinden het niet erg om te wachten.',
    'Ik heb hun gevraagd of ze ook komen.',
    'Hun ouders wonen in Rotterdam.',
    'Ik heb ze gisteren nog gezien.',
  ],
  news: [
    'Het kabinet presenteert dinsdag de Miljoenennota.',
    'Volgens het KNMI wordt het morgen zonnig met 24 graden.',
    'De NS rijdt dit weekend minder treinen vanwege werkzaamheden.',
    'De gemeente Utrecht wil meer fietsenstallingen bij het station bouwen.',
    'In Amsterdam zijn vorig jaar ruim 20.000 woningen verkocht.',
    'De politie zoekt getuigen van een inbraak in Den Haag.',
    'De Tweede Kamer stemt volgende week over het voorstel.',
    'De minister zegt dat er snel een oplossing komt.',
    'Bij de brand in de bakkerij raakte niemand gewond.',
    'Het pand, dat al sinds 1902 een bakkerij is, is zwaar beschadigd.',
    'De brandweer redde een kat die nog in het gebouw zat.',
    'De inflatie daalde in maart naar 2,4 procent.',
    'Het aantal toeristen in Nederland is weer gestegen.',
    'De koning opende woensdag een nieuw museum in Groningen.',
    'Op Koningsdag was het druk in alle grote steden.',
    'Door de storm vielen er bomen op de A2 bij Eindhoven.',
    'De Rijksoverheid adviseert mensen om binnen te blijven.',
    'Het RIVM meldt dat het griepseizoen voorbij is.',
    'De gemeenteraad heeft het plan met 23 tegen 16 stemmen aangenomen.',
    'De rechter oordeelde dat het ontslag onterecht was.',
    'Schiphol verwacht deze zomer meer dan 200.000 reizigers per dag.',
    'De prijs van een liter benzine ligt nu boven de twee euro.',
    'In het noorden van het land kan het vannacht licht vriezen.',
    'Na jaren van onderhandelen is er eindelijk een akkoord.',
    'De burgemeester sprak van een zwarte dag voor de stad.',
  ],
  recipe: [
    'Verwarm de oven voor op 180 graden.',
    'Snijd de ui en de knoflook in kleine stukjes.',
    'Voeg een snufje zout en peper toe.',
    'Laat de saus tien minuten zachtjes koken.',
    'Klop de eieren los met een vork.',
    'Bak de pannenkoeken aan beide kanten goudbruin.',
    'Smelt een klontje boter in de koekenpan.',
    'Bestrooi de pannenkoeken met poedersuiker.',
    'Meng de bloem met de melk tot een glad beslag.',
    'Laat het beslag een kwartier rusten.',
    'Was de groente en dep hem droog met keukenpapier.',
    'Kook de pasta in ruim water met zout beetgaar.',
    'Rasp de kaas en strooi hem over de ovenschotel.',
    'Zet de schaal 25 minuten in het midden van de oven.',
    'Serveer de soep met vers brood en een beetje peterselie.',
    'Voor 4 personen heb je 500 gram gehakt nodig.',
    'Gebruik bij voorkeur ongezouten roomboter.',
    'De taart is lekker met slagroom of een bolletje ijs.',
    'Bewaar de restjes maximaal twee dagen in de koelkast.',
    'Rooster de pijnboompitten in een droge pan.',
  ],
  sports: [
    'Feyenoord won zondag met 3-0 van Ajax.',
    'Max Verstappen werd in Zandvoort tweede.',
    'Sifan Hassan liep de marathon in Parijs in een geweldige tijd.',
    'Het Nederlands elftal speelt woensdag tegen België.',
    'De wedstrijd eindigde in een gelijkspel: 1-1.',
    'Na rust scoorde de spits twee keer.',
    'De schaatsers trainen deze week in Thialf.',
    'Ze zwom de 100 meter vrije slag in 52,3 seconden.',
    'De trainer is tevreden over de inzet van zijn spelers.',
    'Het team staat na tien wedstrijden bovenaan.',
    'Hij fietst elke ochtend 30 kilometer naar zijn werk.',
    'Op zaterdag voetbal ik met mijn vrienden in het park.',
    'De Tour de France start dit jaar in Florence.',
    'De keeper hield in de laatste minuut een penalty tegen.',
    'Zij heeft de finale gewonnen na een spannende tiebreak.',
  ],
  numbers: [
    'Het kost € 12,50 per persoon.',
    'Om 8.15 uur vertrekt de trein naar Groningen.',
    'Nederland heeft ongeveer 18 miljoen inwoners.',
    'Het is vandaag 21 °C en zonnig.',
    'Mijn huisnummer is 14b.',
    'De vergadering begint om half tien.',
    'We wonen op de derde verdieping, nummer 37.',
    'Ze is geboren op 3 juni 1998 in Tilburg.',
    'Het rapport telt 120 pagina’s.',
    'Ongeveer een kwart van de leerlingen fietst naar school.',
    'De korting is 15 procent op alle jassen.',
    'Je kunt bellen naar 0800-1234 tussen 9 en 17 uur.',
    'In 2023 bezochten bijna 2 miljoen mensen het museum.',
    'De lening moet binnen 24 maanden worden terugbetaald.',
    'Hij rende de 5 kilometer in 22 minuten.',
  ],
  abbreviations: [
    'Neem o.a. je paspoort en je rijbewijs mee.',
    'Dat is bijv. handig als je veel reist.',
    'De vergadering is a.s. maandag, d.w.z. over drie dagen.',
    'Graag z.s.m. reageren.',
    'Dhr. Bakker en mevr. Smit zijn vandaag afwezig.',
    'Zie blz. 34 voor meer informatie.',
    'Er waren ca. 50 mensen op het feest.',
    'De prijs is € 99 incl. btw.',
    'We verkopen fietsen, scooters, helmen enz.',
    'Lees het artikel in de NRC van zaterdag.',
    'De KLM vliegt drie keer per week naar Marrakesh.',
    'Hij werkt bij de ANWB als monteur.',
    'De VVD en de PvdA zijn het niet eens.',
    'Ze studeert aan de TU Delft.',
    'Stuur de brief t.a.v. de afdeling personeelszaken.',
  ],
  web: [
    'Kijk op www.parrotype.nl voor de nieuwste versie.',
    'Mail je vragen naar info@voorbeeld.nl.',
    'De code staat op https://github.com/voorbeeld/project.',
    'Volg ons op Instagram via @parrotype.',
    'Download de app in de App Store of Google Play.',
    'Klik op de knop rechtsboven om in te loggen.',
    'Je wachtwoord moet minstens 12 tekens hebben.',
    'De website is tijdelijk niet bereikbaar door onderhoud.',
    'Ik heb de update gisteren geïnstalleerd.',
    'Wis je cookies als de pagina niet laadt.',
  ],
  loanwords: [
    'Ik heb de meeting van vanmiddag gecanceld.',
    'Ze heeft de bestanden naar de cloud geüpload.',
    'Ik heb de nieuwe versie gedownload.',
    'We hebben een uur gebrainstormd over het logo.',
    'Hij heeft de printer gereset.',
    'Ze heeft het adres even gegoogeld.',
    'Ik heb de deadline gelukkig gehaald.',
    'Ze werkt als freelance webdesigner.',
    'We hadden vanochtend een call met de klant.',
    'Ik heb het gecheckt en het klopt.',
    'Mijn laptop is gisteren gecrasht.',
    'Ze heeft de app geüpdatet.',
    'Na de training hebben we lekker gerelaxt.',
    'De workshop over teambuilding was erg nuttig.',
    'Hij is manager van een start-up in Eindhoven.',
    'Het weekend was super gezellig.',
    'Ik moet nog even mijn mail checken.',
    'De feedback van de klant was positief.',
    'Ze geeft workshops over timemanagement.',
    'We hebben het event goed voorbereid.',
  ],
  verbs: [
    'Ik vind het leuk dat je komt.',
    'Hij vond het jammer dat het regende.',
    'Ik antwoord morgen op je mail.',
    'Zij antwoordt altijd binnen een uur.',
    'Het wordt tijd dat we gaan.',
    'Ik werd wakker van de wekker.',
    'Werd je gisteren nog opgehaald?',
    'Je wordt bedankt!',
    'Ik besteed veel tijd aan sport.',
    'Hij besteedt al zijn geld aan boeken.',
    'Ik heb veel tijd aan dit project besteed.',
    'Wat is er gebeurd?',
    'Het gebeurde gisteren rond vier uur.',
    'Hij heeft de hele dag gewerkt.',
    'We hebben pizza besteld.',
    'Ik heb het geprobeerd, maar het lukte niet.',
    'Ze fietste naar school en belde onderweg haar moeder.',
    'De kat heeft de hele nacht gemiauwd.',
    'We hebben de kamer geverfd.',
    'Hij heeft zich vergist in de datum.',
    'Ik heb het boek geleend van de bibliotheek.',
    'Zij heeft het hele verhaal verteld.',
    'De kinderen hebben buiten gespeeld.',
    'Wij wachtten op de bus.',
    'Ik zette koffie en las de krant.',
    'Hij redde het kind uit het water.',
    'Ze meldden zich op tijd aan.',
    'Het verhaal speelt zich af in een dorp in Friesland.',
    'Hij verbrandt de oude takken in de tuin.',
    'Ik verbrand me altijd aan de oven.',
    'Hou op met dat geklaag!',
    'Houd de deur even open, alsjeblieft.',
    'Ik houd van lange wandelingen.',
    'Zij houdt van fietsen in de regen.',
    'Word lid van onze leesclub!',
    'Ben jij morgen thuis?',
    'Heb jij mijn sleutels gezien?',
    'Kun jij me helpen met verhuizen?',
    'Jij bent echt een held.',
    'U hebt gelijk.',
  ],
  daily: [
    '’s Avonds eten we meestal samen.',
    'In de zomer gaan we naar Frankrijk.',
    'Op maandag heb ik altijd yoga.',
    'Ik spreek Nederlands, Engels en Arabisch.',
    'Mijn buurvrouw komt uit Marokko.',
    'We hebben een nieuwe bank gekocht bij IKEA.',
    'De supermarkt is op zondag open van 12 tot 18 uur.',
    'Mijn moeder belt me elke zondagavond.',
    'Ik moet de vuilnisbak nog buiten zetten.',
    'Het regent al de hele week.',
    'Vanochtend stond ik twintig minuten in de file.',
    'Ik ben mijn paraplu vergeten.',
    'Ze heeft een afspraak bij de tandarts.',
    'Ik heb al een week kiespijn.',
    'De verwarming in de slaapkamer doet het niet.',
    'Ik ga morgen naar de sportschool.',
    'Mijn knie doet niet meer zo’n pijn.',
    'Bedankt voor je berichtje.',
    'Wil je met mij mee naar de yogales?',
    'Ik heb mijn fiets laten repareren.',
    'De kinderen spelen buiten in de sneeuw.',
    'We gaan dit jaar met de trein op vakantie.',
    'Ik drink geen koffie na vier uur.',
    'Heb jij zin in een kopje thee?',
    'Ik ben blij dat ik een trui heb meegenomen.',
    'Morgen rijden we met een busje naar de bergen.',
    'Het is ’s nachts best koud.',
    'Mijn opa is vorige maand negentig geworden.',
    'De bibliotheek is tijdelijk gesloten.',
    'Ik zoek een kamer in Leiden of Delft.',
    'De Efteling is een groot pretpark in Brabant.',
    'In de Kalverstraat is het altijd druk.',
    'We wonen aan de Keizersgracht in Amsterdam.',
    'Ze woont op de Lauriergracht, vlak bij het centrum.',
    'Volgend jaar wil ik naar IJsland.',
    'Het IJsselmeer is groter dan je denkt.',
    'Mijn broer woont in ’s-Hertogenbosch.',
    'Hij heeft een Surinaamse moeder en een Friese vader.',
    'We vieren Suikerfeest bij mijn tante.',
    'In december vieren we Sinterklaas en Kerstmis.',
  ],
  tricky: [
    'Wie de schoen past, trekke hem aan.',
    'Het grote huis staat al jaren leeg.',
    'Een oud huis heeft vaak veel karakter.',
    'Dat vind ik een goed idee.',
    'Wat vindt hij ervan?',
    'Vindt u het goed als ik het raam opendoe?',
    'Wordt het morgen weer zo warm?',
    'Wordt er vandaag nog iets bezorgd?',
    'Heeft iemand mijn jas gezien?',
    'Niemand weet waar hij is.',
    'Iedereen vindt het een goed plan.',
    'Hun hond blaft de hele dag.',
    'Ik heb het hun al drie keer uitgelegd.',
    'Zij hebben een nieuwe auto gekocht.',
    'Ze zijn de beste buren die we ooit hebben gehad.',
    'Mijn vader en ik gaan vissen.',
    'Iemand als jij verdient een prijs.',
    'De film die we zagen, was spannend.',
    'Het is beter dan niets.',
    'Er zijn meer mensen dan stoelen.',
    'Dit is het huis waar ik geboren ben.',
    'Zo’n mooie dag hebben we lang niet gehad.',
    'Zoiets heb ik nog nooit meegemaakt.',
    'Weet jij of de winkel vandaag open is?',
    'Of je nu wilt of niet, je moet je huiswerk maken.',
    'Je kunt beter vroeg vertrekken.',
    'Je kan ook morgen langskomen.',
    'Zij is de enige die het weet.',
    'Beide kinderen zitten op dezelfde school.',
    'Ik heb het hem gisteren nog gezegd.',
  ],
}
