// Correct English in many registers, written for the false-positive hunt. Every sentence must pass the
// full free-writing pipeline (rules + Hunspell) without a high or medium flag, with the en-US dictionary.
// Spelling is American except in the 'british' group, which is checked with the en-GB dictionary.

export const CORRECT_EN: Record<string, string[]> = {
  chat: [
    'Hey Sam, are you there yet? I’m at platform 5.',
    'Running late, the train’s delayed by ten minutes.',
    'Lol, no, that was Priya, not me.',
    'Did you see the photos from Saturday?',
    'Can you call me when you’re done?',
    'Ok, I’ll take the 5:42 bus then.',
    'Yusra’s coming too, she’s bringing her little brother.',
    'Pizza or sushi tonight? Your call.',
    'Is it ok if I come a bit later?',
    'Thanks so much, you’re a lifesaver!',
    'Happy birthday, Daan! Have a great day.',
    'I just read your message, sorry for the slow reply.',
    'Want to go for a walk on Sunday?',
    'Mehmet says the party starts at 8:30.',
    'I’ve got 3 tickets left for Friday’s concert.',
    'Could you drop the key off at the neighbors’ place?',
    'Are you coming to the barbecue? Bring your own chair.',
    'Still at the office, but I’ll be there soon.',
    'Who took my charger?',
    'We’re in the café on the corner, near the bookshop.',
    'It’s late, I’m off to bed. Good night!',
    'Let’s meet at noon, if that works for you.',
    'I’ll send you the address on WhatsApp later.',
    'Noor and I already ordered, so don’t rush.',
    'That’s hilarious, I can’t stop laughing.',
    'Btw, the meeting moved to Thursday.',
    'I’m not sure yet, I’ll let you know tomorrow.',
    'He’s been at the gym since six this morning.',
    'You’re welcome, any time.',
    'Can’t wait to see you guys next week!',
  ],
  email: [
    'Dear Ms. Johnson,',
    'Please find attached the quote for the new kitchen.',
    'I have attached the minutes of Tuesday’s meeting.',
    'Could you let me know whether Thursday, March 14 at 10 a.m. works for you?',
    'If you have any questions, please don’t hesitate to contact me.',
    'Thank you in advance for your quick reply.',
    'Kind regards,',
    'Best wishes, Fatima',
    'Following our phone call, I am sending you the details.',
    'Unfortunately, I will not be able to attend next week’s meeting.',
    'I would like to thank you for the pleasant cooperation.',
    'Please pay the invoice within thirty days.',
    'I would appreciate a confirmation by Friday at the latest.',
    'The appointment has been moved to Wednesday, April 2.',
    'You can reach me at j.smith@example.com or on 555-0134.',
    'Have you received the documents yet?',
    'As agreed, I am sending you the contract for signature.',
    'I look forward to hearing from you.',
    'Apologies for the late reply; I was on vacation for a week.',
    'We have received your application and will get back to you shortly.',
    'Your order will be delivered within two business days.',
    'The package arrived yesterday in good condition.',
    'I am applying for the position of customer service representative.',
    'I have worked at an online store in Utrecht for three years.',
    'My colleagues describe me as helpful and accurate.',
    'I would welcome the opportunity to discuss my application in person.',
    'Please let me know if anything is unclear.',
    'I am writing to ask about the status of my refund.',
    'Could we schedule a short call early next week?',
    'Thank you for your patience while we looked into this.',
  ],
  essay: [
    'Research shows that more and more young people read the news online.',
    'However, social media also has its drawbacks.',
    'First, scrolling takes a lot of time; second, misinformation spreads quickly.',
    'On the one hand, working from home offers freedom; on the other hand, you miss your colleagues.',
    'In short, the advantages do not outweigh the disadvantages.',
    'All in all, I believe the government should invest more in education.',
    'It is important that everyone gets the chance to learn a language.',
    'Anyone who learns a new language also discovers a new culture.',
    'This does not mean that the problem will simply disappear.',
    'In addition, housing prices play a major role.',
    'According to many experts, the teacher shortage will grow in the coming years.',
    'The only thing that helps is patience and a lot of practice.',
    'Everything you learn can be useful later.',
    'That is the most beautiful thing I have ever seen.',
    'The book I am reading now is about the Second World War.',
    'The girl who sits next to me comes from Turkey.',
    'The city where I grew up is on the coast.',
    'My sister is two years older than me.',
    'It was busier than we had expected.',
    'Although it was raining, we still went to the beach.',
    'Because the train was canceled, I was late for work.',
    'After we had eaten, we went for a walk.',
    'If you practice every day, you will get faster.',
    'Nobody knows exactly what happened.',
    'It is still unclear how the fire started.',
    'That happens more often than you think.',
    'I think he is right.',
    'She thinks I work too much.',
    'They do not mind waiting.',
    'Its main advantage is that it saves time.',
    'It’s not the end of the world.',
    'Whose idea was it to start at six?',
    'Who’s coming to dinner tonight?',
    'There are fewer cars in the city center than ten years ago.',
    'Their house is bigger than ours.',
    'They’re moving to Rotterdam next month.',
    'The effect of the new law was small.',
    'The weather can affect your mood.',
    'I have lived in Leiden since 2019.',
    'She has been a nurse for twelve years.',
  ],
  news: [
    'The government will present its budget on Tuesday.',
    'According to the weather service, tomorrow will be sunny with highs of 75 degrees.',
    'Fewer trains will run this weekend because of maintenance work.',
    'The city of Utrecht wants to build more bike parking near the station.',
    'More than 20,000 homes were sold in Amsterdam last year.',
    'Police are looking for witnesses to a burglary in The Hague.',
    'Parliament will vote on the proposal next week.',
    'The minister said a solution would be found soon.',
    'No one was injured in the fire at the bakery.',
    'Firefighters rescued a cat that was still inside the building.',
    'Inflation fell to 2.4 percent in March.',
    'The number of tourists visiting the Netherlands has risen again.',
    'The king opened a new museum in Groningen on Wednesday.',
    'Trees fell onto the highway near Eindhoven during the storm.',
    'The city council approved the plan by 23 votes to 16.',
    'The judge ruled that the dismissal was unfair.',
    'The airport expects more than 200,000 passengers a day this summer.',
    'Gas prices are now above $4 a gallon in California.',
    'Temperatures could drop below freezing overnight in the north.',
    'After years of negotiations, the two sides finally reached a deal.',
    'NASA plans to launch the mission in 2027.',
    'The U.S. economy grew faster than expected in the second quarter.',
    'The UN called for an immediate ceasefire.',
    'The company’s shares rose 12% after the announcement.',
    'The mayor described it as a dark day for the city.',
  ],
  recipe: [
    'Preheat the oven to 350°F.',
    'Finely chop the onion and garlic.',
    'Add a pinch of salt and pepper.',
    'Let the sauce simmer gently for ten minutes.',
    'Beat the eggs with a fork.',
    'Fry the pancakes on both sides until golden brown.',
    'Melt a knob of butter in a frying pan.',
    'Dust the pancakes with powdered sugar.',
    'Whisk the flour and milk into a smooth batter.',
    'Let the batter rest for fifteen minutes.',
    'Wash the vegetables and pat them dry with a paper towel.',
    'Cook the pasta in plenty of salted water until al dente.',
    'Grate the cheese and sprinkle it over the casserole.',
    'Bake for 25 minutes on the middle rack.',
    'Serve the soup with fresh bread and a little parsley.',
    'For four people, you will need 1 lb of ground beef.',
    'Store leftovers in the fridge for up to two days.',
    'Toast the pine nuts in a dry pan.',
    'Stir in two tablespoons of olive oil.',
    'Season to taste and garnish with fresh basil.',
  ],
  sports: [
    'Feyenoord beat Ajax 3-0 on Sunday.',
    'Max Verstappen finished second at Zandvoort.',
    'Sifan Hassan ran a brilliant race in the Paris marathon.',
    'The Dutch team plays Belgium on Wednesday.',
    'The match ended in a 1-1 draw.',
    'The striker scored twice after halftime.',
    'She swam the 100 meters freestyle in 52.3 seconds.',
    'The coach is happy with his players’ effort.',
    'The team is top of the league after ten games.',
    'He cycles 20 miles to work every morning.',
    'The goalkeeper saved a penalty in the last minute.',
    'She won the final after a tense tiebreak.',
    'The Lakers lost to the Celtics in overtime.',
    'Serena Williams won 23 Grand Slam singles titles.',
    'The Tour de France starts in Florence this year.',
  ],
  numbers: [
    'Tickets cost $12.50 per person.',
    'The train to Boston leaves at 8:15 a.m.',
    'The Netherlands has about 18 million inhabitants.',
    'It is 70 degrees and sunny today.',
    'The report is 120 pages long.',
    'About a quarter of the students bike to school.',
    'All jackets are 15% off this week.',
    'Call 1-800-555-0199 between 9 a.m. and 5 p.m.',
    'Nearly 2 million people visited the museum in 2023.',
    'The loan must be repaid within 24 months.',
    'He ran the 5K in 22 minutes.',
    'Our apartment is on the 3rd floor, number 37.',
    'She was born on June 3, 1998, in Chicago.',
    'The meeting starts at 9:30 sharp.',
    'Version 2.1 fixes the login bug.',
  ],
  abbreviations: [
    'Bring your passport, driver’s license, etc.',
    'Some fruits, e.g. apples and pears, keep well in the fridge.',
    'The deadline is Friday, i.e. three days from now.',
    'Dr. Smith and Mrs. Brown are away today.',
    'See p. 34 for more information.',
    'There were approx. 50 people at the party.',
    'The price is $99 incl. tax.',
    'She works for the BBC in London.',
    'He studied at MIT before moving to New York.',
    'The EU and the UK signed a new agreement.',
    'Please RSVP by Monday.',
    'The CEO will speak at the event.',
    'My flight with KLM leaves from JFK at 6 p.m.',
    'Mr. Lee lives on Elm St. near the park.',
    'FAQ: How do I reset my password?',
  ],
  web: [
    'Visit www.parrotype.app for the latest version.',
    'Send your questions to info@example.com.',
    'The code is on https://github.com/example/project.',
    'Follow us on Instagram at @parrotype.',
    'Download the app from the App Store or Google Play.',
    'Click the button in the top right corner to log in.',
    'Your password must be at least 12 characters long.',
    'The website is temporarily down for maintenance.',
    'I installed the update yesterday.',
    'Clear your cookies if the page does not load.',
  ],
  grammar: [
    'I have lived here for six years.',
    'She has known him since high school.',
    'He explained the rules to me.',
    'Could you lend me your pen?',
    'Can I borrow your pen?',
    'She taught me how to swim.',
    'I learned a lot from her.',
    'We took a lot of photos in Rome.',
    'I made a mistake in the last sentence.',
    'Did you do your homework?',
    'I am looking forward to seeing you.',
    'I am interested in history.',
    'He could have called me.',
    'You should have told me earlier.',
    'Neither of them was ready.',
    'Each of the students has a laptop.',
    'Most of my friends live in Amsterdam.',
    'I don’t know what time it is.',
    'Do you know where the station is?',
    'He doesn’t like coffee.',
    'Does she speak Dutch?',
    'I bought a new laptop yesterday.',
    'The shop assistant was very helpful.',
    'I need some information about the course.',
    'Can you give me some advice?',
    'I have a lot of homework today.',
    'We bought an apple, an orange and a banana.',
    'It took an hour to get there.',
    'She is an honest person.',
    'He wants to be a European citizen.',
    'It is a useful tool for a university student.',
    'I have to do a lot of things before Friday.',
    'Thank you for everything.',
    'Let’s go to the beach on the weekend.',
    'He is taller than his brother.',
    'Then we went home.',
    'We have less time than we thought.',
    'I lost my keys again.',
    'These shoes are too loose.',
    'I’d love to, but I can’t.',
  ],
  british: [
    'My favourite colour is blue.',
    'We travelled to the theatre in the centre of town.',
    'I realised that I had organised everything.',
    'Our neighbour has a lovely garden.',
    'The programme starts at half past seven.',
    'I learnt a lot at university.',
    'She spelt my name wrong again.',
    'Can you pick me up from the train station at quarter to six?',
    'We had fish and chips by the seaside.',
    'The lift is out of order, so take the stairs.',
  ],
  daily: [
    'In the summer we usually go to France.',
    'I have yoga every Monday.',
    'I speak Dutch, English and Arabic.',
    'My neighbor is from Morocco.',
    'We bought a new sofa at IKEA.',
    'The supermarket is open from 8 a.m. to 10 p.m.',
    'My mother calls me every Sunday evening.',
    'It has been raining all week.',
    'I spent twenty minutes in traffic this morning.',
    'I forgot my umbrella.',
    'She has an appointment at the dentist.',
    'The heating in the bedroom doesn’t work.',
    'Thanks for your message.',
    'I had my bike repaired.',
    'The kids are playing outside in the snow.',
    'I don’t drink coffee after four.',
    'Would you like a cup of tea?',
    'I’m glad I brought a sweater.',
    'My grandfather turned ninety last month.',
    'The library is temporarily closed.',
    'I’m looking for a room in Leiden or Delft.',
    'We celebrate Eid with my aunt.',
    'In December we celebrate Christmas.',
    'Next year I want to visit Iceland.',
    'Monty is a kea, a mountain parrot from New Zealand.',
    'Layla taught Monty a Dutch word: gezellig.',
    'She typed “teh” three times in one sentence.',
    'Curiouser and curiouser!',
    'Pieces of eight! pieces of eight!',
    'Help! help! The cat is stuck in the tree!',
  ],
}
