// Labelled Dutch mistakes for the recall measurement: one mistake per sentence, marked {wrong=>right}.
// Taken from docs/research/dutch-errors.md (rule tables DT, PART, KOF, AGR, ART, PRN, CMP, CAP, SP) and
// from the user's own error profile. The family groups the report (precision/recall per rule family).
//
// `gap` marks a mistake the checker is known not to catch yet (with the reason). Gaps count against recall
// in the report but do not fail the test; anything else that is missed does.

export type Labelled = [family: string, text: string, gap?: string]

export const ERRORS_NL: Labelled[] = [
  // d/t with ik
  ['dt', 'Ik {wordt=>word} morgen dertig.'],
  ['dt', 'Ik {vindt=>vind} het een mooi boek.'],
  ['dt', 'Ik {houdt=>houd} van pannenkoeken.'],
  ['dt', 'Morgen {wordt=>word} ik dertig.'],
  ['dt', 'Dat {vindt=>vind} ik niet erg.'],
  ['dt', 'Ik {antwoordt=>antwoord} je morgen.'],
  ['dt', 'Ik {besteedt=>besteed} veel tijd aan mijn huiswerk.'],
  ['dt', 'Ik {rijdt=>rijd} elke dag naar Utrecht.'],
  ['dt', 'Soms {wordt=>word} ik heel moe van het werk.'],
  ['dt', 'Ik {verbrandt=>verbrand} de oude brieven.'],
  // d/t with hij, zij, het, u
  ['dt', 'Hij {vind=>vindt} het een goed idee.'],
  ['dt', 'Zij {word=>wordt} volgende week veertig.'],
  ['dt', 'Het {word=>wordt} steeds kouder.'],
  ['dt', 'Hij {antwoord=>antwoordt} nooit op mijn berichten.'],
  ['dt', 'Wat {vind=>vindt} hij ervan?'],
  ['dt', 'U {vind=>vindt} de formulieren op onze website.'],
  ['dt', 'Hij {houd=>houdt} niet van spruitjes.'],
  ['dt', 'Het {lijd=>lijdt} geen twijfel.'],
  ['dt', 'Mijn moeder {vind=>vindt} het niet erg.', 'noun subject: the checker only pairs pronouns with verbs'],
  ['dt', 'De vergadering {word=>wordt} verplaatst naar vrijdag.', 'noun subject'],
  // d/t with jij and je
  ['dt', 'Jij {vind=>vindt} het altijd leuk.'],
  ['dt', 'Jij {word=>wordt} steeds beter.'],
  ['dt', '{Vindt=>Vind} jij dat ook?'],
  ['dt', '{Wordt=>Word} jij ook opgehaald?'],
  ['dt', '{Vindt=>Vind} je het leuk?'],
  ['dt', 'Waarom {antwoordt=>antwoord} jij niet?'],
  ['dt', '{Wordt=>Word} je trouwens nog opgehaald na de training?'],
  ['dt', 'Hoe laat {wordt=>word} je wakker?'],
  ['dt', '{Bent=>Ben} je morgen thuis?'],
  ['dt', '{Hebt=>Heb} je mijn sleutels gezien?'],
  // past tense
  ['dt', 'Hij {werdt=>werd} boos.'],
  ['dt', 'Ik {vondt=>vond} het jammer.'],
  // agreement
  ['agreement', 'Hij {ga=>gaat} morgen naar Parijs.'],
  ['agreement', 'Jij {kom=>komt} altijd te laat.'],
  ['agreement', 'Wij {heeft=>hebben} geen tijd.'],
  ['agreement', 'U {is=>bent} van harte welkom.'],
  // participles
  ['participle', 'Wat is er {gebeurt=>gebeurd}?'],
  ['participle', 'Het pakket is gisteren {bezorgt=>bezorgd}.'],
  ['participle', 'Ik heb hem gisteren {gebelt=>gebeld}.'],
  ['participle', 'Ik heb het echt {geprobeert=>geprobeerd}.'],
  ['participle', 'Het huis is zwaar {beschadigt=>beschadigd}.'],
  ['participle', 'We hebben de hele kamer {geverft=>geverfd}.'],
  ['participle', 'Ik heb het formulier al {ingevult=>ingevuld}.'],
  ['participle', 'Ze heeft de vraag {beantwoordt=>beantwoord}.'],
  ['participle', 'De brief is gisteren {verstuurt=>verstuurd}.'],
  ['participle', 'Ik heb het boek van mijn zus {geleent=>geleend}.'],
  ['participle', 'Dat {gebeurd=>gebeurt} vaker dan je denkt.'],
  ['participle', 'Wat {gebeurd=>gebeurt} er hier?'],
  ['participle', 'Dit {betekend=>betekent} dat we moeten wachten.'],
  ['participle', 'Ik heb de app {geupdate=>geüpdatet}.'],
  ['participle', 'Ik {heb=>ben} gisteren naar Amsterdam gegaan.'],
  // 't kofschip
  ['kofschip', 'Hij {fietsde=>fietste} elke dag naar school.'],
  ['kofschip', 'Ik {werkde=>werkte} gisteren tot laat.'],
  ['kofschip', 'Zij {stopde=>stopte} vorig jaar met roken.'],
  ['kofschip', 'Ik {belte=>belde} mijn moeder.'],
  ['kofschip', 'Het vuur {brande=>brandde} de hele nacht.'],
  ['kofschip', 'Ze {pakde=>pakte} haar tas en ging weg.'],
  ['kofschip', 'Zij {dansde=>danste} de hele avond.'],
  ['kofschip', 'Ik {maakde=>maakte} een domme fout.'],
  ['kofschip', 'Hij {leefte=>leefde} tien jaar in Spanje.'],
  ['kofschip', 'Ze {melde=>meldde} zich gisteren ziek.'],
  // spelling (Hunspell + maps)
  ['spelling', 'Dat is {eigelijk=>eigenlijk} niet zo moeilijk.'],
  ['spelling', 'Ik ga {misschein=>misschien} morgen.'],
  ['spelling', 'Het was heel {gezelig=>gezellig}.'],
  ['spelling', 'We gaan in de zomer naar {Belgie=>België}.'],
  ['spelling', 'Ik heb veel {ideeen=>ideeën}.'],
  ['spelling', 'Hij woont nog {aleen=>alleen}.'],
  ['spelling', 'Dat is {natuurluk=>natuurlijk} waar.'],
  ['spelling', 'Ik ben heel {gelukkich=>gelukkig}.'],
  ['spelling', 'Ik heb twee {fotos=>foto’s} gemaakt.'],
  ['spelling', 'De {autos=>auto’s} staan buiten.'],
  ['spelling', 'We eten vanavond {pannekoeken=>pannenkoeken}.'],
  ['spelling', 'Ik heb meer {tyd=>tijd} nodig.'],
  ['spelling', 'Het is erg {kaud=>koud} buiten.'],
  ['spelling', 'Hij heeft een {blouwe=>blauwe} auto.'],
  ['spelling', 'Hij is {achtien=>achttien} jaar.'],
  ['spelling', 'Dat is heel {interresant=>interessant}.'],
  ['spelling', 'Ik ben {morgne=>morgen} jarig.'],
  ['spelling', 'Wij gaan naar de {winekl=>winkel}.'],
  ['spelling', 'Ik heb een {afsrpaak=>afspraak} bij de dokter.'],
  ['spelling', 'Dat is heel {belangijk=>belangrijk}.'],
  ['spelling', 'We hebben drie weken {vakantei=>vakantie}.'],
  ['spelling', '{Bijvoorbeld=>Bijvoorbeeld} een appel of een peer.'],
  ['spelling', 'Ik heb het {gisteern=>gisteren} gekocht.'],
  ['spelling', 'De {computer’s=>computers} zijn kapot.'],
  ['spelling', 'Ik ga {s’avonds=>’s avonds} vaak wandelen.'],
  ['spelling', 'Hij had {teveel=>te veel} gegeten.'],
  ['spelling', 'Ik kom {inplaats=>in plaats} van mijn broer.'],
  ['spelling', 'Dat is {perse=>per se} niet waar.'],
  ['spelling', 'Ik heb {zon=>zo’n} honger.'],
  ['spelling', 'Ik ben blij dat ik een trui heb {meegenoemen=>meegenomen}.'],
  ['spelling', 'De {financiëele=>financiële} situatie is goed.'],
  ['spelling', 'Wij {wonnen=>wonen} in Leiden.', 'a real word (won, wonnen) in the wrong place'],
  ['spelling', 'Ik ben {blei=>blij} dat je er bent.', 'blei is a real word (a fish)'],
  ['spelling', 'Morgen {reiden=>rijden} we naar de bergen.', 'reiden is a real word (reien)'],
  // capitals
  ['capital', 'Ik spreek vloeiend {arabisch=>Arabisch}.'],
  ['capital', 'Op {Maandag=>maandag} heb ik yoga.'],
  ['capital', 'In {Juni=>juni} gaan we op vakantie.'],
  ['capital', 'We gaan naar {frankrijk=>Frankrijk}.'],
  ['capital', 'Hij woont al jaren in {amsterdam=>Amsterdam}.'],
  ['capital', 'Volgend jaar gaan we naar {Ijsland=>IJsland}.'],
  ['capital', 'Het is vandaag {Zaterdag=>zaterdag}.'],
  ['capital', 'Gisteren was ik moe. {daarna=>Daarna} ging ik slapen.'],
  ['capital', 'Morgen ga {Ik=>ik} naar de markt.'],
  ['capital', 'Mijn buurvrouw is {marokkaans=>Marokkaans}.'],
  // compounds
  ['compound', 'Ik moet morgen naar de {tand arts=>tandarts}.'],
  ['compound', 'Ik heb al de hele dag {hoofd pijn=>hoofdpijn}.'],
  ['compound', 'De {voetbal wedstrijd=>voetbalwedstrijd} begint om drie uur.'],
  ['compound', 'Mijn {fiets sleutel=>fietssleutel} is weg.'],
  ['compound', 'De {kerst vakantie=>kerstvakantie} begint vrijdag.'],
  ['compound', 'We hebben een nieuwe {koffie-automaat=>koffieautomaat}.'],
  ['compound', 'Ik heb al een week {kies pijn=>kiespijn}.'],
  ['compound', 'Smelt de boter in de {koeken pan=>koekenpan}.'],
  ['compound', 'Het {project plan=>projectplan} is nog niet af.', 'both parts are words; only a curated list is safe'],
  ['compound', 'Wie de {vergader ruimte=>vergaderruimte} wil gebruiken, moet reserveren.', 'stem + noun split'],
  // de/het, die/dat, dat/wat
  ['article', 'Ik heb {de=>het} boek al gelezen.'],
  ['article', 'Waar is {de=>het} meisje gebleven?'],
  ['article', 'Ik woon in {de=>het} centrum van Utrecht.'],
  ['article', 'Ze heeft {de=>het} huis verkocht.'],
  ['article', '{Het=>De} auto is kapot.'],
  ['article', 'We hebben {het=>de} tafel gedekt.', 'het after a verb can be the pronoun (Heeft het zin?)'],
  ['article', 'Ik vind {deze=>dit} boek heel mooi.'],
  ['article', '{Onze=>Ons} huis is te klein.'],
  ['relative', 'Het boek {die=>dat} ik lees, is spannend.'],
  ['relative', 'Het meisje {die=>dat} daar staat, is mijn zus.'],
  ['relative', 'Het huis {die=>dat} we kochten, is oud.'],
  ['adjective', 'We wonen in een {grote=>groot} huis.'],
  ['adjective', 'Het {groot=>grote} huis staat al jaren leeg.'],
  ['adjective', 'Ze heeft een {mooie=>mooi} huis.'],
  // pronouns
  ['pronoun', '{Hun=>Zij} hebben een nieuwe auto gekocht.'],
  ['pronoun', '{Me=>Mijn} knie doet pijn.'],
  ['pronoun', 'Is dit {jou=>jouw} jas?'],
  ['pronoun', 'Ik ga met {jouw=>jou} mee.'],
  ['pronoun', 'Bedankt voor {jou=>jouw} hulp.'],
  ['pronoun', '{Hun=>Zij} wonen al tien jaar in Leiden.'],
  ['pronoun', 'Hoe gaat het met {u=>uw} moeder?'],
  ['pronoun', 'Als ik {jouw=>jou} was, zou ik het doen.'],
  // comparisons
  ['comparison', 'Mijn zus is twee jaar ouder {als=>dan} ik.'],
  ['comparison', 'Hij is groter {als=>dan} zijn vader.'],
  ['comparison', 'Het was beter {als=>dan} vorig jaar.'],
  ['comparison', 'Hij is even groot {dan=>als} zijn broer.'],
  ['comparison', 'Dat is hetzelfde {dan=>als} vorige week.'],
  ['comparison', 'Ik vind dat iets anders {als=>dan} stelen.', '‘anders als’ is only a strict-mode hint'],
  // word order
  ['wordorder', 'Morgen {ik ga=>ga ik} naar de markt.'],
  ['wordorder', 'Gisteren {ik heb=>heb ik} een film gezien.'],
  // lexical
  ['lexical', 'Hij is de {enigste=>enige} die het weet.'],
  ['lexical', 'Ik {ben het mee eens=>ben het ermee eens}.', 'needs a rewrite of three words'],
  ['lexical', 'Ik {besef me=>besef} dat het laat is.'],
  ['lexical', 'Ik {leg=>lig} al de hele dag in bed.'],
  // punctuation and typos
  ['punctuation', 'Ik kom morgen{ ,=>,} als het lukt.'],
  ['punctuation', 'Ik heb {de de=>de} sleutels gevonden.'],
]
