// Labelled English mistakes for the recall measurement: one mistake per sentence, marked {wrong=>right}.
// From docs/research/english-errors.md (confusables, Dutch and Arabic transfer, the misspelling list)
// and the user's profile. `gap` marks a known miss with the reason.

import type { Labelled } from './errors.nl'

export const ERRORS_EN: Labelled[] = [
  // confusables
  ['confusable', 'My brother is taller {then=>than} me.'],
  ['confusable', 'We had dinner and {than=>then} we went home.'],
  ['confusable', '{Its=>It’s} raining again.'],
  ['confusable', 'The dog wagged {it’s=>its} tail.'],
  ['confusable', 'The company changed {it’s=>its} own logo.'],
  ['confusable', '{Your=>You’re} going to love this.'],
  ['confusable', 'Is this {you’re=>your} bag?'],
  ['confusable', '{Their=>There} is a problem with the printer.'],
  ['confusable', 'They forgot {there=>their} own keys.'],
  ['confusable', 'We went to {there=>their} house for dinner.'],
  ['confusable', '{Their=>They’re} going to be late.'],
  ['confusable', 'I don’t want to {loose=>lose} my keys.'],
  ['confusable', 'Don’t {loose=>lose} hope.'],
  ['confusable', 'The weather has a big {affect=>effect} on my mood.'],
  ['confusable', 'Stress can {effect=>affect} your sleep.'],
  ['confusable', '{Who’s=>Whose} phone is this?'],
  ['confusable', '{Whose=>Who’s} coming to the party?'],
  ['confusable', 'It is {to=>too} hot to work.'],
  ['confusable', 'I want {too=>to} go home.'],
  ['confusable', 'She said me {to=>too}.', 'needs ‘me to’ at the end of a clause'],
  ['confusable', 'I had {two=>too} much coffee.'],
  ['confusable', 'Please {except=>accept} my apology.'],
  ['confusable', 'Can you {advice=>advise} me?'],
  ['confusable', 'Thanks for the {advise=>advice}.'],
  ['confusable', 'I {belief=>believe} you.'],
  ['confusable', 'She won first {price=>prize}.'],
  ['confusable', 'This is the best day of my {live=>life}.'],
  ['confusable', 'I {could of=>could have} helped you.'],
  ['confusable', 'You {should of=>should have} told me.'],
  ['confusable', '{Off course=>Of course} you can come.'],
  ['confusable', 'My cousin is coming {to=>too}, she is in town for a day.', 'clause-final ‘to’ is often right (I’d love to)'],
  ['confusable', 'The owners clearly know {there=>their} wines.', 'there + noun after a verb is ambiguous'],
  // spelling
  ['spelling', 'I {recieved=>received} your letter.'],
  ['spelling', 'We need {accomodation=>accommodation} for two nights.'],
  ['spelling', 'I will {definately=>definitely} come.'],
  ['spelling', 'Please keep them {seperate=>separate}.'],
  ['spelling', 'Is a deposit {neccessary=>necessary}?'],
  ['spelling', 'We have {alot=>a lot} of work.'],
  ['spelling', 'They help {eachother=>each other}.'],
  ['spelling', 'It was a {beatiful=>beautiful} day.'],
  ['spelling', 'I go to the gym {becuase=>because} it helps.'],
  ['spelling', 'See you {tommorow=>tomorrow}.'],
  ['spelling', 'This is {wierd=>weird}.'],
  ['spelling', 'The {goverment=>government} made a decision.'],
  ['spelling', 'I {beleive=>believe} in you.'],
  ['spelling', 'It happens {occasionaly=>occasionally}.'],
  ['spelling', 'I need to {practise=>practice} more.'],
  ['spelling', 'She is my best {freind=>friend}.'],
  ['spelling', 'Wait {untill=>until} tomorrow.'],
  ['spelling', 'I am {intrested=>interested} in art.'],
  ['spelling', 'That was {embarassing=>embarrassing}.'],
  ['spelling', 'He is a {profesional=>professional} cook.'],
  ['spelling', 'I {dont=>don’t} know.'],
  ['spelling', 'She {doesnt=>doesn’t} care.'],
  ['spelling', 'The {enviroment=>environment} matters.'],
  ['spelling', 'What a {suprise=>surprise}!'],
  ['spelling', 'I {realy=>really} like it.'],
  ['spelling', 'The {resturant=>restaurant} was full.'],
  ['spelling', 'It was {wonderfull=>wonderful}.'],
  ['spelling', 'I don’t know {wich=>which} one to take.'],
  ['spelling', 'We went to the {libary=>library}.'],
  // capitals
  ['capital', 'See you on {monday=>Monday}.'],
  ['capital', 'My birthday is in {july=>July}.'],
  ['capital', 'I speak {dutch=>Dutch} and Arabic.'],
  ['capital', 'Yesterday {i=>I} went home.'],
  ['capital', 'I was tired. {then=>Then} I slept.'],
  ['capital', 'We celebrate {ramadan=>Ramadan} together.'],
  ['capital', 'She lives in {london=>London}.'],
  ['capital', 'I moved here in {march=>March}.'],
  // grammar: Dutch and Arabic transfer
  ['grammar', 'I {live=>have lived} here since 2015.'],
  ['grammar', 'I have lived here {since=>for} five years.'],
  ['grammar', 'I {have seen=>saw} him yesterday.'],
  ['grammar', 'I {am agree=>agree} with you.'],
  ['grammar', 'I need some {informations=>information}.'],
  ['grammar', 'Thanks for the {advices=>advice}.'],
  ['grammar', 'This one is {more better=>better}.'],
  ['grammar', '{Most of people=>Most people} like music.'],
  ['grammar', 'He {don’t=>doesn’t} like coffee.'],
  ['grammar', 'She {go=>goes} to school by bike.'],
  ['grammar', 'They {likes=>like} pizza.'],
  ['grammar', 'The people {is=>are} friendly here.'],
  ['grammar', 'I {not like=>don’t like} fish.'],
  ['grammar', 'See you {in Monday=>on Monday}.'],
  ['grammar', 'The man {which=>who} lives next door is a doctor.'],
  ['grammar', 'Can you {explain me=>explain to me} the rules?'],
  ['grammar', 'We need to {discuss about=>discuss} the plan.'],
  ['grammar', 'It {depends of=>depends on} the weather.'],
  ['grammar', 'She is married {with=>to} a doctor.'],
  ['grammar', 'Yesterday I {buyed=>bought} a new laptop.'],
  ['grammar', 'I {thinked=>thought} about it.'],
  ['grammar', 'I am interested {for=>in} history.'],
  ['grammar', 'I look forward to {hear=>hearing} from you.'],
  ['grammar', 'I have to {make=>do} my homework.'],
  ['grammar', 'We {made=>took} a lot of photos.'],
  ['grammar', 'I {did=>made} a mistake.'],
  ['grammar', 'Let’s {make a walk=>go for a walk}.'],
  ['grammar', 'Can you {borrow=>lend} me your pen?'],
  ['grammar', 'Can I {lend=>borrow} your pen?'],
  ['grammar', 'She {learned=>taught} me how to swim.'],
  ['grammar', '{He=>He is} very tall.'],
  ['grammar', 'She {is engineer=>is an engineer}.'],
  ['grammar', 'I have {question=>a question}.', 'missing article before a singular noun'],
  ['grammar', '{When I can=>When can I} call you?'],
  ['grammar', 'My son {is=>has been} ill since Monday.'],
  ['grammar', 'The shop assistant {were=>was} very helpful.', 'agreement with a noun subject'],
  ['grammar', 'There are {less=>fewer} parking spaces than last year.', 'strict-mode territory'],
  ['grammar', 'I {made=>did} my first full workout.', 'make/do with workout is not in the list'],
  ['grammar', 'He {can to=>can} swim.', 'modal + to'],
  // articles
  ['article', 'I waited for {a=>an} hour.'],
  ['article', 'She is {a=>an} honest person.'],
  ['article', 'We bought {an=>a} new car.'],
  ['article', 'It is {an=>a} useful tool.'],
  ['article', 'He wants to be {an=>a} European citizen.'],
  ['article', 'I ate {a=>an} apple.'],
  // punctuation and typos
  ['punctuation', 'I love {photo’s=>photos} of old cities.'],
  ['punctuation', 'The {photo’s=>photos} are on my phone.'],
  ['punctuation', 'Wait{ ,=>,} I am coming.'],
  ['punctuation', 'I am tired{،=>,} so I go home.'],
  ['punctuation', 'I saw {the the=>the} movie.'],
  ['punctuation', 'Hello{,there=>, there}.'],
  // variety (en-US dictionary)
  ['variety', 'My favorite {colour=>color} is blue, and my favorite flavor is lemon.'],
]
