import { definePack } from '../build'

// English words that sound alike (or nearly) and swap places when typing fast.

export const its = definePack({
  id: 'en.its',
  lang: 'en',
  title: "its / it's",
  blurb: 'Possessive its against the short form of it is and it has.',
  rule: {
    en: "*its* means belonging to it and has no apostrophe, just like *his* and *hers*. *it's* is short for *it is* or *it has*.\n\nThe trick: read it aloud as *it is* or *it has*. If the sentence still works, write *it's*. If it doesn't, write *its*.",
  },
  hints: {
    its: { en: 'Belonging to it: its, no apostrophe. Like his and hers.' },
    is: { en: "It is fits here, so it's." },
    has: { en: "It has fits here (it has been), so it's." },
  },
  items: [
    ["The company changed {{its|it's}} logo.", 'its'],
    ["{{It's|Its}} getting late.", 'is'],
    ["The cat licked {{its|it's}} paws.", 'its'],
    ["{{It's|Its}} been a long week.", 'has'],
    ["I think {{it's|its}} going to rain.", 'is'],
    ["The tree lost all {{its|it's}} leaves.", 'its'],
    ["Every country has {{its|it's}} own rules.", 'its'],
    ["{{It's|Its}} not your fault.", 'is'],
    ["The team won {{its|it's}} first match.", 'its'],
    ["{{It's|Its}} hard to say.", 'is'],
    ["The phone is old, but {{its|it's}} battery still lasts all day.", 'its'],
    ["Do you know if {{it's|its}} open on Sundays?", 'is'],
    ["The bird built {{its|it's}} nest in our chimney.", 'its'],
    ["{{It's|Its}} got four wheels and no brakes.", 'has'],
    ["The city is famous for {{its|it's}} canals.", 'its'],
    ["Close the window, {{it's|its}} cold in here.", 'is'],
    ["The museum moved {{its|it's}} entrance to the side street.", 'its'],
    ["{{It's|Its}} up to you.", 'is'],
    ["The dog wagged {{its|it's}} tail.", 'its'],
    ["I like this app, but {{its|it's}} menus are confusing.", 'its'],
    ["{{It's|Its}} already half past nine.", 'is'],
    ["The plan has {{its|it's}} problems.", 'its'],
    ["The film was good, but {{it's|its}} too long.", 'is'],
    ["{{It's|Its}} been ages since we last met.", 'has'],
  ],
})

export const your = definePack({
  id: 'en.your',
  lang: 'en',
  title: "your / you're",
  blurb: 'Belonging to you, or you are.',
  rule: {
    en: "*your* means belonging to you: *your bag*. *you're* is short for *you are*: *you're late*.\n\nThe trick: say *you are*. If it fits, write *you're*. If something of yours follows, write *your*.",
  },
  hints: {
    your: { en: 'Something of yours follows: your.' },
    youre: { en: "You are fits here, so you're." },
  },
  items: [
    ["{{You're|Your}} going to love this.", 'youre'],
    ["Is this {{your|you're}} bag?", 'your'],
    ["{{You're|Your}} welcome.", 'youre'],
    ["Don't forget {{your|you're}} keys.", 'your'],
    ["I think {{you're|your}} right.", 'youre'],
    ["What's {{your|you're}} address?", 'your'],
    ["{{You're|Your}} late again.", 'youre'],
    ["Thanks for {{your|you're}} help.", 'your'],
    ["If {{you're|your}} tired, go to bed.", 'youre'],
    ["{{Your|You're}} English is getting really good.", 'your'],
    ["Let me know when {{you're|your}} ready.", 'youre'],
    ["Can I borrow {{your|you're}} charger?", 'your'],
    ["{{You're|Your}} not the only one.", 'youre'],
    ["How was {{your|you're}} weekend?", 'your'],
    ["I hope {{you're|your}} feeling better.", 'youre'],
    ["Wash {{your|you're}} hands before dinner.", 'your'],
    ["{{You're|Your}} always so calm.", 'youre'],
    ["Is that {{your|you're}} brother over there?", 'your'],
    ["{{You're|Your}} on the wrong train.", 'youre'],
    ["I like {{your|you're}} new haircut.", 'your'],
    ["{{Your|You're}} train leaves in ten minutes.", 'your'],
    ["Call me if {{you're|your}} lost.", 'youre'],
  ],
})

export const their = definePack({
  id: 'en.their',
  lang: 'en',
  title: "their / there / they're",
  blurb: 'Three spellings, one sound.',
  rule: {
    en: "*their* means belonging to them: *their house*. *there* is a place, or the start of *there is* and *there are*. *they're* is short for *they are*.\n\nThe trick: *they're* passes the *they are* test. *their* is followed by something they own. *there* hides the word *here*: here and there.",
  },
  hints: {
    their: { en: 'Something of theirs follows: their.' },
    there: { en: 'A place, or there is / there are: there. It has here inside it.' },
    theyre: { en: "They are fits here, so they're." },
  },
  items: [
    ["{{Their|There|They're}} house is next to the park.", 'their'],
    ["{{They're|Their|There}} always late on Mondays.", 'theyre'],
    ["Put the box over {{there|their|they're}}.", 'there'],
    ["{{There|Their|They're}} is a problem with the printer.", 'there'],
    ["The kids forgot {{their|there|they're}} lunch.", 'their'],
    ["I think {{they're|their|there}} at the gym.", 'theyre'],
    ["{{There|Their|They're}} are three eggs left.", 'there'],
    ["The Smiths sold {{their|there|they're}} car.", 'their'],
    ["{{They're|Their|There}} coming tomorrow.", 'theyre'],
    ["Is anyone {{there|their|they're}}?", 'there'],
    ["Students must bring {{their|there|they're}} own laptops.", 'their'],
    ["{{They're|Their|There}} not sure yet.", 'theyre'],
    ["We stayed {{there|their|they're}} for a week.", 'there'],
    ["Ask them if {{they're|their|there}} hungry.", 'theyre'],
    ["{{Their|There|They're}} dog barks at everyone.", 'their'],
    ["{{There|Their|They're}} were no seats left.", 'there'],
    ["{{They're|Their|There}} both teachers.", 'theyre'],
    ["The players shook {{their|there|they're}} heads.", 'their'],
    ["I've never been {{there|their|they're}} before.", 'there'],
    ["{{They're|Their|There}} getting married in June.", 'theyre'],
    ["Is {{there|their|they're}} any milk left?", 'there'],
    ["They did {{their|there|they're}} best.", 'their'],
  ],
})

export const thenThan = definePack({
  id: 'en.then-than',
  lang: 'en',
  title: 'then / than',
  blurb: 'Comparison or time. Dutch dan covers both.',
  rule: {
    en: '*than* compares: *taller than*, *rather than*, *more than*. *then* is about time or order: *first this, then that*, and *if ... then*.\n\nDutch *dan* covers both, which is why this one slips out. The trick: comparing? *than*, with an a, like compare. Time? *then*, with an e, like when.',
  },
  hints: {
    than: { en: 'A comparison (taller, more, rather): than, with an a like compare.' },
    then: { en: 'Time or order (first, next, after that): then, with an e like when.' },
  },
  items: [
    ['This test is harder {{than|then}} the last one.', 'than'],
    ['Finish your work, and {{then|than}} we can go.', 'then'],
    ['She is taller {{than|then}} her brother.', 'than'],
    ['First we eat, {{then|than}} we watch the film.', 'then'],
    ["I'd rather walk {{than|then}} take the bus.", 'than'],
    ["If you're tired, {{then|than}} go to bed.", 'then'],
    ['It costs more {{than|then}} I expected.', 'than'],
    ['We lived in Utrecht back {{then|than}}.', 'then'],
    ['My new laptop is faster {{than|then}} my old one.', 'than'],
    ['Turn left, {{then|than}} take the second right.', 'then'],
    ['Nobody knows more about cheese {{than|then}} my uncle.', 'than'],
    ['Since {{then|than}}, he has never been late.', 'then'],
    ['It took longer {{than|then}} we planned.', 'than'],
    ['Can you wait until {{then|than}}?', 'then'],
    ['There were fewer people {{than|then}} last year.', 'than'],
    ['He said goodbye and {{then|than}} left.', 'then'],
    ['Better late {{than|then}} never.', 'than'],
    ['Every now and {{then|than}} I eat meat.', 'then'],
    ['I have less time {{than|then}} you think.', 'than'],
    ['What happened {{then|than}}?', 'then'],
    ['She earns more {{than|then}} her boss.', 'than'],
    ['Back {{then|than}}, nobody had a phone.', 'then'],
  ],
})

export const loseLoose = definePack({
  id: 'en.lose-loose',
  lang: 'en',
  title: 'lose / loose',
  blurb: 'The verb with one o, the adjective with two.',
  rule: {
    en: '*lose* (one o, rhymes with *choose*) is the verb: to misplace something or not to win. *loose* (two o\'s, rhymes with *goose*) means not tight.\n\nDutch speakers tend to end both with an s sound, so they sound the same. The trick: *loose* has an extra o, as if it had come loose.',
  },
  hints: {
    lose: { en: 'The verb, to misplace or not win: lose, one o.' },
    loose: { en: 'Not tight, not fixed: loose, two o\'s.' },
  },
  items: [
    ["Don't {{lose|loose}} your ticket.", 'lose'],
    ['This shirt is too {{loose|lose}}.', 'loose'],
    ['I always {{lose|loose}} my keys.', 'lose'],
    ['One of the screws is {{loose|lose}}.', 'loose'],
    ["If we {{lose|loose}} this match, we're out.", 'lose'],
    ['The dog got {{loose|lose}} and ran into the park.', 'loose'],
    ['I want to {{lose|loose}} a few kilos.', 'lose'],
    ['My tooth is {{loose|lose}}.', 'loose'],
    ['You have nothing to {{lose|loose}}.', 'lose'],
    ['She wears her hair {{loose|lose}}.', 'loose'],
    ['Try not to {{lose|loose}} your temper.', 'lose'],
    ["There's a {{loose|lose}} wire behind the TV.", 'loose'],
    ["We can't afford to {{lose|loose}} any more time.", 'lose'],
    ["Tie the rope tighter, it's coming {{loose|lose}}.", 'loose'],
    ['Did you {{lose|loose}} your phone again?', 'lose'],
    ['These jeans feel {{loose|lose}} around the waist.', 'loose'],
    ["Don't {{lose|loose}} hope.", 'lose'],
    ['I hate it when I {{lose|loose}} at chess.', 'lose'],
    ['The lid is {{loose|lose}}, so be careful.', 'loose'],
    ['Players who {{lose|loose}} three games are out.', 'lose'],
  ],
})

export const affectEffect = definePack({
  id: 'en.affect-effect',
  lang: 'en',
  title: 'affect / effect',
  blurb: 'Usually the verb and the noun.',
  rule: {
    en: '*affect* is usually the verb: to change or influence something. *effect* is usually the noun: the result. The weather *affects* your mood; it has an *effect* on your mood.\n\nThe trick: a for action (the verb), e for end result (the noun). After *a*, *an*, *the* or an adjective you need the noun, *effect*.',
  },
  hints: {
    affect: { en: 'A verb is needed here (to influence): affect, a for action.' },
    effect: { en: 'A noun is needed here (the result): effect, e for end result.' },
  },
  items: [
    ['The weather can {{affect|effect}} your mood.', 'affect'],
    ['The new law had no {{effect|affect}} on prices.', 'effect'],
    ['Does coffee {{affect|effect}} your sleep?', 'affect'],
    ['The medicine started to take {{effect|affect}} after an hour.', 'effect'],
    ['How will this {{affect|effect}} our plans?', 'affect'],
    ['The film has amazing special {{effects|affects}}.', 'effect'],
    ['The strike will {{affect|effect}} thousands of passengers.', 'affect'],
    ['Stress has a big {{effect|affect}} on your health.', 'effect'],
    ['Her words really {{affected|effected}} me.', 'affect'],
    ['The side {{effects|affects}} are usually mild.', 'effect'],
    ["The cold doesn't seem to {{affect|effect}} him.", 'affect'],
    ['What {{effect|affect}} did the change have?', 'effect'],
    ['Noise can {{affect|effect}} how well children learn.', 'affect'],
    ['The rule comes into {{effect|affect}} in January.', 'effect'],
    ['Nobody was {{affected|effected}} by the power cut.', 'affect'],
    ['Music has a calming {{effect|affect}} on me.', 'effect'],
    ['Will the delay {{affect|effect}} my connection?', 'affect'],
    ['The {{effect|affect}} was immediate.', 'effect'],
    ['Rising prices {{affect|effect}} everyone.', 'affect'],
    ['I could feel the {{effect|affect}} of the coffee.', 'effect'],
  ],
})

export const whose = definePack({
  id: 'en.whose',
  lang: 'en',
  title: "whose / who's",
  blurb: 'Belonging to whom, or who is and who has.',
  rule: {
    en: "*whose* asks or tells who something belongs to: *Whose coat is this?* *who's* is short for *who is* or *who has*.\n\nThe trick: try *who is* or *who has*. If it fits, write *who's*. If it doesn't, write *whose*.",
  },
  hints: {
    whose: { en: 'Belonging to whom: whose.' },
    is: { en: "Who is fits here, so who's." },
    has: { en: "Who has fits here (who has been), so who's." },
  },
  items: [
    ["{{Whose|Who's}} coat is this?", 'whose'],
    ["{{Who's|Whose}} coming tonight?", 'is'],
    ["{{Who's|Whose}} there?", 'is'],
    ["The woman {{whose|who's}} car was stolen called the police.", 'whose'],
    ["Do you know {{who's|whose}} in charge?", 'is'],
    ["{{Whose|Who's}} turn is it?", 'whose'],
    ["{{Who's|Whose}} been using my laptop?", 'has'],
    ["I met a man {{whose|who's}} brother lives in Utrecht.", 'whose'],
    ["{{Who's|Whose}} your best friend?", 'is'],
    ["{{Whose|Who's}} phone keeps ringing?", 'whose'],
    ["{{Who's|Whose}} going to tell her?", 'is'],
    ["That's the teacher {{whose|who's}} class I liked most.", 'whose'],
    ["Guess {{who's|whose}} back.", 'is'],
    ["{{Whose|Who's}} idea was this?", 'whose'],
    ["{{Who's|Whose}} seen my keys?", 'has'],
    ["The students {{whose|who's}} names are on the list can go.", 'whose'],
    ["{{Who's|Whose}} that girl with the red hat?", 'is'],
    ["I don't know {{whose|who's}} bag this is.", 'whose'],
    ["{{Who's|Whose}} ready for dessert?", 'is'],
    ["{{Whose|Who's}} shoes are these?", 'whose'],
  ],
})

export const toToo = definePack({
  id: 'en.to-too',
  lang: 'en',
  title: 'to / too / two',
  blurb: 'Direction, also and too much, and the number.',
  rule: {
    en: '*to* shows direction (*to the beach*) or comes before a verb (*to go*). *too* means also, or more than enough: *me too*, *too hot*. *two* is the number 2.\n\nThe trick: *too* has one o too many, just like something that is too much.',
  },
  hints: {
    to: { en: 'Direction, or before a verb: to.' },
    much: { en: 'More than enough: too, with the extra o.' },
    also: { en: 'Meaning also: too.' },
    two: { en: 'The number 2: two.' },
  },
  items: [
    ['I want {{to|too}} go home.', 'to'],
    ['This soup is {{too|to}} hot.', 'much'],
    ['Can I come {{too|to}}?', 'also'],
    ["We're going {{to|too}} the beach.", 'to'],
    ["It's {{too|to}} late to call her now.", 'much'],
    ['I like pizza. Me {{too|to}}.', 'also'],
    ['She drove {{to|too}} Amsterdam.', 'to'],
    ['You work {{too|to}} hard.', 'much'],
    ['I need {{to|too}} buy milk.', 'to'],
    ['My sister is coming {{too|to}}.', 'also'],
    ['The box is {{too|to}} heavy for me.', 'much'],
    ['Give it {{to|too}} me.', 'to'],
    ["Don't eat {{too|to}} much sugar.", 'much'],
    ['He forgot {{to|too}} lock the door.', 'to'],
    ['I have {{two|too|to}} brothers.', 'two'],
    ["It's never {{too|to}} late.", 'much'],
    ['Say hello {{to|too}} your parents.', 'to'],
    ["That's {{too|to}} bad.", 'much'],
    ["I've been {{to|too}} Morocco twice.", 'to'],
    ['She speaks Arabic, and Dutch {{too|to}}.', 'also'],
    ['We waited for {{two|too|to}} hours.', 'two'],
    ['The music is {{too|to}} loud.', 'much'],
  ],
})
