import { definePack } from '../build'

// English usage traps, several of them Dutch interference (since + present, lenen, leren, maken).

export const aAn = definePack({
  id: 'en.a-an',
  lang: 'en',
  title: 'a / an',
  blurb: 'Chosen by sound, not by letter.',
  rule: {
    en: 'Choose by sound, not by letter. Before a vowel sound: *an* (*an apple*, *an hour*, *an MBA*). Before a consonant sound: *a* (*a car*, *a university*, *a one-way street*).\n\nThe trick: say it out loud. *Hour* starts with a vowel sound because the h is silent. *University* starts with a y sound, and *one* with a w sound.',
  },
  hints: {
    vowel: { en: 'Starts with a vowel sound: an.' },
    consonant: { en: 'Starts with a consonant sound: a.' },
    silent: { en: 'The h is silent, so the word starts with a vowel sound: an.' },
    you: { en: 'Starts with a y sound (you, yoo): a.' },
    w: { en: 'One starts with a w sound: a.' },
    letter: { en: 'Letters and numbers go by how you say them: an M (em), an 8 (eight), a U (you).' },
  },
  items: [
    ["I'll be there in {{an|a}} hour.", 'silent'],
    ['She studies at {{a|an}} university in Leiden.', 'you'],
    ['He ate {{an|a}} apple on the way to work.', 'vowel'],
    ['It was {{an|a}} honest mistake.', 'silent'],
    ['I need {{a|an}} new phone.', 'consonant'],
    ['She has {{an|a}} MBA from Rotterdam.', 'letter'],
    ["That's {{a|an}} useful tip.", 'you'],
    ['We saw {{an|a}} owl in the garden.', 'vowel'],
    ["He's {{a|an}} European citizen.", 'you'],
    ['{{An|A}} hour later, the train finally arrived.', 'silent'],
    ['I got {{an|a}} 8 for my test.', 'letter'],
    ["It's {{a|an}} one-way street.", 'w'],
    ['She bought {{an|a}} umbrella.', 'vowel'],
    ['He wears {{a|an}} uniform at work.', 'you'],
    ['I have {{an|a}} idea.', 'vowel'],
    ['Can you send me {{an|a}} email?', 'vowel'],
    ['He works for {{an|a}} NGO.', 'letter'],
    ["That's {{an|a}} unusual name.", 'vowel'],
    ['She lives in {{a|an}} house by the sea.', 'consonant'],
    ['We need {{an|a}} extra chair.', 'vowel'],
    ['My sister is {{an|a}} engineer.', 'vowel'],
    ['Is there {{a|an}} hotel near the station?', 'consonant'],
  ],
})

export const sinceFor = definePack({
  id: 'en.since-for',
  lang: 'en',
  title: 'since / for',
  blurb: 'A starting point or a length of time, with the present perfect.',
  rule: {
    en: '*for* goes with a length of time (*for three years*), *since* with a starting point (*since 2019*, *since Monday*).\n\nWhen something started in the past and is still true, English uses the present perfect: *I have lived here since 2019*. Dutch uses the present tense (*ik woon hier sinds 2019*), which is why *I live here since 2019* slips out. The trick: *since* or *for* plus up to now means *have* + past participle.',
  },
  hints: {
    for: { en: 'A length of time (six years, a week, ages): for.' },
    since: { en: 'A starting point (2019, Monday, breakfast): since.' },
    pp: { en: 'Started in the past and still true: present perfect, have + participle.' },
  },
  items: [
    ['I have lived here {{for|since}} six years.', 'for'],
    ['I have lived here {{since|for}} 2019.', 'since'],
    ['She has worked at the bank {{since|for}} March.', 'since'],
    ["We've been waiting {{for|since}} twenty minutes.", 'for'],
    ['I {{have known|know}} him since primary school.', 'pp'],
    ['They {{have been|are}} married for ten years.', 'pp'],
    ["He hasn't called {{since|for}} Tuesday.", 'since'],
    ["I haven't seen her {{for|since}} ages.", 'for'],
    ['How long {{have you lived|do you live}} in Amsterdam?', 'pp'],
    ['We {{have had|have}} this car since 2015.', 'pp'],
    ['It has rained {{since|for}} this morning.', 'since'],
    ['She has been ill {{for|since}} a week.', 'for'],
    ['I {{have been learning|learn}} Dutch for two years.', 'pp'],
    ['Nobody has used this room {{since|for}} the party.', 'since'],
    ['He {{has worked|works}} here since January.', 'pp'],
    ["I've been awake {{since|for}} five o'clock.", 'since'],
    ["We've known each other {{for|since}} a long time.", 'for'],
    ['They {{have lived|live}} next door for three years.', 'pp'],
    ["I haven't eaten {{since|for}} breakfast.", 'since'],
    ['She has played the piano {{for|since}} most of her life.', 'for'],
    ['My phone {{has been|is}} broken since yesterday.', 'pp'],
    ["It's been quiet {{since|for}} the kids left.", 'since'],
  ],
})

export const makeDo = definePack({
  id: 'en.make-do',
  lang: 'en',
  title: 'make / do',
  blurb: 'Creating something or doing a task, plus take a photo and have fun.',
  rule: {
    en: '*make* is for creating or producing something: *make a cake*, *make a mistake*, *make a decision*, *make money*. *do* is for tasks, jobs and activities: *do homework*, *do the dishes*, *do your best*.\n\nDutch *maken* covers more ground than *make*, so watch the fixed phrases: you *do* homework, *take* a photo, *take* a walk and *have* fun.',
  },
  hints: {
    make: { en: 'Creating or producing something: make.' },
    do: { en: 'A task, job or activity: do.' },
    take: { en: 'Fixed phrase: take a photo, take a walk. Not make.' },
    have: { en: 'Fixed phrase: have fun. Dutch plezier maken, English have fun.' },
  },
  items: [
    ['I still have to {{do|make}} my homework.', 'do'],
    ['Can you {{make|do}} a reservation for four?', 'make'],
    ['Everybody {{makes|does}} mistakes.', 'make'],
    ["Who's going to {{do|make}} the dishes?", 'do'],
    ['She {{made|did}} a cake for my birthday.', 'make'],
    ['I {{did|made}} the shopping on Saturday.', 'do'],
    ['We need to {{make|do}} a decision today.', 'make'],
    ["Don't {{make|do}} so much noise.", 'make'],
    ['He {{does|makes}} yoga every morning.', 'do'],
    ["I'll {{make|do}} some coffee.", 'make'],
    ['Just {{do|make}} your best.', 'do'],
    ['Let me {{take|make}} a photo of you two.', 'take'],
    ['We {{had|made}} a lot of fun at the party.', 'have'],
    ['She {{makes|does}} a lot of money.', 'make'],
    ['I have to {{make|do}} a phone call.', 'make'],
    ['Have you {{done|made}} the laundry?', 'do'],
    ["It's hard to {{make|do}} friends in a new city.", 'make'],
    ['They {{do|make}} business with China.', 'do'],
    ['Can you {{make|do}} the bed?', 'make'],
    ['He {{did|made}} a great job.', 'do'],
    ['We {{took|made}} a walk along the beach.', 'take'],
    ['I {{made|did}} an appointment with the dentist.', 'make'],
    ['Did you {{make|do}} any plans for the weekend?', 'make'],
    ["I'll {{do|make}} the cooking if you do the cleaning.", 'do'],
  ],
})

export const lendTeach = definePack({
  id: 'en.lend-teach',
  lang: 'en',
  title: 'lend / borrow, teach / learn',
  blurb: 'Dutch lenen and leren each cover two English verbs.',
  rule: {
    en: '*lend* is to give something for a while; *borrow* is to take something for a while. *teach* is to give knowledge; *learn* is to get it.\n\nDutch uses one verb for each pair (*lenen*, *leren*), so English needs a second look. The trick: a person right after the verb (*lend me*, *teach you*) means *lend* or *teach*. Borrowing and learning come with *from*.',
  },
  hints: {
    lend: { en: 'Giving something for a while: lend. Lend me your pen.' },
    borrow: { en: 'Taking something for a while: borrow. Borrow it from someone.' },
    teach: { en: 'Giving knowledge to someone: teach.' },
    learn: { en: 'Getting knowledge yourself: learn.' },
  },
  items: [
    ['Can you {{lend|borrow}} me your pen?', 'lend'],
    ['Can I {{borrow|lend}} your pen?', 'borrow'],
    ['My father {{taught|learned}} me to swim.', 'teach'],
    ['I {{learned/learnt|taught}} to swim when I was six.', 'learn'],
    ['She {{lent|borrowed}} me ten euros.', 'lend'],
    ['I {{borrowed|lent}} a book from the library.', 'borrow'],
    ['Who {{taught|learned}} you to cook like this?', 'teach'],
    ['You can {{learn|teach}} a lot from your mistakes.', 'learn'],
    ['Could you {{lend|borrow}} me your car this weekend?', 'lend'],
    ['May I {{borrow|lend}} your umbrella?', 'borrow'],
    ['He {{teaches|learns}} English at a secondary school.', 'teach'],
    ["I'm {{learning|teaching}} Dutch at evening classes.", 'learn'],
    ['Never {{lend|borrow}} money to friends.', 'lend'],
    ['We had to {{borrow|lend}} chairs from the people next door.', 'borrow'],
    ['Can you {{teach|learn}} me how to use this app?', 'teach'],
    ['Children {{learn|teach}} languages quickly.', 'learn'],
    ["The bank won't {{lend|borrow}} us any more money.", 'lend'],
    ['Can I {{borrow|lend}} your phone for a second?', 'borrow'],
    ['My grandmother {{taught|learned}} me this recipe.', 'teach'],
    ['I want to {{learn|teach}} how to play the guitar.', 'learn'],
    ['He {{borrowed|lent}} my bike and never gave it back.', 'borrow'],
    ['Experience {{teaches|learns}} you more than books do.', 'teach'],
  ],
})
